### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by SourMesen** [SourMesen/Mesen#1]
I think, Mesen need also Paths like nestopia and fceux - this will make Mesen more usefull, because not all users can like when you can't choose paths. To example:

D:\Games\Mesen\save\  - for **Save Data** (savestates) ;
D:\Games\Mesen\cheats\ - for **Cheats**

> Originally created at 2016-08-15 14:36:38+00:00 (UTC) by medigi as a(n) minor issue.

**Comment by SourMesen** [comment]
Thanks for the suggestion, I'll keep it in mind, but I'm not sure if I want to add that many settings for something that probably wouldn't really be used very often.

If your main objective is to keep everything together, you can rename the executable to Mesen_P.exe.  If you do this, Mesen will load/save all of its settings in the same folder as the .exe file.

i.e:

..\Mesen_P.exe

..\Mesen\SaveStates

..\Mesen\Screenshots

**Comment by ImJezze** [comment]
I just discover Mesen and I really like it so far, except the mentioned issue here. ;)

Thanks for the hint how to keep files in its program folder. This helps a lot. You should add this info on Mesen's homepage. I'm sure many people would expect this as default behavior. The .\Mesen\ sub-folder is actually not necessary.

Keep up your great work.

**Comment by SourMesen** [comment]
Thanks for the comment!

Is your main concern being able to select the path, or simply having all of Mesen's files in the same folder?
The current concept is a bit like uTorrent's - you just drop the exe file anywhere, run it from there and not worry about where it is saving its settings.  I think this works nicely in most cases, but obviously some people want/need more control over it.

If the current Mesen_P solution is good enough for you, maybe an option in the UI along the lines of "Keep all of Mesen's settings and files in the same folder as Mesen" would work?  (i.e to avoid having to rename the executable file and make the option more obvious to everybody).

**Comment by ImJezze** [comment]
I don't need to be able to select the path, I just want to keep files related to Mesen in its folder. The only reason for me to store the settings in "My Documents" is to have different profiles for different users. 
But I like the idea of an option to choose between both behaviors.

And if I want to change the paths for several sub-folders like save states and screenshots, I can use junctions or symbolic links. For me path selection would be nice to have but not a requirement. However I can't talk for everyone, it's just my personal opinion.

**Comment by medigi** [comment]
This is not 100% issue, it's more like idea then issue. Too bad users like ImJezze didn't understanded this. And i was writed this issue to help and / or try improve mesen, not to ruin it.

**Comment by ImJezze** [comment]
What did I not understand?

I clearly understand, that many people want to configure each path separately and that it is a quasi-standard for the most emulators. But such a feature is not that important to me, because there are other possibilities to redirect a path. This does not mean it will never be implemented, only because I have another opinion.

**Comment by sczther** [comment]
I think that simply the best option would be to have them configurable in a options.ini file or something similar as that would open the possibility to advanced users whilst not confusing newbies.

**Comment by Nicholas-Steel** [comment]
For me, it would be nice to have 2 separate File Open dialog boxes each using their own Path variable. One for Music files and the other for ROM files.

I don't have the music files in a remotely similar location to the ROM files.

**Comment by SourMesen** [comment]
This is fixed by 7a44c547eedbf3cf42ac7a6f45e7de51d951b940 which adds a first-launch config wizard (which won't be seen by anyone who's already executed Mesen once) and a number of folder-related options in the preferences.

![setupwizard](https://user-images.githubusercontent.com/21093973/29237909-3479adc8-7ef6-11e7-8388-72962ad5d3a6.png)

![pathconfig](https://user-images.githubusercontent.com/21093973/29237921-5bafd69c-7ef6-11e7-861e-b54111449faf.png)

**Comment by Nicholas-Steel** [comment]
Awesome stuff, thank you.
