### ISSUE TITLE
Fast Forward Speed 

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#102]
Is there a way we can make fast forward speed any faster than zero? I ask because when trying to read the story on the game Ikari Warriors 2 it's to slow to read even with speed set to zero.

**Comment by SourMesen** [comment]
Unfortunately, no - 0 means your computer is running the emulation as fast as it can.
Making it any faster would require speed hacks, which could cause games to break while fast forwarding, or optimizing Mesen's code to run faster in general (which is easier said than done).

**Comment by Cibomatto2002** [comment]
oh OK Thanks for your time.
