### ISSUE TITLE
Super Robin Hood (NES) flashing

### ISSUE THREAD

**Issue by DormouseMarlene** [SourMesen/Mesen#103]
With enabled option "Remove sprite limit (Reduces flashing)" in some areas of this game flashing sprites.

**Comment by SourMesen** [comment]
The "Remove sprite limit (Reduces flashing)" option, like the name says, reduces the flashing in some circumstances, but it can't remove flashing completely in all games.
It removes the sprite limit on a specific line, but there is still a limit to the number of sprites visible on the whole screen, and the way the game is coded can also have an impact on how much flashing occurs.
