### ISSUE TITLE
iBuffalo Famicom USB A/B Buttons Pressed Simultaneously

### ISSUE THREAD

**Issue by I-Like-MGS2** [SourMesen/Mesen#105]
I didn't want to make an account, but since this problem has been bothering me for a while, I felt the need to address this issue.

So anyway, I have the iBuffalo Famicom controller (BGCFC801) and whenever I'm trying to jump or shoot, the emulator thinks I'm pressing both A and B simultaneously, despite that I have both buttons mapped differently. But if I use a different emulator, say Nestopia or puNES, it doesn't do that.

I want to use this emulator, but the issue that's been bothering me apparently hasn't been resolved since I last used it (I think this problem persisted since 0.5.3 I guess, can't really remember).

Thanks for reading this.

**Comment by SourMesen** [comment]
There are multiple key sets that can be configured for each player.
e.g: The "Keyset #1", "Keyset #2", etc. tabs in the configuration for player 1.
Are you sure you don't have the same keys mapped to different buttons in different tabs?
The default bindings use the first 3 tabs to support a large number of typical defaults, so it is possible these bindings are in conflict with the bindings you did (probably in the first tab)

**Comment by I-Like-MGS2** [comment]
Welp, I'm an idiot then. I was gonna say that Keyset No.2 was WASD Key configuration, but I thought that No.3 wasn't being used, yet here I am.

Guess this was pretty pointless after all.
