### ISSUE TITLE
Mapper 190 needed for Magic Kid Googoo.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#106]
Magic Kid Googoo just got dumped and needs Mapper 190.

Maybe this will help you with adding the mapper.

https://sourceforge.net/p/fceultra/code/3334/

**Comment by SourMesen** [comment]
Thanks for the request - a few other people also asked me the same thing :)
Support for mapper 190 is added by d44c8f78088e80495626dbac921b4f388ae42b89
It'll be in the next release, which I'll probably do later today.

**Comment by Cibomatto2002** [comment]
Thank you.
 

    On Saturday, February 18, 2017 11:55 AM, SourMesen <notifications@github.com> wrote:
 

 Thanks for the request - a few other people also asked me the same thing :)
Support for mapper 190 is added by d44c8f7
It'll be in the next release, which I'll probably do later today.—
