### ISSUE TITLE
save state error

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#107]
This happens to me from time to time in different games You will save the game with the F1 key then reload it sometimes you will see  grafx errors. I uploaded a save state for you to see when i'm talking about.

[Batman - Return of the Joker (U) [!]_1.zip](https://github.com/SourMesen/Mesen/files/781828/Batman.-.Return.of.the.Joker.U._1.zip)

**Comment by Cibomatto2002** [comment]
Batman - Return of the Joker will crash the Emulator.
![capture1-11-2017-2 06 54 am2-16-2017-6 56 39 pm](https://cloud.githubusercontent.com/assets/21169038/23048228/109ce002-f47a-11e6-8d0a-ef0e488e0efe.jpg)

**Comment by SourMesen** [comment]
Thanks for the report! This was a bug specific to mapper 69 (Sunsoft FME7) -fixed by 37bbb5ea7ae8fe066637115d56c5d45064070d0c
The savestates you have still won't work after this fix, though - you'll need to create new save states in the next release for them to work properly.
