### ISSUE TITLE
Feature Request: Lower Bar

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#108]
PuNes, and Bizhawk have lower bars in their interfaces. It is used for saves, profiles, and rewind. Bizhawk also uses it to show information. I think it could me very useful. 
![image](https://cloud.githubusercontent.com/assets/24971871/23098635/4e553a52-f632-11e6-908c-c4907c81f54b.png)

**Comment by Cibomatto2002** [comment]
If something like this gets added in i hope there is a option to disable it on the screen it looks like it takes a lot of the screen up and i like a big screen when playing games.

**Comment by PinkLouie** [comment]
Agreed. This bar being hideable is better. Customization is always good. An even later version could be more customizable. You being able to add the buttons and menus you think are more useful to you. But at the beginning, something simple would be already great.

**Comment by SourMesen** [comment]
I'm closing this for now - it's not a bad idea, but I don't really see any real use for it right now.
I implemented rewind like it is in Nestopia (you hold down a key and it shows the game playing in reverse until you let the button go), so there is no need for a bottom bar for this.  Save states already have a number of shortcut keys, so I don't really think they need to be shown there on top of that, too.
"Additional information" can now also be shown in the title bar as an option (like puNES does in your screenshot).
