### ISSUE TITLE
Air Fortress (J) Graphics Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#110]
Game will not load graphics correct unless you reset the emulator. Here is a video.
 of the bug.

https://www.youtube.com/watch?v=KGmuqZvrunM&feature=youtu.be&spfreload=10

**Comment by SourMesen** [comment]
I'm not getting any issue on my end.
Can you check the CRC values for the rom you're using in the Log Window?

This is what I have:
Loading rom: Air Fortress (J) [!].nes
File CRC32: 0x53CB7CED
PRG+CHR CRC32: 0x3E785DC3

If it's the same, maybe it's some option in your settings that is causing this.

**Comment by Cibomatto2002** [comment]
Download another copy and it works sorry about that. Is there a tool that can check the CRC32 of all my games to see if there good sets or not I have had these roms for years.

**Comment by SourMesen** [comment]
I've never actually used it myself, but I think this is what "GoodTools" is meant to do.

Also, Mesen itself can be used to validate most common/licensed games.
In the log window, you should see either:
[DB] Game found in database
[DB] Game not found in database
when loading a rom.

If your rom is supposed to be a licensed game and it's not found in the database, the ROM itself might be bad.

**Comment by Cibomatto2002** [comment]
it would be nice if there was a window that would pop up when a rom is not supposed in the database that way we could look for another copy of the rom that would be in the database.
