### ISSUE TITLE
Update palettes

### ISSUE THREAD

**Issue by StephenSheehan** [SourMesen/Mesen#114]
Hope this isn't too small, but FirebrandX has updated the NES Classic palette, renamed Unsaturated to Nostalgia then to Direct Capture and released a georgous PVM-based palette.

**Comment by SourMesen** [comment]
Thanks for letting me know!
I renamed "Nostalgia" to "Composite Direct" (which is its current name) - the palette was exactly the same.
I also added the PVM style palette & the original hardware palette, and updated the NES Classic palette.
(Fixed by e4ad22ddfbde31ea8b372912330dcdbb9203d0f9)
