### ISSUE TITLE
Cheat Finder Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#115]
Trying to make codes for Rad racer 2 I already know the code to stop the time it's 3C:3B. But the Cheat Finder will not select that to be used instead it keeps showing 076E no matter what  I click on. here is a video of the bug.

https://www.youtube.com/watch?v=CuNZWpD3CNc&feature=youtu.be

**Comment by SourMesen** [comment]
Thanks for the bug report!
This is fixed by b22ceea5302aa683f857a414d2d6d97f5b8b78ed
