### ISSUE TITLE
[feature] Sharp bilinear

### ISSUE THREAD

**Issue by phly95** [SourMesen/Mesen#118]
there's a filter in retroarch which I believe is called sharp bilinear, which gets rid of shimmering at non-integer values without getting rid of the "retro" look. I think that would be a great option to add under filters. Also awesome work! This is probably the only emulator that overclocks the NES properly without any audio issues.

**Comment by SourMesen** [comment]
Hey, thanks for the request.
I'm not too familiar with the filter you mentioned, but from what I am reading you should be able to achieve a similar effect in Mesen:

Options -> Video -> Picture tab:
Select the Prescale 2x/3x/4x filter, depending how big your screen is.
Check the "Use bilinear interpolation when scaling" option.

From what I understand, the sharp-bilinear filter does essentially the same thing.

**Comment by phly95** [comment]
Cool, I didn't even think of that. I set it to prescale 4x, and then had it downscale using bilinear filtering to 1080p, and it looks great. Might want to add more prescaling options for people with 2k, 4k, and 8k screens though, since 4x seems to cut it pretty close to 1080p and I'm sure downscaling is better than upscaling.

**Comment by SourMesen** [comment]
Thanks for the suggestion - I added 6x, 8x and 10x prescale filters (87dc9ce0ffcbcc5b7352fc8c99a8ddf7bd838ff6), which should be enough for now.  I'll probably change this to be more flexible at some point in the future.
