### ISSUE TITLE
Support Sharp's Twin Famicom BIOS (Enhancement Request for FDS Mode)

### ISSUE THREAD

**Issue by wildgoosespeeder** [SourMesen/Mesen#122]
I ran some tests and Mesen doesn't like Sharp's Twin Famicom BIOS file but it is OK with Nintendo's. Both versions of this BIOS do work in FCEUX and puNES. This isn't an unlicensed hardware clone like the FC Twin or something. This is official hardware made by Sharp Corporation licensed by Nintendo. The BIOS files are different in one way and that is Nintendo's displays _Nintendo_ while Sharp's Display's _Famicom_.

More info:
https://www.youtube.com/watch?v=YFXlL-7uyQs

If you need the two BIOS files, let me know.
![nintendo](https://cloud.githubusercontent.com/assets/18543809/24184759/8a27dcc8-0e9d-11e7-8dcc-00bf3115bc00.png)
![sharp](https://cloud.githubusercontent.com/assets/18543809/24184758/8a264048-0e9d-11e7-8e9c-929f1e21234e.png)

**Comment by SourMesen** [comment]
Thanks for the report!
I didn't even know this BIOS existed - there is a hash check to ensure a valid BIOS file is used, and it only accepted the original FDS' bios. I've added support for the sharp bios too (5b17f25f708dd40999e10737c48eb1d594d72aea).

There is no built-in way of changing the BIOS after selecting it once, though - if you want to change it in Mesen, you can open up Mesen's folder (via the Options->Preferences->"Open Mesen folder" button) and delete the FdsBios.bin file you will find there.  This will make Mesen ask you for the BIOS file again the next time you try to open a FDS game.

**Comment by wildgoosespeeder** [comment]
Very nice. Thanks for fixing for future releases of Mesen!
