### ISSUE TITLE
Some Unlicensed game are not working

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#126]
I tried my collection of (Unl) games and I noticed some of them do not work. Some open, other have a weird looking. They are:

Fan Kong Jing Ying (China) (Unl) - Works in Punes and FCEUX
Mahjong Samit - Kabukicho Hen (Japan) (Unl)
Korean Igo (Korea) (Unl)
Pegasus 5 in 1 (Unknown) (Unl) - Works in Punes and Nestopia UE
Final Combat (Asia) (NTSC) (Unl)
Gaiapolis (Asia) (Unl)
Jurassic Boy (Asia) (Unl)
Mahjong World, The - Ma Que Shi Jie (Asia) (NTSC) (Unl) - Works in Punes
Popo Team (Asia) (Unl)
Pyramid II (Asia) (PAL) (Unl)
Rockball (Asia) (Unl)
Silver Eagle (Asia) (PAL) (Unl)
Street Heroes (Asia) (Unl) - Works in Bizhawk (NesHawk core)
Super Cartridge Ver 2 - 10 in 1 (Asia) (Unl)
Super Cartridge Ver 3 - 8 in 1 (Asia) (Unl)
Super Cartridge Ver 9 - 3 in 1 (Asia) (Unl)
Super Pang II (Asia) (Unl)
King Neptune's Adventure (USA) (Unl) - Works in Punes, Nestopia UE, and Bizhawk
Racermate Challenge II (USA) (v9.03.128) (Unl) - Do not glitches in Bizhawk

They are no-intro roms, so as you can see, some games tagged with (Asia) and (unknown), are also tagged with (Pal) and (NTSC). What about if you use the tags in rom's file name to make the detection correct?

**Comment by PinkLouie** [comment]
Do I need to send you the roms?

**Comment by PinkLouie** [comment]
Free Fall (USA) (Proto) do not work as well.

**Comment by PinkLouie** [comment]
Curiously the beta version of King Neptune's Adventure, works in Mesen, but the final version, don't.

**Comment by PinkLouie** [comment]
I discovered that some no-intro roms are .pas files. I think they are headless roms. You added support for headless files in version 0.8.0, so, shouldn't add support for .pas files as well? The files are:

Block Out (USA) (Proto).pas
Dragon Ball 3 - Gokuu Den (Japan) (Rev 1).pas
Game Master Kid (Unknown) (Proto) (RAM) (Unl).pas
Game Master Kid (Unknown) (Proto) (Unl).pas
Hard Drivin' (USA) (Proto) (Unl).pas
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console).pas

Just 6 games. What about add them in mesen internal database?

**Comment by PinkLouie** [comment]
I discovered that some no-intro roms are .pas files. I think they are headless roms. You added support for headless files in version 0.8.0, so, shouldn't add support for .pas files as well? The files are:

Block Out (USA) (Proto).pas
Dragon Ball 3 - Gokuu Den (Japan) (Rev 1).pas
Game Master Kid (Unknown) (Proto) (RAM) (Unl).pas
Game Master Kid (Unknown) (Proto) (Unl).pas
Hard Drivin' (USA) (Proto) (Unl).pas
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console).pas

Just 6 games. What about add them in mesen internal database?

**Comment by SourMesen** [comment]
Some of these look like they are caused by incorrect headers.
Spending time to fix these means I cannot work on more useful features - so I can't start testing and fixing every single unlicensed game (there is no end to them).  I will take a look eventually, but it might be a while.

It looks like ".pas" files are a unique format used by the Pasofami emulator - I don't plan on adding support for these.

**Comment by PinkLouie** [comment]
From no-intro, problematic roms are 20. I think they came from Famiclones. I even played some in the old times.

**Comment by SourMesen** [comment]
I've created #128 to keep track of all problems related to unlicensed games in the same GitHub issue.
If you find any more problems with unlicensed games, please post a comment in that issue and I'll add it to the list.
Thanks for reporting these!

**Comment by PinkLouie** [comment]
Super Mario Bros from Virtual Console is a .pas file and mesen can open it.

**Comment by SourMesen** [comment]
Mesen will try to open any file extension and match their contents against the CRC values in the game database.
The .pas file you tried to open probably matched the CRC values for the regular SMB game, which is why it loaded properly.
