### ISSUE TITLE
High CPU Use when going to full screen

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#129]
At random when going to full screen the CPU Spikes to 99% for a few seconds and starts to stutter for 3 or 4 seconds sometimes longer.

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz	36 °C
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)	35 °C
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)	45 °C
	ForceWare version: 365.10
	SLI Disabled
Storage
	931GB TOSHIBA DT01ACA100 (SATA)	33 °C
Optical Drives
	HL-DT-ST DVDRAM GH24NSC0
Audio
	Realtek High Definition Audio

**Comment by SourMesen** [comment]
Thanks for the specs - if I had to guess, it might be due to your CPU being a dual-core CPU.
Mesen uses spin locks to synchronize threads, but spin locks on single or dual core CPUs are not that great in some situations (when there are no free CPU cores) and might cause high CPU usage instead.

**Comment by Cibomatto2002** [comment]
Is spin locks kinda like Triple Buffing? Do I need to Close this?

**Comment by SourMesen** [comment]
No - it doesn't have anything to do with triple buffering.
I might try to replace the spinlocks with an alternative on single/dual-core CPUs in the future, which might fix this (hard to say).  It's something I've been meaning to do for a while, but it's a low priority.
I'll close this for now - if I ever make a change that might fix this on your computer, I'll comment on this issue to let you know.

**Comment by Cibomatto2002** [comment]
That's OK I know you have a life outside of Mesen I can live with it. Emulators that are worked on today what would be the best cores to get? is 6 Cores good for emulation or do I need something like Core i7? Back when I got my first computer is was a single core 1.8 now days I have really no idea what to get the computer I have now works really good on Dolphin Emulator and the PCSX2.

**Comment by SourMesen** [comment]
Core i7s only have 4 real cores + hyperthreading.  Hyperthreading is mostly useless when it comes to emulation.
For emulation, I would tend to believer an overclocked 4-core i5 is probably the best all-around CPU? The new AMD Ryzen CPUs may be worth a look from a price/performance ratio, too.
But I'm no expert - my current CPU (an i5) is over 7 years old and I haven't really been using it for emulation/gaming all that much.
