### ISSUE TITLE
Issues with non-XInput gamepads

### ISSUE THREAD

**Issue by davidj1987** [SourMesen/Mesen#130]
Hey, I'm trying to use the iBuffalo SFC USB Controller (Super Famicom looking controler for the PC) and the Retrolink Sega Saturn style controller and in Mesen and I'm having issues. With the iBuffalo controller When I press the B button, both A and B will be pressed. As for the Retrolink controller if I press Start both start and select are pressed.

However if I setup the Retrolink controller and then setup iBuffalo controller as player 1, everything works fine.

**Comment by SourMesen** [comment]
My first guess would be that you have the buttons mapped multiple times.
It's not excessively obvious in the UI, but each NES controller gets 4 sets of key bindings - so you can bind a keyboard & a gamepad to the same player, for example.
By default, Mesen fills up the first 3 tabs: Tab 1 is keyboard, 2 is XInput, 3 is DirectInput.
If you redid the bindings for the 1st tab, without clearing the bindings for the 3rd tab, you probably have the same physical buttons bound to multiple NES buttons.

A few people have had similar issues in the past, and this always ended up being the reason.
I really need to get around to displaying a warning somewhere when this happens.

**Comment by davidj1987** [comment]
That was it! Thank you!
