### ISSUE TITLE
(linux)compile issues - 

### ISSUE THREAD

**Issue by retro-wertz** [SourMesen/Mesen#131]
seems like a small typo.

current commit : https://github.com/SourMesen/Mesen/tree/2de4a39766b1cc8ea3f2a01d4810f5a37d2e8244

In file included from ../UpsPatcher.cpp:4:
../UpsPatcher.h:8:30: error: extra qualification on member 'ReadBase128Number'
        static uint64_t UpsPatcher::ReadBase128Number(ifstream &file);
                        ~~~~~~~~~~~~^
In file included from ../UpsPatcher.cpp:4:
../UpsPatcher.h:8:30: error: extra qualification on member 'ReadBase128Number'
        static uint64_t UpsPatcher::ReadBase128Number(ifstream &file);
                        ~~~~~~~~~~~~^

**Comment by SourMesen** [comment]
Thanks for the report!

I usually only compile the linux version once per release, so it's possible something breaks in-between releases. This should be fixed (c9a5e4e2fb1cb8a5be0dd108457cfbadb3f67003)
