### ISSUE TITLE
Aladdin (Mapper 4) last level issue

### ISSUE THREAD

**Issue by RetroBladen** [SourMesen/Mesen#132]
No lava in last level, rom file is _Aladdin (SuperGame) (Mapper 4) [!]_

![aladdin supergame mapper 4 _000](https://cloud.githubusercontent.com/assets/27443801/25024013/edb7ba42-20a4-11e7-8515-b778f279d0e8.png)

**Comment by SourMesen** [comment]
Thanks for the report!
I've added it to the list of problematic unlicensed games in #128
