### ISSUE TITLE
Add support for "Wo Xiang Niao Niao"

### ISSUE THREAD

**Issue by RetrogradeTom** [SourMesen/Mesen#134]
This is new homebrew game. It works in Mesen, but emulator says that this game using **Mapper: 0**

http://www.mojontwins.com/juegos_mojonos/wo-xiang-niao-niao/

"------------------------------------------------------
Loading rom: mojon-twins--wo-xiang-niao-niao--v1.3e.nes
File CRC32: 0x7063779C
PRG+CHR CRC32: 0x97116D42
[iNes] Mapper: 0 Sub:0
[iNes] PRG ROM: 32 KB
[iNes] CHR ROM: 8 KB
[iNes] Mirroring: Vertical
[iNes] Battery: No
------------------------------------------------------
[DB] Initialized - 3010 games in DB
[DB] Game not found in database"

**Comment by SourMesen** [comment]
As far as I can tell, the game works fine - and having 32kb of PRG and 8kb of CHR usually means the game really is a mapper 0 game.
Mapper 0 isn't an invalid value - it's the mapper number used to represent the most simple cart format the NES supports.

**Comment by RetrogradeTom** [comment]
So it will work, despite on this message and that this game not found in database? :)

**Comment by SourMesen** [comment]
Yes, the database is only used to fix issues when rom files contain invalid information - for most roms, it isn't needed at all and the games will work fine even if they are not found in the database.
