### ISSUE TITLE
Mapper 116 support

### ISSUE THREAD

**Issue by RetrogradeTom** [SourMesen/Mesen#135]
https://wiki.nesdev.com/w/index.php/INES_Mapper_116

This mapper needs for some unl and pirate games.

Some games, what are using it: AV Mei Shao Nv Zhan Shi ; Somari ; Samurai Spirits ; Contra Fighter

**Comment by SourMesen** [comment]
Thanks - I just created a more general issue containing all mappers that are currently not supported by Mesen (including mapper 116).
Take a look at #136 for more details
