### ISSUE TITLE
Retroarch support {Future release}

### ISSUE THREAD

**Issue by alex-lkdl** [SourMesen/Mesen#144]
Hi.
Is it possible,in the future,to see support for Retroarch(Mesen as core)?
It would be great,most of the time I play with rpi3.
Also,do you plan to integrate http://retroachievements.org support?

**Comment by SourMesen** [comment]
Hey,
A libretro port is listed in the roadmap on the GitHub main page - I don't have any estimated timeline as to when one might happen.

As for retroachievements.org, I wasn't aware of its existence, but if I understand correctly, they seem to have modified existing emulators to make them interact with their servers, so there isn't really anything I can do on my end to add support for this.

Hope that helps,
