### ISSUE TITLE
0.8.1 - Mesen does not accept input on FDS game 

### ISSUE THREAD

**Issue by jasonridesabike** [SourMesen/Mesen#146]
Can't seem to get Mesen to accept keyboard or Xbox One controller input for the FDS version of Zelda. May affect other games, haven't tested. Tried manually setting the console type to Famicon, no go.

**Comment by SourMesen** [comment]
Have you tried non-FDS games?
Are you able to setup the key bindings properly in the UI?
There's no real reason that I can think of that FDS games specifically would refuse to work, but then again, someone else made (and closed) a similar report a few days ago, so there might be something going on with it.

**Comment by jasonridesabike** [comment]
Hi yes, should have been more explicit. Tried a handful of NES games, no problem with either form of input.
Key bindings set fine in all cases and I also attempted to use the builtin xinput profile and setting alternate inputs. 
Also turned on input reporting (not sure if that's what it's called, away from gaming computer), nothing printed.

Let me know if you'd like for me to test something specific.

**Comment by SourMesen** [comment]
I still haven't had the chance to take a look at this, but could you attach your settings.xml file here?  It should be in Documents\Mesen\settings.xml - with a bit of luck, maybe it'll allow me to reproduce the issue on my end.

If you could try any other FDS game to be sure it affects all of them, that'd be great.
Also, the Zelda ROM's CRC value would be good to know too - you can find it in Tools->Log Window after loading the ROM.

**Comment by jasonridesabike** [comment]
@SourMesen So this is a non-issue. Apparently, it's common of FDS games to boot from one side and then flip the disk once at the title screen to actually start the game; I just had to flip the disk.

I'll bet a number of non-Japanese speaking people will run into this same issue, might be worth mentioning on the website.

**Comment by SourMesen** [comment]
Ah, thanks for letting me know.
A lot of games display a black screen asking to change the disk, but Zelda in particular is less obvious (esp. if you don't know Japanese).
If you look at the bottom, there's a message that starts with "Bメン" at the bottom of the screen - that's the Japanese for "B Side".  It might also be written as "Bめん" in some games.
