### ISSUE TITLE
Widow mode enhancement

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#147]
Sometimes i play my games in a window so I can change my music when playing games could we see something like this one day? This would give me more screen to.
![1](https://cloud.githubusercontent.com/assets/21169038/25301448/047bcd38-26ed-11e7-918d-fc1c266cfd04.jpg)

**Comment by SourMesen** [comment]
As far as I know, it's not possible to do this without custom drawing the window, which is a lot of work and would be prone to causing issues (e.g it would need to be thoroughly tested on each version of windows, etc.).  I think a good middle grounds would be a simple way to toggle the menu on/off, which is the first item in #142

**Comment by Cibomatto2002** [comment]
A toggle for the menu screen would fix my problem to the computer going to 99%.

**Comment by SourMesen** [comment]
I added an option to make the menu auto-hide in windowed mode, like it does in fullscreen mode (c9c7c626efeea77e5503e3e6fc8c1717ca1939e6)

**Comment by Cibomatto2002** [comment]
Thanks A lot :) Now I will just play it in window mode.
