### ISSUE TITLE
Zelda II - The Adventure of Link (USA) [bug maybe].

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#148]
I can't remember if this happen on the real NES so I sent it to you anyways on the top on the screen it jumps. Here is a video and a savestates. 
[Zelda II - The Adventure of Link (USA)_1.zip](https://github.com/SourMesen/Mesen/files/960726/Zelda.II.-.The.Adventure.of.Link.USA._1.zip)

https://sendvid.com/34zuefcm

**Comment by SourMesen** [comment]
This is almost certainly a bug in the game itself.  Using the overclocking features in Mesen (additional scanlines before NMI), you can make the issue go away.   Also, turning on the "Lag Counter" shows that the game is getting some lag frames at the same time as the status bar is jumping.

**Comment by Cibomatto2002** [comment]
I was not sure if it was a timing bug or not.
