### ISSUE TITLE
палитра

### ISSUE THREAD

**Issue by paul93p** [SourMesen/Mesen#153]
здраствуйте! можно ли сделать хорошую палитру цветов, как на приставке точную копию один в один please

**Comment by SourMesen** [comment]
Sorry, I don't speak Russian!
If you are trying to change the palette, you can do that in Options -> Video -> Palette.
You can change each color individually, or select a preset with the "Load Preset Palette" button.
Hope that helps!

-----
Google translate:
Извините, я не говорю по-русски!
Если вы пытаетесь изменить палитру, вы можете сделать это в Настройках -> Видео -> Палитра.
Вы можете изменить каждый цвет по отдельности или выбрать пресет с помощью кнопки «Загрузить настроенную палитру».
Надеюсь, это поможет!
