### ISSUE TITLE
[Ubuntu 16.04] Build fails

### ISSUE THREAD

**Issue by iarspider** [SourMesen/Mesen#155]
With a few fixes here and there I got to xbuild invocation stage, and got this error:
```
cd UpdateHelper && xbuild /property:Configuration="Release" /property:Platform="AnyCPU" /target:build
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 5/4/2017 9:46:45 PM.
__________________________________________________
Project ".../Mesen/UpdateHelper/UpdateHelper.csproj" (build target(s)):
.../Mesen/UpdateHelper/UpdateHelper.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '4.0' instead.
        Target PrepareForBuild:
                Configuration: Release Platform: AnyCPU
        Target GenerateSatelliteAssemblies:
        No input files were specified for target GenerateSatelliteAssemblies, skipping.
        Target GenerateTargetFrameworkMonikerAttribute:
        Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
Done building project ".../Mesen/UpdateHelper/UpdateHelper.csproj".-- FAILED

Build FAILED.

Warnings:

.../Mesen/UpdateHelper/UpdateHelper.csproj (build) ->

        ...Mesen/UpdateHelper/UpdateHelper.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '4.0' instead.

         1 Warning(s)
         0 Error(s)

Time Elapsed 00:00:00.2370120
makefile:42: recipe for target 'ui' failed
make: *** [ui] Error 1
```

More verbose log: https://gist.github.com/iarspider/cbab7fa3a33c8b56c57e7843b9cb34ff

**Comment by SourMesen** [comment]
Thanks - I'll try to take a look at your pull request and this tonight.
I always develop on Windows and check the Linux build whenever I release a new version, so the Linux build can sometimes break in-between releases.  I build/develop the linux port on a Ubuntu 16.04 VM, though, so you shouldn't have any problem once the fixes are done.

**Comment by SourMesen** [comment]
I fixed the build errors and most clang warnings (gcc still outputs some though) in 25019f052c5beba2309b70267e0c2a7281a6e6f1.  Thanks for letting me know about them.

I'm not seeing the problem you're getting with the xbuild part though.
From your log, it looks like this part is where it fails:

```
Task "Csc"
Using task Csc from Microsoft.Build.Tasks.Csc, Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Task "Csc" execution -- FAILED
```

Unfortunately, it doesn't give any clue as to why it's failing.
The UpdateHelper project is a tiny project with a single file and almost no code - my guess at the moment is that there may be something wrong with your environment that's causing XBuild to fail (but I don't really know what it could be).

This is what I get when building, so it looks like we're using the same XBuild & Mono versions:
```
cd UpdateHelper && xbuild /property:Configuration="Release" /property:Platform="AnyCPU"
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors

Build started 5/4/2017 11:37:32 PM.
__________________________________________________
Project "/home/saitoh/MesenCode/UpdateHelper/UpdateHelper.csproj" (default target(s)):
/home/saitoh/MesenCode/UpdateHelper/UpdateHelper.csproj:  warning : Project has unknown ToolsVersion '14.0'. Using the default tools version '4.0' instead.
	Target PrepareForBuild:
		Configuration: Release Platform: AnyCPU
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	Target GenerateTargetFrameworkMonikerAttribute:
	Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
	Target CoreCompile:
	Skipping target "CoreCompile" because its outputs are up-to-date.
Done building project "/home/saitoh/MesenCode/UpdateHelper/UpdateHelper.csproj".

Build succeeded.
```

**Comment by iarspider** [comment]
Looks like I was missing `mono-mcs` package. Can you add a list of dependencies to the README?

**Comment by SourMesen** [comment]
Thanks for letting me know!
I updated the readme to add some more info (56656aa0a4475701f0a80801b901657561203853) - I'm guessing you hadn't installed the mono-devel package directly?  That would explain why you didn't have the mono-mcs package installed.

Let me know if you have any other issues.
