### ISSUE TITLE
Feature Request: Automatic FDS Disk Side Swap

### ISSUE THREAD

**Issue by synnae** [SourMesen/Mesen#156]
I know there's a "FDS - Switch Side" shortcut key, but I was wondering if an optional automatic swap feature could be added. Basically, the emulator would automatically swap disk sides whenever the game asks for it.

There's a NES Flashcart that can do it (EverDrive-N8 Deluxe Edition): 
http://www.stoneagegamer.com/everdrive-n8-deluxe-nes.html

Just a suggestion to make the swapping process even more convenient.

**Comment by SourMesen** [comment]
Thanks for the suggestion!
I've added an option in the preferences window for this (ce62e40d475fd4a4634f24584dfea179481c123e).
I tested it with a decent amount of games and it seems to be working well.
Let me know if you find any issues with it in the next release.
