### ISSUE TITLE
Feature Request: Add option to show timer for every game

### ISSUE THREAD

**Issue by DocMoreau** [SourMesen/Mesen#159]
This is let user (-s) to choose on/off timer, which will showing how much time you playing game in format Hours:Minutes:Seconds (example 00:10:00). And also add timer functions, such as pause timer when game paused, reset timer if game changed and reset timer on Power Cycle.

**Comment by SourMesen** [comment]
Thanks for the request!
I've added a game timer option (Preferences->Advanced), which displays the amount of time that has passed since the last reset/power on (7d1fa8aaaf73c82acb8614a880b84b3fce58fefe)
