### ISSUE TITLE
звук 

### ISSUE THREAD

**Issue by paul93p** [SourMesen/Mesen#160]
после вашего обновления у меня перестал работать режим денди, вернее он работает но заикается звук, исправте пожалуйста

**Comment by SourMesen** [comment]
Thanks for letting me know!
I've fixed this (27dbf34940ce32410e124d55068698416203ace4) and reuploaded a new version of 0.9.0 on the website.  If you [redownload Mesen](https://www.mesen.ca/download.php) from the website, the problem should be fixed.

Google Translate:
Спасибо, что дали мне знать!
Я исправил это (27dbf34940ce32410e124d55068698416203ace4) и перезаписал новую версию 0.9.0 на веб-сайте. Если вы [повторно загрузите Mesen] (https://www.mesen.ca/download.php) с веб-сайта, проблема должна быть исправлена.
