### ISSUE TITLE
многоигровки

### ISSUE THREAD

**Issue by huroxe** [SourMesen/Mesen#161]
когда ваш эмулятор сможет открывать все ромы многоигровки? (goodnes multicarts collection)

**Comment by SourMesen** [comment]
Support for multicarts is not a very high priority but I try to improve support for them once in a while (see #128 for all unlicensed/multicart issues). I doubt there will ever be a day where Mesen supports all multicarts, there are simply too many of them, using too many different board types.

Google Translate:
Поддержка мультикартов - не очень высокий приоритет, но я стараюсь время от времени улучшать их поддержку (см. #128 для всех вопросов, связанных с нелицензированными / многопользовательскими). Я сомневаюсь, что когда-нибудь будет день, когда Mesen поддерживает все мультикарты, их просто слишком много, используя слишком много разных типов плат.
