### ISSUE TITLE
Issue with Game Genie cheat code?

### ISSUE THREAD

**Issue by omcnoe** [SourMesen/Mesen#165]
LAXAALAE

I ran into problems using this code in Battletoads, it should cause the game to start at a level 11. In FCEUX using the code correctly skips me to level 11, but in Mesen it starts at 7 instead.

So it seems like there is an issue in how Mesen is handling Game Genie codes?

**Comment by SourMesen** [comment]
Thanks for the report!
It was caused by a small bug in the logic to decode 8-character game genie codes (ada46d8428b6095183c25a321b514d10708670fc)
It will be fixed in the next release.
