### ISSUE TITLE
Screen flashing while setting scale value.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#166]
It happens after you set a new value for scale in Video Option, and before you press ok. It is very bad. It can cause headaches.

[Mesen - Zatsugaku Olympic Quiz Part II (Japan) (Unl) 18_05_2017 01_16_06.zip](https://github.com/SourMesen/Mesen/files/1009742/Mesen.-.Zatsugaku.Olympic.Quiz.Part.II.Japan.Unl.18_05_2017.01_16_06.zip)

**Comment by SourMesen** [comment]
Thanks for the report.
Should be fixed by f573009acaf357d8f51ae048999c43882649599e
