### ISSUE TITLE
Video Recorder improvements?

### ISSUE THREAD

**Issue by RetroGameIntros** [SourMesen/Mesen#175]
Add support for "CamStudio Loseless Codec v1.5" (nice quality for recording) and "Reference frame" (this one was in nestopia)

**Comment by SourMesen** [comment]
Thanks for the suggestions.

The "Camstudio (CSCD)" codec option in Mesen is the same as "Camstudio Lossless Codec v1.5", as far as I am aware of (all codec options in Mesen are lossless)

For "reference frame" I'm guessing you mean "key frames"?  The key frames in the AVIs are every 120 frames (2 seconds), which is a good balance between being able to seek properly in the video & not making the file too large - if someone really needs more or less key frames for some reason, they can re-encode the video using FFMPEG or other tools easily enough.
