### ISSUE TITLE
B/A input not working

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#176]
In Hyper Olympic (Japan) (Genteiban!) and Hyper Olympic (Japan), I can't make the athlete run. He should run when A is pressed a lot of times. Nothing Happens. Runs fine in other emulators.

**Comment by SourMesen** [comment]
Thanks for the report.
This is normal - the games Hyper Olympic and Hyper Sports both require the "Konami Hyper Shot" controller, which isn't supported yet.  Adding support for the less common input devices is on my list of things to do.

**Comment by PinkLouie** [comment]
I used to play this game in famiclones, with their "normal" controllers. I will wait for the for the support unhurried.

**Comment by SourMesen** [comment]
I checked the game's code, and it's only checking the Start & Select buttons from the controller - everything else is being read from the Konami Hyper Shot's input port, so a standard controller shouldn't work.
