### ISSUE TITLE
Some problems with japanese games

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#178]
Some japanese famicom games do not work in Mesen (yet, I hope), and they are the followings:

Galaxian (Japan) -  Green Screen
Galaxian (Japan) (Rev A) - Green Screen
Minna no Taabou no Nakayoshi Daisakusen (Japan) - Green Screen
Mississippi Satsujin Jiken (Japan) (Rev A) - The screen flashes and the game does not work
Money Game, The (Japan) - Black Screen
Nantettatte!! Baseball + Nantettatte!! Baseball - Ko-Game Cassette - '91 Kaimaku Hen (Japan) - Green Screen
Nantettatte!! Baseball + Nantettatte!! Baseball - Ko-Game Cassette - OB All Star Hen (Japan) - Green Screen
Tatakae!! Rahmen Man - Sakuretsu Choujin 102 Gei (Japan) - Black Screen with sound of old TVs with no signal.
Mighty Bomb Jack (Japan) - Green Screen
Dragon Ball 3 - Gokuu Den (Japan) (Rev 1) - Gray Screen
Super Mario Bros. 25 Shuunen Version (Japan) (En) (Promo, Virtual Console) - Can't load.

Most of them run in other emulators.

Also, noticed another bug. Mesen loses the actual game's name in titlebar if a new game fails to load. The name should remain, after all, no new game is running, and the old one is still running. You can see it in the screenshot:

![2017-05-25](https://cloud.githubusercontent.com/assets/24971871/26444059/31ce25ae-4111-11e7-9bf5-dd9895e238b8.png)

**Comment by SourMesen** [comment]
**Minna no Taabou** is a known bug in the game's code - it won't boot when the ram initialization setting is set to all 0s
The **Nantettatte!! Baseball** ones are extra cartridges that you plug into the original game's cartridge - I don't think any emulator can run these.

Everything else should be fixed by 8032407f2803c393d84c5d7fe5dd84adb6dd1276

**Comment by PinkLouie** [comment]
Minna no Taabou works in NesHawk, so shouldn't run in mesen too?

**Comment by SourMesen** [comment]
NesHawk initializes RAM with 1s by default.
If you set Mesen to initialize ram to 1s (Emulation Settings -> Advanced), it will boot the game just like NesHawk.
