### ISSUE TITLE
Problems with Xexyz & Ninja Gaiden 1 (Dendy)

### ISSUE THREAD

**Issue by paul93p** [SourMesen/Mesen#180]
игра Xexyz (U) [!] зависает на уровне 11-1 и 12-4, NINJA GAIDEN 1 НЕЛЬЗЯ СМОТРЕТЬ КАТ-СЦЕНЫ, СБРАСЫВАЕТ ИГРУ ЛИБО ГЛЮЧИТ НА РЕЖИМЕ ДЕНДИ

**Comment by Koh1fds** [comment]
This is normal behavior
https://www.youtube.com/watch?v=kvXxS3LIPiA

**Comment by SourMesen** [comment]
Thanks for letting me know that this is normal - saved me a lot of time!

**Comment by paul93p** [comment]
ниндзя гайден на режиме денди так и должен сбрасывать игру, при просмотре катсцен на famiclone pal

**Comment by paul93p** [comment]
еще в настройках видео где можно выбрать палитру самое подходящая  nes classic ( by firebrandx) можно ли как нибудь сделать цвета по насыщней как по умолчанию сам пробывал настраивать все не то

**Comment by SourMesen** [comment]
You can click on any color block in the "Palette" tab (on the left side) to change its color.
