### ISSUE TITLE
Trying to play a new game.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#183]
If you click Automatically hide menu bar then reopen Mesen there is no way to open a new game without playing the last game saved. 
![capture1-11-2017-2 06 54 am5-28-2017-2 32 38 am](https://cloud.githubusercontent.com/assets/21169038/26526893/0c936558-434e-11e7-929e-1f3c979c3058.jpg)

**Comment by SourMesen** [comment]
Thanks - this is fixed by 735c3e583b6fc7f355d6d32182c4a31d6ba27a32.
As a workaround, you can also make the menu bar appear by pressing alt to activate it (like in any other Windows application)
