### ISSUE TITLE
Automatically switch aspect ratio when a Pal game is loaded.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#185]
NTSC and Pal formats have different aspect ratio and resolution right? So, I think, Mesen should have a check box to change the AR automatically when a Pal game is loaded. I use NTSC AR, and the configuration is retained when a Pal game is loaded. Another option, is to have separated AR option for Pal and NTSC (Dendy too?). The auto option do not do this, it just makes every games with a pixel aspect ratio of 1:1, I even thin it should have another have, like "Perfect Pixel" ou something like. If you rename it, you will have space for a new "auto" option, I described above.

Just one more suggestion. When a headerless rom fail to load because mesen doesn't have it in its DB, instead of a "mesen has crashed", a message like "No header found" would be more specific, and probably better.

Thank you.

**Comment by SourMesen** [comment]
Yes, having an "Auto" option that switches between NTSC & PAL based on the game and a "Pixel Perfect / No Stretching" option as the default would probably be best.
I'd rather not add separate NTSC/PAL settings - it would potentially add tons of settings, and most users are probably unlikely to use both.

Headerless roms should not display a "CPU crashed" message.  They should display "Could not load file" message and write this to the log window:
>Loading rom: \<file name>
File CRC32: \<file crc>
Invalid rom file.

If you are getting "CPU crashed" messages, then your ROMs do have a header (be it iNES or UNIF) but the header or ROM is most likely incorrect, which is causing the crash.  The NoIntro set in particular appears to have a large amount of roms marked as mapper 0 even though they are not.

**Comment by PinkLouie** [comment]
A message about headerless rom would be nice, instead of green, or grey, or black screen,  or everything that happens when no header is found. I have no idea of what each screen color means.

**Comment by SourMesen** [comment]
Like I just said - a headerless rom will not start the emulator at all if it is not in the game database.
If the emulation starts and stops, then your rom has a header, or it was found inside the game database.

**Comment by SourMesen** [comment]
I added a new aspect ratio option that automatically switches between NTSC & PAL aspect ratios based on the selected region/game (26ec5b808e277dd687cca9d1deab5557a5f3df7d)
