### ISSUE TITLE
Ninja Gaidel [level 4-4]

### ISSUE THREAD

**Issue by DiZLike** [SourMesen/Mesen#187]
Bug at the death of the double
https://cloud.mail.ru/public/LuEF/CZCmbHGN3

**Comment by SourMesen** [comment]
Are you referring to the fact there are 3 monsters?
As far as I can tell, this seems to be "normal" (probably a bug in the game itself):

From : https://www.reddit.com/r/nes/comments/3xnez2/i_encountered_a_bizarre_glitch_while_playing/cy80ocz/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=nes
>I would say that about 1/10 games, when the boss on the right is killed this way, 2 more will spawn giving you a total of 3 to deal with.

From : https://www.gamefaqs.com/boards/587488-ninja-gaiden/69451951
>I have a vague memory of having another statue spawn,

>Yeah, there can be three Kelbeross' at once. I have no idea what triggers it, though.

**Comment by SourMesen** [comment]
Closing since it doesn't look like this is a bug.
