### ISSUE TITLE
Cursor not hidden automatically on full screen if it isn't over the game frame

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#189]
If you launch Mesen on full screen with the command line, or use the full screen shortcut, the cursor is automatically hidden after a few seconds if it's placed over the game frame, like in the windowed mode. However, the cursor isn't hidden if it's on the side of the screen.

Mesen 0.9.0
Windows 10

**Comment by SourMesen** [comment]
Thanks for the report - I had actually noticed this myself recently and it was on my list of things to get done.

Fixed by fcd09ebdd9df6f88149f277aa35f09fe3224f795
