### ISSUE TITLE
Use Player 1 input to browse the "Recent Game Selection"

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#190]
Currently you can only use the mouse to select the previous or next game, and <kbr>⏎</kbr> to start it, right? It'd be nice to be able to use the Player 1 controller buttons to do that.

Mesen 0.9.0
Windows 10

**Comment by SourMesen** [comment]
Thanks for the suggestion!
Player 1's bindings can now be used to navigate the recent game selection screen (147fcbfcf74d299eb48db102392bfb267c1b27d1)
Left/Right to change game, A or B to start it.
