### ISSUE TITLE
Dependencies to run Mesen on KDE Neon / Ubuntu

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#192]
I only managed to run Mesen on KDE Neon after installing these packages plus everything that comes with them: mono-complete gnome-themes-standard libsdl2-2.0 . Is this correct, or could I have used a slimmer Mono package? 

Also, the information to mark the file as an executable and use the `mono` command, and the list of dependencies, should be included on the frontpage for people who run versions of Debian/Ubuntu that don't come with them pre-installed.

**Comment by SourMesen** [comment]
I am not a Linux guru and do not use it much - so I am not quite certain what packages may or may not be required. It works on the Ubuntu 16 VM I use.  The minimum packages needed to build are listed in the readme - I have no tested to see the minimum packages required to simply run the application.
mono-devel should be sufficient - at the very least, I do not have mono-complete installed on my setup.
libsdl2-2.0 is a required dependencies - it is installed via libsdl2-dev when building from source.
As for gnome-themes-standard, I have no idea - I have never heard of it, and do not quite exactly know why it would be a requirement.

I've updated the readme file to add a few more details for Linux users (e.g list of known dependencies, basic information about mono), so hopefully that helps.

Mesen has not been tested on anything other than a very vanilla install of Ubuntu 16 (I do not have the time to debug or test other setups) - and if you are trying to use it on anything else, it may be simpler to build it from source.

**Comment by anewuser** [comment]
The matter is that the development tools have huge lists of dependencies, and it takes a little while to compile it - only to get the same binary you already provide. It's more practical and sensitive (especially for people with small SSDs) to install only the required packages to actually run the emulator. Let's say it's the three I mentioned then. 

>As for gnome-themes-standard, I have no idea - I have never heard of it, and do not quite exactly know why it would be a requirement.

I had to manually install `gnome-themes-standard` too because Mono kept throwing an error about the `adwaita` theme being missing. It provides the style (e.g. for the file dialog icons) that Mono uses by default. It's included by Gnome and Unity, but I use KDE.

Hopefully this list can help anyone interested in creating .deb packages.

**Comment by SourMesen** [comment]
Ah ok, that makes sense.  Since I don't actually ever use Linux outside of a VM context, I tend to see Linux as something that fits on a 20gb disk, forgetting that people that actually use it as their OS also have a ton of data installed on there :)  And I definitely know the pain of having a small SSD disk!

Seems odd that Mono isn't installing that package as a dependency if it actually requires it - the official releases' executable file is actually built in Visual Studio and not with Mono, so I'm assuming pretty much any WinForms app you'd run under Mono would need that package, too.

I updated the readme again and added a list of packages (the ones you listed) - hopefully that helps.

**Comment by anewuser** [comment]
Thank you for your replies and working on the issues I reported again.

It took Snes9x a long time to convince me to move way from ZSNES, but Mesen won me the first time I used it. :)

**Comment by SourMesen** [comment]
No problem, happy to hear you like it!
