### ISSUE TITLE
More Mesen optimizations / perfomance fixes

### ISSUE THREAD

**Issue by RetroGameIntros** [SourMesen/Mesen#193]
If compare with Nestopia, Mesen eating 45 Mb of RAM + 9-10% cpu, while nestopia took only 15-20 Mb and 5-6% cpu or less

**Comment by Cibomatto2002** [comment]
I don't see this as a problem. Why would 9-10% CPU make any differences to you?

**Comment by SourMesen** [comment]
Optimizing Mesen further than I already have would be excessively time consuming (and I have already spent literally dozens of hours doing this in recent months), and would not really help most people at this point - Mesen can already run games at full speed on 10-year-old computers.  Nestopia's speed often comes at the cost of its code being excessively hard to decipher - it's not a trade-off I am willing to make.

Memory usage is typically fairly low - it uses up about 35mb of ram in typical scenarios.  Mesen is a 64-bit process, so this inevitably causes higher memory usage compared to 32-bit processes (like Nestopia).  Still, we are at a point where most computers have 4gb of ram or more, so I don't really see the point in trying to reduce the memory footprint - using 35mb is low by today's standards.
