### ISSUE TITLE
SL:310 in tracelog

### ISSUE THREAD

**Issue by Eicar** [SourMesen/Mesen#197]
For some reason I see several SL:310 in my tracelogs. Like this:

E442  $C9 $07      CMP #$07                A:C9 X:05 Y:00 P:A5 SP:F3 CYC:334 SL:260 FC:36 CPU Cycle:1042198
E444  $B0 $FA      BCS $E440                A:C9 X:05 Y:00 P:A5 SP:F3 CYC:340 SL:310 FC:36 CPU Cycle:1042200
E440  $E9 $07      SBC #$07                  A:C9 X:05 Y:00 P:A5 SP:F3 CYC:  8 SL: -1 FC:36 CPU Cycle:1042203

Is this a bug?

**Comment by SourMesen** [comment]
Thanks for the report - it's a bug, you can assume that scanline 310 means 260.  If you run the game in NTSC instead of "Auto", the issue should go away on its own.  (and this is fixed by 97323f3eb0c53c6e9d5061c40977dc4e8d5e6100)
