### ISSUE TITLE
Input settings - conflicting key kindings v0.9.0

### ISSUE THREAD

**Issue by cacciatc** [SourMesen/Mesen#198]
When configuring my gamepad I am getting a warning (see screenshot below) which I cannot remedy.

![Input Settings](https://user-images.githubusercontent.com/149836/27876342-9781246c-616b-11e7-8bf2-e8c7fcfcda70.png)

## Steps to reproduce
1. Click Setup button for Player 1.
2. Click Clear Key Bindings.
3. Configure gamepad under Key Set 1 (with no conflicting keys as shown in screenshot).
4. Click OK on Standard Controller: Player 1 dialog.
5. Click OK on Input Settings dialog.

Now when I play the start button also triggers the A button. See the following:

![Input Example](https://user-images.githubusercontent.com/149836/27876555-6984691a-616c-11e7-94a5-94cad301cb36.gif)

**Comment by SourMesen** [comment]
Like it says in the input configuration: "Tabs with an icon contain key bindings for this player".
You have 3 tabs with an icon - you most likely have conflicting bindings between those 3 tabs.

**Comment by cacciatc** [comment]
Thanks. It makes sense now. I was confused since the default input config contains those warnings and I always ignored them.

**Comment by Cibomatto2002** [comment]
What game is this?

**Comment by cacciatc** [comment]
_Nebs & Debs_. It is a homebrew game I am working on. If interested you can see my progress at https://twitter.com/cacciatc

**Comment by Cibomatto2002** [comment]
Thanks. So far it looks good.

**Comment by SourMesen** [comment]
@cacciatc Thanks for mentioning that, I hadn't realized the default bindings had conflicts in them - I changed the P2 default keyboard bindings to prevent this in the future.
