### ISSUE TITLE
Feature request: Portable mode and turn off gameloaded text.

### ISSUE THREAD

**Issue by scottluker** [SourMesen/Mesen#201]
The reason why I want portable mode is to keep everything in one folder, as this is useful for Frontends and  being able to turn off "Game Loaded (NTSC) .... " text that appears when you load a game is for Frontends as well,  it's just unnecessary and a little distracting.

**Comment by SourMesen** [comment]
Thanks for the suggestions.

Portable mode is already available - just rename the exe file to Mesen_P.exe to make the emulator keep all of its file in a "Mesen" subfolder next to the executable file. I do want to make this more user friendly at some point, but for now it works.

I also added an option in Preferences->Advanced to disable the OSD (they'll be shown in the Log Window instead) (ca579b4c404c70b2d90fbf816d5e5caf20c017d2)

**Comment by scottluker** [comment]
ah awesome yeah that works for me, just wasn't clear. And thank you for implementing that change so quickly, very appreciated.

**Comment by SourMesen** [comment]
No problem, it was a pretty simple addition and the OSD can definitely be annoying in some cases, so it makes sense to have an option.
