### ISSUE TITLE
My Feedback on Mesen 

### ISSUE THREAD

**Issue by John-Enigma** [SourMesen/Mesen#202]
I started using the emulator, and now I'm going to make my feedback. 

First things first, if you want to know the specs of desktop, [here they are](https://www.cnet.com/products/gateway-sx2110g-uw24-e1-1500-1-48-ghz-6-gb-500-gb-led-19-5/specs/). I changed the OS to Windows 10, by the way. Also, **DISCLAIMER**: all of this is from my experiences.

So far, my times with Mesen have been bittersweet. Sometimes it works, sometimes it doesn't. 

1. In the past, whenever I started Mesen, it would crash before even starting. Before I even touched anything. As far as I know, emulators don't do that. Usually emulators would crash whenever a driver is missing, or whenever a bad ROM is loaded. 

One or two weeks ago, I reset my PC, but not because of this emulator. Eventually I wanted to try Mesen (v0.9.0) again to see how it would work on my PC. Miraculously, no crashes! Then I wanted to see the emulator for myself. 

2. It looks nice, I guess. It certainly has more features than FCEUX though. However, I'm gonna take a wild guess and say that most of these features are still unfinished, right? For example, where are the Directories/Paths section? Almost every known emulator, even FCEUX, have a Directories/Paths section. This one doesn't. Why? 

3. And of course, emulation. How can I forget that? I've tested some games to see how they would work. So far so good, the basic NES games (Super Mario Bros., 2, 3, Final Fantasy I-III) work, but apparently complex games (like Mystery World Dizzy, Magic Kid Googoo, Super Pitfall, and its prototype sequel), and bootleg games (like the Final Fantasy VII NES pirate, the Super Mario World NES port pirate, the Somari [and its many clones] bootleg, Rockman 6-in-1 bootleg multicart, etc.) are still unstable. This emulator boasts to have many supported Mappers, but from what I've seen here, it's still not done. Oh, and not many ROMs play at all, like the 25th Anniversary Edition of Super Mario Bros. And I think that Mesen hates NES romhacks. I've tested some romhacks, and they either crash the emulator, or freeze the game. 

Also, whenever I play this games as well, they would eventually turn out to be glitchy. And the basic ROMs that I have are No-Intro ROMs, which means that they are cleaned ROMs. However, I execute this ROMs in Mesen with my computer, and they are sometimes a minor glitchy mess. 

Another thing that bothers me, is that the FPS drops drastically whenever I do something with the emulator. If want to change a setting, lower the volume of my computer, or press Ctrl+O to change another ROM, the game's FPS drops dramatically to levels I have never seen before. I know that this is suppose to be normal, but as far as I know, if an emulator drops its framerate, it quickly returns to be 60 FPS. **IN HERE, NO!** You do something that is not playing in Mesen, the FPS drops and it stays there. You open something else, aside from the emulator, the FPS drops, and it stays there. In my honest opinion, even if I have a really bad PC, these FPS issues should be addressed, prioritized, and fixed. 

Since this is an emulator that focuses on accuracy, know this: I've tested mGBA (GBA/GBC/GB emulator) before, and after a few updates, it runs beautifully on my PC. And that's an emulator that focuses on both accuracy, and speed (even on PC's like mine). Something that you don't see that much on other emulators. I like to call it the @endrift philosophy. 

From what I remember, I never had these issues with FCEUX. The only reason I changed emulators, is because I wanted something new, and modern. (In certain parts, FCEUX is still archaic, takes a LONG time to be updated, and also, it's on Sourceforge.) 

So there. There's my feedback on Mesen. 

Thank you for taking the time to read this.

**Comment by SourMesen** [comment]
You are free to use any other emulator if you find they work better for you than Mesen - high accuracy comes at a price in terms of performance and I can't spend 95% of my time optimizing for the 5% slowest CPUs. Beyond that, most of the valid issues you brought up are already being discussed in other opened issues on GitHub.

While I normally appreciate feedback, there are ways to give feedback without sounding condescending and entitled. At the end of the day, Mesen is my personal hobby and completely free - please don't act like I owe you something.

**Comment by John-Enigma** [comment]
Sorry about that. 

And thanks for the reply.

**Comment by John-Enigma** [comment]
I still feel sorry about the comment that I made, @SourMesen .

I hope you can forgive me for what I said back then. 

Btw, your emulator runs great on my [PC.](https://www.cnet.com/products/gateway-sx2110g-uw24-sff-e1-1500-1-48-ghz-6-gb-500-gb-led-19-5/specs/)
