### ISSUE TITLE
A clearer message about update error.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#205]
Add a clear message, "You need an available internet connection to use this function".

![2017-07-31 1](https://user-images.githubusercontent.com/30609937/28804678-28eca474-763b-11e7-9178-1fd1de6ddd89.png)

Thank you!

**Comment by SourMesen** [comment]
I added "Check your internet connection and try again." to the message to imply it could be caused by a connectivity issue (d4499fcf8c7b8d3319ea72f1bc9009a46abc0342).  It's also possible this would appear due to other reasons though (e.g problems with the mesen.ca server, etc.)
