### ISSUE TITLE
Feature Request: Force integer scaling.

### ISSUE THREAD

**Issue by scottluker** [SourMesen/Mesen#207]
Have an option to force integer scaling when in fullscreen. For example rather than a 1080p monitor having a scaling of 4.5 it is restricted to 4.

**Comment by SourMesen** [comment]
Thanks for the suggestion - I've added this as an option in the video settings (4e7d05734a47f9f1bf2cb9dbcc9e354b5d010e5a)

**Comment by scottluker** [comment]
Appreciate the work :D
