### ISSUE TITLE
Strange rectangle when no game is loaded

### ISSUE THREAD

**Issue by ImJezze** [SourMesen/Mesen#208]
I just updated to version 0.9 and when no game was loaded before a small gray rectangle is flickering on the black screen, right below the Help menu entry.

I added a ZIP file containing a small MP4 video to demonstrate.

[mesen-strange-rectangle.zip](https://github.com/SourMesen/Mesen/files/1202973/mesen-strange-rectangle.zip)

I think this is the rectangle of the most recent played game, which for me wasn't there due to a clean install of Mesen.

This issue is very minor, but if you need any further information to reproduce it, let me know.

**Comment by SourMesen** [comment]
Thanks for the report!
This is something someone else reported a while back (can't seem to find a trace on GitHub though, may have been elsewhere), and as far as I know, it should already be fixed in the current code.  The next release should no longer have this issue.
