### ISSUE TITLE
Recording new HD packs with emulation paused 

### ISSUE THREAD

**Issue by PhoenixBound** [SourMesen/Mesen#209]
Starting a HD pack recording for the first time doesn't work when emulation is paused. Instead Mesen throws an exception over and over:

![image](https://user-images.githubusercontent.com/13182187/29055052-bd0956d2-7bbf-11e7-9783-ee352677351a.png)

Recording seems to work fine if emulation is unpaused or pack data already exists.

Tested on 0.9.1, but not tested on the latest commit.

**Comment by SourMesen** [comment]
Thanks for the report!
This should be fixed by f536f62dd14830adf836914c087fa343dc61d2ca
Let me know if you find anything else.
