### ISSUE TITLE
Strike Wolf (MGC-014) (Unl) zapper

### ISSUE THREAD

**Issue by dragon2snow** [SourMesen/Mesen#210]
Mesen zapper X not working?

**Comment by SourMesen** [comment]
The zapper seems to be working for me in that game - what's not working for you?
I tried both the Famicom & NES zappers, both seem to work.  The NES zapper needs to be plugged into the 2nd player port to work, though.

**Comment by dragon2snow** [comment]
thank you ,update version,ok
