### ISSUE TITLE
Background inputの日本語訳が逆no意味になっている

### ISSUE THREAD

**Issue by 2chsoft** [SourMesen/Mesen#216]
「Mesenが最面前ではない時、コントローラ反応しない」にチェックを入れると
Mesenがバックグラウンドの時、コントローラー入力を受け付けるようになる

**Comment by XXLuigiMario** [comment]
You could try fixing it yourself by creating a pull request, this is the file containing the japanese translation:
https://github.com/SourMesen/Mesen/blob/master/GUI.NET/Dependencies/resources.ja.xml

**Comment by SourMesen** [comment]
For some reason, these bugs were created yesterday and disappeared.  And now they've magically come back. They're all fixed already though :)
Fixed by 2a8ed7b744a1ce10b62dfa11b6a8373971d93bc0
