### ISSUE TITLE
lag issues

### ISSUE THREAD

**Issue by LotteBestGirl** [SourMesen/Mesen#224]
I tried to play the game "Hebereke" on Mesen but in 2 minutes after it beginned to lag a lot, how can i solve it?

**Comment by dragon2snow** [comment]
update hardware?

**Comment by XXLuigiMario** [comment]
@LotteBestGirl I cannot seem reproduce it on my end, but I did get was some minor slowdown, which should also happen on actual hardware.

**Comment by SourMesen** [comment]
It's hard to say without more details - if you are talking about in-game lag, that's normal and is pretty typical of NES games.
You might be able to use overclocking options to remove the in-game lag. Try increasing the "Additional scanlines before NMI" option to 400+ in the Options->Emulation->Overclocking options.
Beyond that, Mesen should run fine on most computers (unless you're running a really low-spec computer like a notebook).
