### ISSUE TITLE
HdPacks

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#225]
Where is a good place to find HdPacks? Also how to you load them I was working on one and i can't get it to load I made it with the HD pack builder. I wanted to test it out so i made mario blue but don't know how to load it.

**Comment by SourMesen** [comment]
There aren't really many HD packs out there - you can find a few of them if you search for "hdnes packs" or the like on Google, but the few that exist are for games with a limited amount of graphics (e.g mario bros 1).

To get the packs to load, make sure you enable the "Enable HDNes HD packs" option in the video options.  I'll probably enable this option by default in the next version.

**Comment by Cibomatto2002** [comment]
Thanks A lot
