### ISSUE TITLE
HdPacks NSF files

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#226]
Can HdPacks play other NES game soundtracks form a NSF file? It would be nice to play Zelda 1 music in Zelda 2. We could choose what song would play on what level. I would like Zelda 1 levels to have different songs for every level.

**Comment by SourMesen** [comment]
The HD packs are now able to play any OGG sound file as a replacement for a game's BGM or sound effects - _however_ this functionality requires hacking the game's code to do so.  There is no simple/automated way of altering a game's audio without spending time to understand how the game plays it's music/sound effects and changing the game's code to use the functionality I implemented in HD packs.

So what you're describing is possible - but it's something that would take a number of hours.

**Comment by Cibomatto2002** [comment]
Oh ok.

**Comment by GregoryMcGregerson** [comment]
It would be cool to have it work with tileAtPosition/spriteAtPosition feature where depending on the tile/sprite on screen (level-world number) you can choose a different music file.

**Comment by SourMesen** [comment]
The conditions can only actually work in the context of the graphic substitutions - changing the music/sound is completely unrelated.  On the other hand, when changing the sound, you're already changing the game's code - so there is nothing stopping you from adding new tracks where only 1 track used to be played on multiple maps, for example.
