### ISSUE TITLE
Feature suggestion: TrueType fonts for HDPacks

### ISSUE THREAD

**Issue by GregoryMcGregerson** [SourMesen/Mesen#227]
Today I was thinking of how much of a pain it is to create good looking sprite fonts for replacing letter/number tiles and how uneven everything looks when doing that due to most fonts not being monotype, and I thought it would be so much simpler to be able to define the alphabet tiles in the debugger and make it so you can assign it to the corresponding letters & numbers, having a new a layer that replaces and displays text as a TrueType font, while allowing you to choose; font size, alignment, kerning, color, bolding, italics, etc. The actual font files could be placed into the HDPack zip and used from there without being installed on the users system. I know this would be really hard to implement but it would help so much with displaying good looking text on screen, especially at higher resolutions with HD packs.

![text-example](https://user-images.githubusercontent.com/8885274/29547644-3293de4a-86b0-11e7-9100-50d0fd457864.png)

**Comment by SourMesen** [comment]
Thanks for the suggestion.
I'd imagine loading TrueType fonts from C/C++ is probably a nightmare, though (and loading them is one thing, rendering them is a whole other thing). 
I think a more reasonable approach would be to allow "oversized" tiles, e.g replace a 8x8 tile with a tile of any size which overflows.  Then you could just define such a tile to match to a location in a png file that contains the prerendered script and display it on the screen.

That being said, it might not be too simple to get done.
Maybe it would be easier to have an opposite to the <background> tag that instead lets you display things in the foreground, at specific locations, over the rest of the screen?

**Comment by GregoryMcGregerson** [comment]
I think any solution is going to be complicated to implement. The oversize idea sounds interesting. It could also be a solution to meta-sprites and having sprites or tiles larger then normal allowing more detailed replacements that go out of bounds of the normal area (ie larger monsters in turn based RPGs), which is similar to the BG replacement feature you already have.

Perhaps having a large common sprite font premade that looks good in most games, which is included somewhere, maybe as a tutorial on replacing tiles is a good way to go.

I guess just put this suggestion on the back burner for now and do what you think is best and most versatile for all users. Anyways thanks for hearing out my idea!

**Comment by GregoryMcGregerson** [comment]
Oh BTW this is my old attempt to standardize a font layout for people to use. It's all the colors from the NES using the HDNes palette. It includes Hiragana, Katakana, English and punctuation. See the readme file for more information. [http://www.mediafire.com/file/0uadi87ch7cdf5s/HDNes_-_Standard_4x_Fontpack.zip](url)

**Comment by SourMesen** [comment]
This is probably not something I'll be adding as-is.  There have been some other suggestions that could potentially also be used to display text as well, which would be better than having a text-specific solution.
