### ISSUE TITLE
Some codes can not be imported from FCEUX

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#23]
First I want to thank you for everything you do on the program. :) I really enjoy the Import and Export also the cheat search it's really easy to use. 

I found a few codes that I can't import there may be more I just started importing them.

[Codes that can't be inported.zip](https://github.com/SourMesen/Mesen/files/441013/Codes.that.can.t.be.inported.zip)

Here is a video of me trying to import them.

https://www.youtube.com/watch?v=faItTJKz22Y

**Comment by SourMesen** [comment]
Thanks for the bug report!

The code to import CHT files was bugged in some cases (when codes inside the CHT file are marked as "disabled").  This should be fixed by 94dd968
