### ISSUE TITLE
Some suggestions for Mesen

### ISSUE THREAD

**Issue by RetroGameIntros** [SourMesen/Mesen#230]
Proposing you some suggestions (new features) to add / or try add in Mesen, if possible

1) Autofire Pattern (Fceux) ;
2) Autofire Offset ;
3) Alternate A and B ;
4) Movie Status Icon

**Comment by SourMesen** [comment]
The first 3 seem to be a bunch of different settings for the turbo buttons - I'm not sure there is a whole lot of value to them for normal gameplay (nobody has really ever complained about the turbo feature in Mesen being problematic).

The last one is available already: Options->Preferences->Display play/record icon when playing or recording a movie

**Comment by SourMesen** [comment]
I think I'll hold off on these for now - it would complexify the setup for turbo buttons, and probably doesn't really give that much benefit in most cases.  It might be worth it when TAS tools or re-recording and the like are implemented, for the sake of speedruns, etc - but for now it mostly feels like unneeded complexity for the end user.
