### ISSUE TITLE
Suggestion: Individually remove save states and recent files.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#235]
A "X" remove button right to the slot is something nice to have I think. Another suggestion is to have the possibility to give a name to the save.

![2017-09-02](https://user-images.githubusercontent.com/30609937/30039711-4592822a-91ab-11e7-9042-7b69ed15ae11.png)

Thank you.

**Comment by SourMesen** [comment]
I don't feel like a delete button really adds any value - why would you really need to erase a save state?
On the other hand, it adds the possibility of a user deleting a save state by mistake, which seems a lot worse.

In 0.9.2, you can save & load states to/from any file you want, so in a sense, it allows you to give "names" to save states - they don't show up in the UI directly, though.

**Comment by PinkLouie** [comment]
As you can see in the screenshot, two of my saves were saved at the same minute, so they have the same "name". One of them is not useful anymore. so I would delete it, because I would not use it, and I can load it by mistake. Maybe no one would delete it accidentally if the save state had a name and the delete option asked for a confirmation.

**Comment by SourMesen** [comment]
I understand that in some very specific scenarios you might want to delete a save state, but it's not a typical use case.  From a UI perspective, adding a delete button and the ability to name these numbered save states is a lot of work, for not a lot of added value.

Also, like I mentioned, the "Save state to file" feature in 0.9.2 already allows you to create "named" saved states by giving them the filename you want.

If you really need to delete a save state for some reason, I would suggest just going into Mesen's "SaveStates" folder and erasing the corresponding files - they are named based on the rom's name & the slot number (so it is easy to find and delete a specific slot)
