### ISSUE TITLE
Allow key combination in shortcut binding

### ISSUE THREAD

**Issue by pinobatch** [SourMesen/Mesen#238]
So I was messin' around with Mesen 0.9.2 in Mono 4.6.2.7+dfsg-1 in Debian 9. For cross-application consistency, I prefer my NES emulator to have the same key bindings as my JavaScript emulator (that is, my web browser):

* Reset: Ctrl+R, like Reload
* Power Cycle: Ctrl+Shift+R, like Reload Bypassing Cache
* Power Off: Ctrl+W, like Close Tab

Ctrl+R is already bound in Mesen. But when I try to bind the others in Mesen's Preferences > Shortcut Keys, it instead immediately binds it to "Left Control" instead of waiting for me to release Ctrl.

Would it be hard to allow binding a chord of multiple keys to a command? They don't have to be modifier keys on the keyboard; they can also L+A, L+B, L+X, L+Y, or whatever on a connected joystick.

**Comment by SourMesen** [comment]
Shortcut keys are split into 2 categories right now - the first are UI-side shortcuts, Ctrl+R is an example of this.  Those are handled by the WinForms UI, and can't be remapped.

Then there is the `Shortcut Keys` tab in the preferences, these shortcuts are all handled by the emulation core instead (there is some overlap between these 2 categories, e.g reset).

The shortcuts processed by the core, as it is right now, can only handle 1-key shortcuts (e.g no modifiers, etc.).  Ideally, I want to eventually scrap the (old) UI shortcuts altogether, move everything to the Shortcut Keys tab and allow them to accept key combinations. I don't *think* this would require an excessive amount of effort to change, but it's probably not a very small change either - I'll try to take a look at this soon

**Comment by SourMesen** [comment]
This is fixed by a4d06f683a2e3e32f19f174b4df9ef2df820b028.  I've removed all hardcoded shortcuts from the main window, and replaced them with customizable shortcuts in the Preferences.  The shortcut keys tab now allows multi-key combinations, too (up to 3 keys at once - can be any key, including gamepad buttons).
