### ISSUE TITLE
Mesen Crashed

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#239]
It's rare that Mesen will crash on me but I thought I would send a SMP Dump of it anyways.

https://ufile.io/vkxa4

**Comment by SourMesen** [comment]
Did you have the cheats window opened?
A change I did in 0.9.2 has apparently made it more likely for Mesen to crash if a game is running while the cheat window is opened (I noticed this on my end yesterday)

**Comment by Cibomatto2002** [comment]
Yes the cheats windows was opened. I will upload upload the SMP file again I had no idea that the place that I uploaded it to was so slow. mega:#fm/xOZAwRaI

**Comment by Cibomatto2002** [comment]
Is there going to be a quick fix so I can re download it?

**Comment by SourMesen** [comment]
I'll try to make a small bugfix release soon-ish (e.g a few days).

I'm not sure what fixed your fullscreen issue, either, but happy to hear it's fixed!  I made some window size logic changes in 0.9.2, maybe that's what fixed it.

At this point in time, adding other consoles to Mesen is a bit unlikely - a lot of the UI is very NES-specific right now (especially when you look at all the debugging tools).  If I were to ever want to make an emulator for something else, I feel like it would make more sense to make it into a completely different application.
I'm not too sure about the idea of starting an emulator for another console, though - it takes a lot of time to make an emulator that is worth using, I've probably spent at least a couple of thousand of hours on Mesen, if not more!

**Comment by SourMesen** [comment]
This should be fixed by 5b8a37e3923524b5979c82f66e5610353e7a699d
