### ISSUE TITLE
Request: Folder override for ROM directory / Clear history button / Drag & Drop for ROMs.

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#242]
Pretty simple stuff really, your recent [folder override](https://i.imgur.com/Y1WRn0N.png) which you added is great but it's missing a field for where to point to where your ROMs are located, can one be added?

Also most emulators keep a history of your recently played games, yours does too, but can there be a "clear" button added... to clear them, similar to [Nestopia](https://i.imgur.com/hmnSFTy.png) I tried clearing the line manually in the ini file but then Mesen would just keep crashing on startup, so yeah the manual way is not a good way to do this, I'm just not a fan of leaving a history so to speak.

Lastly would it be possible for Mesen to play ROMs by just dragging & dropping them (Game.nes or Game.zip) onto Mesen's screen? I just find that ultra convenient, It's hard to get used to not being able to do this when other NES emulators do.

Lastly Lastly, thanks for the consideration either way!

**Comment by SourMesen** [comment]
Mesen tries to keep track of the folder(s) your games are in automatically by default (for the sake of simplicity), I guess I could add a setting to override this. Clearing the history I can add as well.

About drag & drop, that's a bit odd - loading via drag and drop has been implemented for years, and I use it all the time - not quite sure why this wouldn't be working on your end? It works on my Win7 machine and my Win10 VM (and I know other people have been using it as well)

**Comment by ImSpecial** [comment]
Don't know why drag & drop loading doesn't work for me, the NES emulators I have and use, and now just recently tested this because you are making me second doubt my claim :P , FCEUX, Mesen, Nestopia UE, and NNNesterJ, only Mesen doesn't seem to pick the games up when I drag & drop, maybe it's my system, weird. If others can Drag & Drop then it's me and never mind then.

**Comment by SourMesen** [comment]
Game folder override: 5e318fd6144deaa2e8a82a47cdb15bee88737994
Clear recent files history: bcd0cd485f0a1a992cf4263b2f38a8f2e452cecc

I also added some error handling for the drag and drop code in 4704c923177f8478a5fbfc4a497238a05d171263, with some luck, that might help figure out what's not working on your end.

**Comment by ImSpecial** [comment]
Very cool, thank you.
