### ISSUE TITLE
error in game.

### ISSUE THREAD

**Issue by breaker1976** [SourMesen/Mesen#244]
incorrectly works game "air fortress".
bugs in the game menu.
at the entrance to the base we see a gray screen.

**Comment by SourMesen** [comment]
I haven't been able to reproduce any bug in air fortress - you may be using a bad dump of the game or are using some non-standard settings in Mesen that are breaking it?

**Comment by SourMesen** [comment]
Would need more information to investigate this - as it is, everything appears to be working normally on my end.
