### ISSUE TITLE
Can't use other input key while load state

### ISSUE THREAD

**Issue by MichaelZhangLF** [SourMesen/Mesen#253]
I can't use other input key while using load state function by shortcut key, but can use it while saving state.

**Comment by SourMesen** [comment]
Thanks for the report - this should already be fixed with recent commits.
You can try this build to confirm it fixes the problem for you: https://www.mesen.ca/MesenSizeFixes.zip

**Comment by SourMesen** [comment]
Closing this for now as I believe it is already fixed - let me know if you still have issues.
