### ISSUE TITLE
Change FDS BIOS and zipped BIOS

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#254]
Currently there is no way to change the FDS BIOS. It's only possible to choose the file the first time you try to open a FDS rom (as far as I now). Zipped bios are not supported. Like games, I think it would be good if zipped BIOS were supported. 

Thanks.

**Comment by SourMesen** [comment]
You can change the bios by replacing or deleting the FdsBios.bin file in Mesen's folder.
I think adding an option for this is overkill - the vast majority of users will never need/want to do this, which only adds complexity the UI for no real reason.
Support for zipped bios is a minor use case as well, I don't think it is worth the extra code complexity (most people will only configure the BIOS a single time, so it's hard to argue that not supporting zip files for this is an issue)
