### ISSUE TITLE
Icon resolution is small

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#256]
IMHO the icon size should be higher (1024 x 1024 probably), specially to match HDPI configurations. Currently it is small (ok for standard DPI with no zoom) and not smooth. You can see in the screenshot. 

![2017-09-27 3](https://user-images.githubusercontent.com/30609937/30919723-9f5e9576-a378-11e7-807d-c3d3f2d995c3.png)

Thank you.

**Comment by ImSpecial** [comment]
What even is the icon? An eye... doesn't really represent a NES emulator.

**Comment by SourMesen** [comment]
I think that screenshot of yours exaggerates the issue a bit :)
I don't really feel like spending time redrawing the icon for this (I would rather spend time implementing useful features or fixing bugs) - if I ever change the icon, I'll keep this in mind.

As for the icon, itself:
**Nes Em**(ulator) backwards = Mesen
Mesen: http://jisho.org/search/mesen

And that's how you end up with an eye!

**Comment by PinkLouie** [comment]
Yes, I exaggerated, because my monitor has a small resolution. It's a bigger problem for example, in a 4k monitor, or laptop with high a HPDI screen. So, I did it myself, it's not perfect, but better. I hope it will help you.

![mesen](https://user-images.githubusercontent.com/30609937/30944640-a360226e-a3cf-11e7-8225-edaa89c2133c.png)

**Comment by Lululalu** [comment]
You really should the updated icon PinkLouie made. It's good, it's better.
