### ISSUE TITLE
I can't go to https://www.mesen.ca/

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#257]
Am I the only one with this problem? I tried on my tablet and Desktop.

![1](https://user-images.githubusercontent.com/21169038/31056709-e385eeb8-a69b-11e7-9211-88f3eafc8ec1.jpg)

**Comment by Cibomatto2002** [comment]
It's working now.

**Comment by SourMesen** [comment]
The website is hosted on cheap shared hosting - it will definitely be down from time to time.
In general, there's probably no need to worry unless it is down for over a day.

**Comment by ImSpecial** [comment]
I just wanna add that your documentation for this emulator is very ace! Save for the maybe one or two  outdated pictures.

And maybe having an offline version of it would be good so people don't need an internet connection/web browser to view/hope your web host isn't down, to view it.

Maybe turn it into a CHM file bundled along with the emulator?

**Comment by SourMesen** [comment]
Turning it into a CHM may not be too easy - the website's source is essentially a set of markdown files that also contain a bit of HTML markup at times.  These are converted to an actual website by using another software, but it's unlikely I can find something to convert the same source markdown files into a CHM file without adding maintenance overhead.

At some point, I'll probably see about adding a zipped up version of the documentation website along the GitHub releases, though.

**Comment by SourMesen** [comment]
FYI, beginning with 0.9.5, an offline version of the documentation can be downloaded and browsed offline by opening the HTML files in your browser.
