### ISSUE TITLE
Edit cheats Feature

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#26]
Do you think we may see a way to edit the cheats after they are put in? like change the name of a cheat or the value of a cheat.

**Comment by SourMesen** [comment]
You can already do this by double-clicking on any cheat in the list.
Although I guess I could add an explicit "Edit cheat" button in the toolbar.

**Comment by Cibomatto2002** [comment]
Oh ok I did not know to double click on it to edit. thanks.

**Comment by Cibomatto2002** [comment]
It's ok you don't have to add that. Double-clicking work just fine. 
 

    On Monday, August 29, 2016 3:12 AM, SourMesen <notifications@github.com> wrote:
 

 You can already do this by double-clicking on any cheat in the list.
Although I guess I could add an explicit "Edit cheat" button in the toolbar.—
