### ISSUE TITLE
Mesen Ignores Keyboard Inputs if XInput Device is Sending Input

### ISSUE THREAD

**Issue by wildgoosespeeder** [SourMesen/Mesen#260]
On the latest build (0.9.3), I was trying to savestate with Shift+F1. Couldn't figure out why the emulator wasn't doing what I was telling it to do. Turns out, as I was pressing the keyboard shortcuts, I was holding down a button on my XInput device (like to hold NES B to allow Mario to run in the Super Mario Bros. games). To use the keyboard shortcut, I have to let go of the XInput buttons. This could be a problem for some games to savestate with a button needing to be held down.

**Comment by SourMesen** [comment]
Thanks for the report - this is probably the same as #253 
It should already be fixed in the latest commits, you can try this build from yesterday: https://www.mesen.ca/MesenDebuggerFixes4.zip

**Comment by wildgoosespeeder** [comment]
It might not be the same problem, because his commentary is vague, but the bug is fixed in the version you linked me to. Thanks for getting to this so fast!

**Comment by SourMesen** [comment]
No problem!
