### ISSUE TITLE
Feature request: Input Datach Barcode

### ISSUE THREAD

**Issue by wangsitan** [SourMesen/Mesen#266]
Hello. I see the roadmap says: 'Support for more UNIF boards and more NES/Famicom input devices'. Is there a plan for adding Datach barcode input? 

I'm tring to hack a Datach game 'Battle Rush'. Mesen's debugger looks very strong, but it doesn't help when I need to input barcode.

Anyway, this is an awesome emulator, thank you for your work.

P.S. Do you know any other debuggers having Datach barcode input feature? No$nes has that, but its debugger is kind of simple. Sorry for the trouble.

**Comment by SourMesen** [comment]
Hey,

I'm actually in the middle of implementing all of the missing input devices (including the barcode readers) right now.  It involves a lot of changes (movie format, netplay, UI for the key bindings, etc.), so it will probably be a few more weeks before I'm completely done with this, though.

At the moment, I'm not aware of any emulator that supports it and has decent debugging tools, either (didn't even know about no$nes supporting it - I don't really use it much).

**Comment by wangsitan** [comment]
Thank you for your effort. Donated =)

**Comment by SourMesen** [comment]
Thanks! I'll let you know once this is done.

**Comment by SourMesen** [comment]
For your info, I just discovered FCEUX does have support for this in its code, but for some reason, there is no UI for it in the Windows version: https://forums.nesdev.com/viewtopic.php?f=3&t=10251

**Comment by wangsitan** [comment]
Hahaha, thank you very much for your help, I got this link by searching, too. A fun thing is, FCEUX has no Datach input in win version, and has no debugger feature in SDL version (this is my post for the question: http://forums.nesdev.com/viewtopic.php?f=2&t=16563). Now, Mesen is my hope (not mean to give pressure on you).  =)

**Comment by SourMesen** [comment]
As of 850102bbdc5d6798135619906bac1e8486504a13, this is available - still may require some more changes between now and the next release, but for the most part it works (including recording in movies & over netplay)

**Comment by wangsitan** [comment]
Got it. Thank you for your effort.
