### ISSUE TITLE
Fullscreen command line bug

### ISSUE THREAD

**Issue by Phanatical** [SourMesen/Mesen#267]
One of the devs for RocketLauncher had made a module for Mesen but there's a problem we've encountered.

When using the /fullscreen command, it changes the video scale to 4.50 for some reason. Which means the game window is shrunk down a bit. When I launch Mesen standalone and go fullscreen, the scaling sets to 4.82 which is correct on my 1080p monitor and fills properly.

So there seems to be an issue with the video scaling being set wrong when simply using the /fullscreen switch.

**Comment by SourMesen** [comment]
Thanks for the report - it looks like the issue only occurs when overscan is not set to 0 for all sides.
I'll have it fixed in the next release.

**Comment by SourMesen** [comment]
This should be fixed by 372c1b049cf58ca002f479dac0002904ab01cfeb.
