### ISSUE TITLE
ppu viewer > chr selection does not refresh when selected.

### ISSUE THREAD

**Issue by retro-wertz** [SourMesen/Mesen#268]
Not sure if this is intended, but in debugger > ppu viewer > chr viewer then Chr selection pulldown menu, when choosing a chr to view using arrow keys+enter, it does not display it. Only when selecting and then clicking with the mouse allows it to be viewed.

[https://i.imgur.com/fKni3uj.png](url)

im running linux/mono

**Comment by SourMesen** [comment]
Thanks for the report! Looks like this might be a Mono bug with a specific WinForms event.
I've fixed the issue by using another similar event instead (abaf524e99e55e0ce0c1bca8900b487a0c7f9bed)
