### ISSUE TITLE
Autosaver for mesen

### ISSUE THREAD

**Issue by medigi** [SourMesen/Mesen#27]
How about add this feature, or this is already in Mesen?

Something like this add in Mesen
![1](https://cloud.githubusercontent.com/assets/21311432/18053284/52b4035c-6e07-11e6-9dff-aab7a147da60.jpg)

**Comment by SourMesen** [comment]
Thanks for the suggestion!
It's a good idea and should be simple to add.

**Comment by SourMesen** [comment]
This has been implemented in 1ddb980.

Automatic saves are done to the 6th save state slot, which is only available in the "Load State" menu (or by pressing F6)
You cannot manually save a state to the 6th slot - only the automatic save feature can.

![untitled](https://cloud.githubusercontent.com/assets/21093973/18151457/4cc3a652-6fbd-11e6-99f0-399c0ef02518.png)
