### ISSUE TITLE
Linux: compile issue, commit 850102b

### ISSUE THREAD

**Issue by retro-wertz** [SourMesen/Mesen#276]
@SourMesen 
compile error in trying to compile latest commit: 850102b

```
../Console.cpp:268:18: error: conditional expression is ambiguous; 'std::__cxx11::string' (aka 'basic_string<char>') can be converted to 'VirtualFile' and vice versa
        return Instance ? Instance->_patchFilename : VirtualFile();
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [makefile:82: Core/obj.x64/Console.o] Error 1



```
can compile with "return Instance->_patchFilename" instead but not sure what should be there.

**Comment by SourMesen** [comment]
Thanks - I did a quick check over the code in Linux and fixed the warnings & errors clang gave - both clang & gcc should compile properly now.
Keep in mind that the new input changes aren't finished yet and haven't been tested under Linux at all, so there might be a number of issues still.
