### ISSUE TITLE
Graphics Editor [feature request]

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#277]
In the future could we see a Graphics Editor? All I really want is a tool to change the colors of the Graphics and be able to save them. 

![image](https://user-images.githubusercontent.com/21169038/33227671-be071bf6-d16d-11e7-9322-ab342f3ad9e3.png)

https://www.romhacking.net/utilities/108/

**Comment by SourMesen** [comment]
This is already something you can do in the PPU viewer's CHR viewer tab.
You can also (temporarily) change the palette via the Palette Viewer - however, these changes are not permanent.  Permanently altering the palette essentially requires altering the game's code, so this is not something that can be done via an editor.

**Comment by Cibomatto2002** [comment]
I see thanks for your time.
