### ISSUE TITLE
Rewinder

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#28]
Thanks for getting 4.3 out so fast. 

Do you think we may see this feature in the future? it could be mapped to the Back Space key.

https://www.youtube.com/watch?v=zKKg3vf35B0&feature=youtu.be

**Comment by SourMesen** [comment]
A rewind feature is on my list of things to do, but it could be a while before it's added.

**Comment by Cibomatto2002** [comment]
I'm in no hurry for it it was just something I remembered using a few times you had to press the select button to use it I never could understand why you never could  mapped it to a button in FCEUX maybe it was because it was a .lua file. Here is the file in case you need it.


 
[Rewinder.zip](https://github.com/SourMesen/Mesen/files/445787/Rewinder.zip)

**Comment by SourMesen** [comment]
FYI, rewind functionality has been added with 3a6c8ca41646196cd5364af82163594312c78116 - will be available in the next release.
