### ISSUE TITLE
Option for not displaying blackout (fogging)

### ISSUE THREAD

**Issue by lomaxgames** [SourMesen/Mesen#280]
When you press "Pause" or hotkey for pause, in Mesen there's blackout / fogging ("затемнение" in russian). In fceux, there no blackout or fogging, only pause icon " [ | | ] "

If there impossible to do something with this, maybe u can simple reduce blackout / fogging when pressing "Pause" ?

Fceux:

![fceux_2017-12-15_22-01-05](https://user-images.githubusercontent.com/34583944/34058418-a1b1563e-e1e3-11e7-8fa5-fd53d4d1094b.png)

Mesen:

![mesen_p_2017-12-15_22-01-38](https://user-images.githubusercontent.com/34583944/34058422-a52ef2d0-e1e3-11e7-9f11-1a5b0e82d38b.png)

**Comment by cyrilleCh** [comment]
Look at "preferences" > "hide the pause screen"

**Comment by SourMesen** [comment]
Thanks for the request - like cyrilleCh said, it is already possible to hide the pause screen completely via the preferences menu.
