### ISSUE TITLE
HD packs

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#282]
Are you going to include the Megaman 1 HD pack from https://www.romhacking.net/forum/index.php?topic=25426.0 so people can see how nice the HD packs can be? Do you know any other HD packs that I can try out.

**Comment by SourMesen** [comment]
As much as it would be a nice feature to have, I don't have any plans to bundle any HD packs with the emulator - doing so would more or less be a legal mine field.
That Megaman HD pack is the only pack I am aware of at the moment (aside from a few small older ones that were created for HDNes some years ago)
