### ISSUE TITLE
feature request - always on top + hide menus

### ISSUE THREAD

**Issue by rob-lindman** [SourMesen/Mesen#283]
Should be self-explanatory, but a menu option and keyboard shortcut for the window to remain always on top would be good.

Also good, a feature in some other emulators allows hiding the menu and window 'chrome' so the window is just on screen, perhaps with a small border, draggable by holding the mouse down anywhere in the window. 

thanks for the fun!

**Comment by SourMesen** [comment]
Thanks for the requests - I added a "always on top" option in a93d50ea1f0626556cb16f8805cbf5aafa182c97.
There is already an option to hide the menu, but I'm assuming you're asking to hide the whole window's frame? I'd rather not do this right away since I'm trying to get a new release done, but I'll take a look into it later on.

**Comment by rob-lindman** [comment]
Hmm... I did a check for updates and it says I'm running the latest version, 0.9.3. So perhaps this option is only available a source version? I would be looking for Tools (menu) >> Always on top with a check. If it's there and done, and just waiting for a release... feel free to close the issue.

Yes, I'm talking about hiding the window frame. 

These are just requests, feel free to do as you please with them.

**Comment by SourMesen** [comment]
Yes, the option will be available in the next release (0.9.4 - probably in a few days).  It's in Preferences->Advanced, but there is also a customizable shortcut toggle key for it that you can configure if you need to toggle it on/off frequently.

I'll keep the "hide window frame" request in my notes and see about implementing it in a future version.
