### ISSUE TITLE
Feedback on Mesen 0.9.3

### ISSUE THREAD

**Issue by lomaxgames** [SourMesen/Mesen#284]
Thanks Sour for this emulator, this is only one which correctly emulating Wagyan Land 1-3 , especially 3rd one. On fceux / nestopia / puNES and other, there some graphical bugs. On your emulator that games working fine.

Now i'm want to ask, when we have new version of Mesen? :)

**Comment by SourMesen** [comment]
Thanks for the feedback, happy to hear you like it!
A new release should be (finally) ready in a few days (hopefully in 2017!), though I don't have an exact date.
