### ISSUE TITLE
Sometimes newlines are not displayed on "Edit Label" dialog

### ISSUE THREAD

**Issue by taotao54321** [SourMesen/Mesen#286]
On Mesen debugger, sometimes newlines are not displayed on "Edit Label" dialog. I guess this might be a problem of newline code (LF/CRLF).

I edited comments on the debugger and saved `.mlb` file with "Export Labels", and later loaded it again with "Import Labels". Then, the comments are correctly displayed on disassembly list, but they are displayed without newlines on "Edit Label" dialog:
![mesen-issue-newline](https://user-images.githubusercontent.com/21364118/34429611-e239636c-ec9d-11e7-8498-5a9ba8aea45f.png)

Here is the corresponding line in the `.mlb` file:

```
P:7FFBE:_prg_switch:バンク切り替え (m8000-mBFFF)\n----\nIn\n  X     U8  バンクID    # 8K単位
```

### My environment

* Windows 7 SP1 (Japanese)
* Mesen 0.9.3 (I also tried HEAD, but the same issue occured)

**Comment by SourMesen** [comment]
Thanks for the report! 
I can reproduce it on 0.9.3, but as far as I can tell, it's fixed in the latest commit (it was fixed by a commit I did a few days ago).
You can try this build, it should work correctly: https://www.mesen.ca/MesenDecember29.zip

**Comment by taotao54321** [comment]
Thank you. This build worked correctly.
Probably I forgot to pull the newest commits. Sorry for the trouble.
I will close this issue.

**Comment by SourMesen** [comment]
No problem!  Let me know if you find anything else.
