### ISSUE TITLE
No message when toggling keyboard mode

### ISSUE THREAD

**Issue by lomaxgames** [SourMesen/Mesen#288]
Load any game , press default key "Scroll Lock" to toggle keyboard mode and you should got a message. I didn't getting any message. I'm tryed downloading Mesen from github and making clean install, also changing key no result

**Comment by SourMesen** [comment]
Keyboard mode is available when the Family Basic Keyboard or Subor Keyboard is plugged in - at any other time it's disabled & cannot be enabled (even by pressing the shortcut for it).  Do you have either of those keyboards connected as the expansion device in the input settings?

**Comment by lomaxgames** [comment]
No, i don't have any of them, playing usually all games via gamepad / usb keyboard :)
