### ISSUE TITLE
Cheat codes will not turn off.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#29]
I can't turn the codes off.  It's like the check box does not work they always stay on.

**Comment by SourMesen** [comment]
Thanks, ecea158 broke this.
I've updated the 0.4.3 download on the website to include a fix (da78317) for this, so if you download Mesen manually from the website it should solve the issue.
I'll look into making another proper release including the fix in the next few days.

**Comment by Cibomatto2002** [comment]
Thanks for getting it fixed so fast. Everything seems to be working correctly now.
