### ISSUE TITLE
So, 0.9.4's settings.ini is... large?

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#290]
Coming from 0.9.3 my settings ini was 32KB https://i.imgur.com/1bGjHcy.png

now after upgrading to 0.9.4 it's now, over a meg, normal? https://i.imgur.com/TVwEym8.png

I tried deleting it but the same thing, I also tried to look inside of it to make sense of it and there's just a lot of; 
            <unsignedInt>0</unsignedInt>
            <unsignedInt>0</unsignedInt>
            <unsignedInt>0</unsignedInt>
            <unsignedInt>0</unsignedInt>
etc.

**Comment by SourMesen** [comment]
1mb? That's odd, mine's "only" 190kb.  Can you attach yours so that I can compare?
But yea, that's an oversight. I didn't realize .NET serialized byte arrays in such a silly way and never actually opened the settings file during dev.  I should be able to fix it in the next release.

**Comment by SourMesen** [comment]
The settings.xml file size should be back down to around 50-60kb as of bb18cf9a3fd6075d8388106d93dbff666b12d9d8.  This change will reset keybindings for most special input devices to their defaults, though.

**Comment by ImSpecial** [comment]
Oh wow, I totally forgot about this bug, sorry about that, I should have told you that this _was_ an issue at first, and when deleting the XML file to start fresh I was able to reproduce this "sometimes" reproduce it, but it somehow fixed it self and I wasn't able to get it to grow so large anymore, and just kinda forgot about it, its been and currently sitting at around 195KB on the latest version of Mesen.

But thanks for looking into this and reducing the file size is always a good thing. I assume it just doesn't write settings now unless you make a change to something? Like config controllers you've never used won't have a blank template now.

**Comment by SourMesen** [comment]
No problem.

I actually cheated and did my own "serialization" for arrays instead of using .NET's unnecessarily verbose one.  e.g, this:
```
<unsignedInt>0</unsignedInt>
<unsignedInt>0</unsignedInt>
```
became just: ```"0,0"```

For controllers that types that used this pattern & have no keybindings, they'll be empty, until a keybinding is configured, to save a bit of extra space (esp. since some of the bindings available for P3/P4 in the config file aren't actually something you can configure at all).
