### ISSUE TITLE
音声は等速で倍速プレイ出来る機能をリクエスト

### ISSUE THREAD

**Issue by futukan** [SourMesen/Mesen#292]
倍速プレイ機能をリクエストします
倍速プレイ機能は、音声だけ等速に出来るようにして欲しいです。
倍速プレイだけど音声だけ等速という機能

**Comment by SigmaVirus** [comment]
Straight from Google Translate:

Title:
"Request a function that can play double speed at constant speed"

Message:
"I will request a double speed play function
I want the double speed play function to make it possible to make the sound only at constant speed.
Although it is double speed play, the function of only voice equal speed"

**Comment by SourMesen** [comment]
リクエストありがとうございます。残念ながら、これは多分不可能と思います。
ファミコンではゲームの速度を上げると、必ず音楽のテンポも早くなります。
例えば、120fpsの速度なら、テンポが２倍とピッチも高くなってしまう。
エミュレータだと、ピッチの部分だけなら直す事ができますが、テンポの方はどうにもならないと思います。

**Comment by SourMesen** [comment]
Closing since this can't actually be done (as far as I know)
