### ISSUE TITLE
Feature request: option to pause when menu selected

### ISSUE THREAD

**Issue by stubl** [SourMesen/Mesen#296]
Mesen provides a lot of options when it comes to user interaction, which is something I really like, but there is 1 thing that would be nice to have among the Pause/Background Settings, which is "Pause when menu is selected"

this is often with other emulators where menu access pauses emulation, and I find it a lot easier to handle saving and loading save states with this, and video filters etc

**Comment by SourMesen** [comment]
Thanks for the request! (And sorry for the late reply)
This should be taken care of by f14747e110df33c0b012a1a225e330302a1a57df
There are a couple of new options to control the auto-pause behavior, including one to pause when in menus or configuration dialogs.
