### ISSUE TITLE
Several bugs in the script window  

### ISSUE THREAD

**Issue by hksy** [SourMesen/Mesen#297]
I have found some problems related to the Lua script window.  

### Screen not display after opened NSF  
1. Opening a ROM or NSF, then open the debugger and script window.  
2. Open NSF file.  
3. Open ROM file.  
4. The game screen is not displayed. (can play games)  

### Crash in quit  
1. Changed the script contents.  
2. Quit the Mesen.  
3. Crash after displayed the save confirmation dialog.  

### Environment  
* Mesen : 0.9.4 (confirmed at Release version and commit #2f93057)
* OS : Windows 7 Professional SP1 64bit
* Frequency : Certainty

sorry for my poor english...

---

### NSFを開いた後にゲーム画面が表示されない  
1. ROM、またはNSFを開いた状態でデバッガおよびスクリプトウィンドウを開く  
2. NSFを開く  
3. ROMを開く  
4. ゲーム画面が表示されません（ゲームのプレイ自体は可能）  

デバッガはスクリプトウィンドウを開いた後に閉じても上記現象が発生しました。  
直前にNSFを開いた事が条件のようで、再度ROMを読み込んだ場合は発生しませんでした。  

### 終了時にクラッシュ  
1. スクリプトの内容を変更する  
2. Mesenを終了する  
3. 保存確認ダイアログ表示後クラッシュします（どれを選択しても発生）

**Comment by SourMesen** [comment]
バグ報告ありがとうございます。
NSF関連のバグは 7debc4e98c66e848594b39a229f2d9c858381e2c で直しました。

Luaスクリプトにより終了時のクラッシュの方は今のところまだ再現できていません。
Visual Studioで起動して、クラッシュしてる状態でのParallel Stackウインドウの内容を送ってもらえたらバクを再現するための条件がわかるかもしれません。

**Comment by hksy** [comment]
設定の`Mesenが最前面ではない時、自動的にポーズする`が有効の場合に発生するようです。

以下、Visual Studio 2017のスクリーンショットです。  
https://www.dropbox.com/sh/52afgf0shjz2ohx/AABc2Kgcr85pxuoONZRYI7S2a/Mesen/Mesen_ScriptWindow.png

**Comment by SourMesen** [comment]
ありがとうございます！　おかげでクラッシュを再現できました。
1e76d25986053eb344b23925815799cf81fd536d で直しているはずです。

**Comment by hksy** [comment]
最新コミットで直っていることを確認しました。  
素早い対応ありがとうございました！
