### ISSUE TITLE
Don Doko Don 2 - "Invalid OP code - CPU crashed" when rewinding

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#309]
This error happens every time the rewind function of the emulator is used with Don Doko Don 2 during gameplay: "Invalid OP code - CPU crashed". If I try to start the same game or any other game again, they are played at increased speeds. Mesen needs to be restarted to fix this. I've reproduced this with a fresh copy of Mesen 0.9.4 without changing any setting.

Mesen 0.9.4 (running as Mesen_p.exe)
Windows 10

[mst.zip](https://github.com/SourMesen/Mesen/files/1615576/mst.zip)

**Comment by SourMesen** [comment]
Thanks for the report - it looks like this is actually fixed as of the latest commit.  It was fixed by a0a6d89416ed68dc5ac3be74a01c02430e7f2197.

I'm not sure I like the implications of that commit fixing this though, I'll need to investigate more to find the exact cause when I have some time.

**Comment by SourMesen** [comment]
Only a year late, but I finally got around to checking this - it was actually a mapper-specific bug when loading save states (and the fact that it worked after that other commit was just pure luck). Properly fixed the issue in b01c2d3f837c491e84b0313606984e4e4fbd6557.
