### ISSUE TITLE
ディスクシステムに不具合が

### ISSUE THREAD

**Issue by futukan** [SourMesen/Mesen#310]
ディスクシステムのゲームは面の切り替えとかの処理が出来てないゲームがあるようです
ディスクシステムのゲームは動作しないゲームが多いのではないでしょうか
あとはディスクシステムくらいでしょうかね
それ以外は完成度高いようです

**Comment by SourMesen** [comment]
「ファミコンディスクシステムのゲーム中に自動的に該当するディスクを入れる」って言う設定を使っていたのなら、公式なソフトでも色々不具合があって、f4a867384893c134f1944e448ce007e2568ab060で直しているはずです。

この設定を使っていない場合は、ゲームの名前を教えてください、調べてみます。

**Comment by SourMesen** [comment]
As mentioned, should hopefully be fixed by f4a867384893c134f1944e448ce007e2568ab060
