### ISSUE TITLE
Scaling above 4x gets cut off

### ISSUE THREAD

**Issue by GregoryMcGregerson** [SourMesen/Mesen#312]
So today I decided to try Mesen on my 4k tv and while using fullscreen and scaling above 4x the bottom and right side of the screen is cut off. It's kind of strange. I'm using integer scaling and exclusive fullscreen mode. I'm using a GTX 1080 running a screen resolution of 3840x2160, I'm also using nvidia gpu scaling instead of letting the screen handle it which in an advanced option in the driver settings. I haven't tested turning that off but I don't think that will help any. Seems to be an issue of having scaling above 4x. I think a 4k screen would be 8x scaling which doesn't seem to be supported anyways because the highest setting in the options I can find is 6x. Although the command line wiki says it can go up to 10x. This probably isn't a high priority fix since most people run 1920x1080 resolutions but I just thought I'd report it. Have a good day!

**Comment by SourMesen** [comment]
Any chance this looks the same as #295?
I'm using a 2560x1440 monitor and don't get the issue, though, it looks like it might be 4k-specific somehow, unsure why.

FYI, the scale can be anything between 0.1 to 10.  You can set it manually in the video options, but shortcut keys to switch only exist for 1x to 6x.

**Comment by GregoryMcGregerson** [comment]
Yes this is the same issue. Sorry I did not see it.

**Comment by SourMesen** [comment]
Thanks for testing - too bad that didn't turn out to be the problem.
I don't have any 4k display to test with, unfortunately, so it might be a while before I manage to fix this.
Have you tried 0.9.3 to see if it works properly on your end too?  That would at least allow me to narrow it down to 0.9.4 changes.

**Comment by sharknnth** [comment]
SourMesen I can confirm that it indeed works properly for 4k displays on 0.9.3.

**Comment by sharknnth** [comment]
It works beautifully and I'm having no further problems with it. Thanks very much, SourMesen.

**Comment by SourMesen** [comment]
Thanks for testing the fix!
