### ISSUE TITLE
Auto exec script?

### ISSUE THREAD

**Issue by DayBr3ak** [SourMesen/Mesen#313]
I haven't seen anything like it in the command line options or documentation, so I'll ask here.
Is it possible to have my scripts to execute on startup?

**Comment by SourMesen** [comment]
Are you talking about Lua scripts?  There is currently no way to load/run one from the command line, but it should be relatively to add this if you need it.

**Comment by SourMesen** [comment]
Could you clarify what you needed? Do you want a way to load a game and immediately start a Lua script from the command line? 
e.g, something like this:  mesen myrom.nes --lua myscript.lua

**Comment by spiiin** [comment]
If you will do that, please add option to run couple of scripts at once (emulator support it, and it's useful for splitting script functional to separate files).

**Comment by SourMesen** [comment]
Thanks for the suggestion!
Giving the path to any ".lua" file in command line will now open up a script window & start executing the script. Any number of Lua files can be specified. (9be9a57565bd3d257c2570c3e223056d366211ca)

**Comment by rien333** [comment]
@SourMesen Is there an option to disable the script window from opening? (not sure if that's the best default option anyway) I don't think I plan on using it.

**Comment by SourMesen** [comment]
@rien333  The script window should not be opening unless you specify a script in command line or manually open it by clicking on it or using its keyboard shortcut.  If you mean you want to run a script without having the script window opened, that's not possible currently.

**Comment by SourMesen** [comment]
This is a bit more complex than just not opening the window, unfortunately.  And there are a number of potential issues (e.g if you just forcibly load the script without opening a window, and then open/close any debugger tool, the scripts will be unloaded, etc.)

What would be the behavior you would expect here?  At the moment power cycling or loading another game unloads the scripts automatically.  Would you expect the scripts to keep running in that scenario in your case?

Depending on what you need, I can take a look, but I'm trying to get a proper release build out sometime this month, so at the moment I'm trying to select/limit what I change to avoid regressions right before a release.

**Comment by rien333** [comment]
> What would be the behavior you would expect here? At the moment power cycling or loading another game unloads the scripts automatically. Would you expect the scripts to keep running in that scenario in your case?

My only use case is starting the game while simultaneously running some lua code. You can think of it as a kind of patch. I have a lua script that is meant to be executed together with some game, and if the global emulation state changes (loading other games, resetting)  I suppose it's okay if the script will unload, as my script is not meant for that stuff. And because it's only a sort of patch over some particulair game, I have no need for the script editor window. Additionally, I figure there are other people out there that would also prefer to code in their own text editor and have no need for the script window. 

> e.g if you just forcibly load the script without opening a window, and then open/close any debugger tool, the scripts will be unloaded, etc.

Not sure what I would prefer here. I suppose the current behavior is fine, as long as I also have the choice to not open any windows while running a script.

**Comment by SourMesen** [comment]
> Additionally, I figure there are other people out there that would also prefer to code in their own text editor and have no need for the script window.

There is nothing preventing people from coding in another editor, even with the script window (there's an option to auto reload from the disk when the script changes for this exact reason).

That being said, as far as I can tell, it looks pretty standard in NES emulators to force a Lua window to be opened while a Lua script is running (FCEUX and Bizhawk have the same behavior as Mesen, even from the command line)

**Comment by rien333** [comment]
Hm, if other emulators are doing it I understand the current behavior then. I'm aware that there's nothing preventing me from using my current editor; nevertheless as someone who likes the the Unix philosophy having two editors while I have a perfectly fine one seems like overkill + the window kinda gets in the way.
