### ISSUE TITLE
Mystery World Dizzy - Libretro

### ISSUE THREAD

**Issue by altiereslima** [SourMesen/Mesen#314]
Libretro Windows version - Mystery World Dizzy crash in Portuguese language. Mesen Windows version is OK.

**Comment by SourMesen** [comment]
Thanks for the report.
I haven't been able to reproduce this - I've tried a few different options including Portuguese in both NTSC and PAL, and can't seem to make anything crash.
Do you mean the game freezes somehow? Or does RetroArch itself crash?

**Comment by altiereslima** [comment]
Try Overclock=High in Portuguese.

**Comment by SourMesen** [comment]
I tried after/before NMI overclocks at High and couldn't get it to crash, either.
Is it Retroarch that crashes? Or just the ROM?

**Comment by altiereslima** [comment]
Just the ROM. 
https://youtu.be/xxAYgr73BR0

Just crash on High, Very High work fine.
