### ISSUE TITLE
Mag Max.NSF File Track 2 plays to slow

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#316]
I made a video of Mesen playing it and the nSFPlayer 2.4 beta 4 playing it. nSFPlayer 2.4 beta 4 plays it correct. I know this was talked about before but this time I made a video.

https://www.youtube.com/watch?v=AugvZ83HeTI&feature=youtu.be

**Comment by SourMesen** [comment]
On your video, if you take note of the times where the melody change, they match up between Mesen and NSFPlay as far as I can tell. e.g: around 0:14/0:15 the melody changes on both players, and again around 0:31/0:32.
I'm not exactly the best person to be comparing music in general, but I cannot see much of a difference between both of them

**Comment by Cibomatto2002** [comment]
The melody changes when I use the NSFPlay it plays it faster Mesen plays it slower it's no big deal i can use NSFPlay when i want to here it. :)
