### ISSUE TITLE
Feature request: Add 8x7 scaling mode for 4K monitors

### ISSUE THREAD

**Issue by Myriachan** [SourMesen/Mesen#317]
If you have a monitor capable of showing 2048x1680, it would be possible to emulate the NES's native pixel aspect ratio without blurring, because you could draw each NES pixel as 8x7 Windows pixels.

**Comment by SourMesen** [comment]
Thanks for the suggestion - as far as I can tell, though, this is already possible with the current options.
Just set the scale to 7x and the aspect ratio to NTSC, the resulting picture is 2048x1680 pixels.  If you keep bilinear interpolation off, there is no blurring and each pixel should be exactly 8x7.

**Comment by SourMesen** [comment]
Closing since this should already be possible.
