### ISSUE TITLE
Stack bytes sometimes invisible in debugger

### ISSUE THREAD

**Issue by Myriachan** [SourMesen/Mesen#318]
On some display configurations, such as my 4K monitor with 150% UI scaling, the stack bytes become unreadable in the debugger, being cut off.

![image](https://user-images.githubusercontent.com/8469545/35198322-f30113dc-fea1-11e7-8b38-1d2f72faaf88.png)

**Comment by SourMesen** [comment]
Thanks for the report - this should be fixed by eee218ccea48914d35b19bff0bc4bc2622d0777d
