### ISSUE TITLE
Blood Of Jurassic (GD-98)(Unl)[U][!]

### ISSUE THREAD

**Issue by sdefkk** [SourMesen/Mesen#320]
Blood Of Jurassic [(GD-98)(Unl)[U][!].nes
No support .nes file

**Comment by Cibomatto2002** [comment]
Loading rom: Blood Of Jurassic (GD-98)(Unl)[U][!].nes
File CRC32: 0xF18262C5
[UNIF] Error: Unknown board
PRG+CHR CRC32: 0x1CA9C322
[UNIF] Board Name: UNL-158B
[UNIF] PRG ROM: 128 KB
[UNIF] CHR ROM: 128 KB
[UNIF] Mirroring: Horizontal
[UNIF] Battery: No
[DB] Game not found in database

**Comment by retro-wertz** [comment]
unsupported board atm
https://github.com/SourMesen/Mesen/issues/136

**Comment by SourMesen** [comment]
Thanks for the report.  Like retro-wertz pointed out, this specific board isn't supported yet.  Support for the missing boards will be added eventually, but their priority is relatively low.
