### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sdefkk** [SourMesen/Mesen#322]
1. Set Overscan Ntsc/PAL Separate. (e.g: http://ddlw.org/img/fvcy7pq.jpg
2. Misc: Add .rar support

**Comment by SourMesen** [comment]
Thanks for the suggestions - 0f5d65da7e82405b985be249a90675ade4df0db3 adds a way to configure overscan for each game individually.

I won't be adding RAR support for a couple of reasons:
1) The license for the Unrar code is technically not compatible with GPL software
2) It would require a lot of additional code for very little benefit in this case (that majority of files tend to be in zip or 7z format these days)
