### ISSUE TITLE
Issue loading files from command line on Linux 

### ISSUE THREAD

**Issue by teamdisposable** [SourMesen/Mesen#324]
Ever since upgrading to 0.9.4 beta, I can't seem to load roms from the command line. They will load fine within the program itself once started, but it ignores the rom supplied from the command line, starting instead on the flickscreen showing previously played games.

Loading roms from the command line worked (almost) perfectly in the previous version. There was occasionally a delay in the rom loading on starting (it should show me the flick screen sometimes and then switch to the rom)

Nothing has changed on my machine, as I use a makefile to start the program (I'm testing my own homebrew in your wonderful emulator).

I've tested with commercial roms and the issue is the same.

Additionally, all other command line arguments I've tested seem to work (--fullscreen, etc), even if supplied with the rom.

Has the syntax changed? I did have a dig around a bit in the changelog, the help and on here but couldn't see anything.

Here is my current startup line (the rom name is generated automatically). This will start mesen but not load the rom:

`mono /home/mic/Mesen/Mesen.exe /home/michael/Desktop/nes/project/bin/runngun-2018-02-05.11.23.09.nes `

This will start mesen, not load the rom, but start in full screen:

`mono /home/mic/Mesen/Mesen.exe /home/michael/Desktop/nes/project/bin/runngun-2018-02-05.11.23.09.nes --fullscreen`

I can't get this to work with any rom tried.

Let me know if this is just me doing something stupid.

**Comment by SourMesen** [comment]
Thanks for the report! This is something that I broke in 0.9.4 and happened to notice and fix a couple of days ago (33af6caf08aff7d2d7325cddb108f1a2c6328715).

Essentially 0.9.4 incorrectly turns the whole path to lowercase, which means Linux won't be able to find the file.  If the path you give doesn't start with a slash, it should still work, though.  e.g try using this instead:
mono /home/mic/Mesen/Mesen.exe ~/Desktop/nes/project/bin/runngun-2018-02-05.11.23.09.nes

If you build Mesen from the latest commit, it should fix the issue, too.

**Comment by teamdisposable** [comment]
Yep, compiled a fresh copy, all fixed in latest build. Thank you!
