### ISSUE TITLE
no support for mapper iNES #124 (Super Game Mega Type 3 Pirate arcade board)

### ISSUE THREAD

**Issue by iGom** [SourMesen/Mesen#325]
Hi, could you add support for mapper # 124, which is used for Super Game Mega Type 3?

Documentation about it, files, rom etc. can be found in description of this video
https://www.youtube.com/watch?v=re9O388mtJU
http://blog.kevtris.org/blogfiles/Super%20Game%20Mega%20Type%20III.rar

**Comment by SourMesen** [comment]
Thanks for the information & link! I had never heard of this board until now.
It looks pretty complex (it can emulate 3-4 different mappers), so I probably won't be implementing it very soon, though.  I've added it to the list of unsupported mappers in #136 - I'm hoping to get around to implementing most of the missing mappers at some point over the next few months, but I can't make any promises.
