### ISSUE TITLE
[Libretro] .sav and .srm Files?

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen#326]
I notice the Mesen core is creating two save files for battery backed games, one with a .srm extension and one with .sav. Aren't the .sav ones redundant?

**Comment by SourMesen** [comment]
The core creates and reads the .sav file.  I'm guessing the .srm file is something RetroArch does on its own, wasn't aware of its existence.

I'd have to see whether the .srm files are getting properly loaded first, then I guess I can figure out a way to disable the .sav files.  Although it'd be simpler from my point of view if there was a way to disable RetroArch's .srm files.

**Comment by Awakened0** [comment]
I found when I deleted the .sav files it would read the .srms and then create .savs and visa versa. I think when the core first came out it only created .sav files, but I'm not sure when it started making .srms too. 

I don't think it matters which way you pick for saving, since it's just a different file extension AFAIK.

**Comment by SourMesen** [comment]
The .srm files are most likely the result of having added support for retro achievements - it exposes the save ram to retroarch to detect achievements, so RetroArch is probably saving & loading the ram using that, too.

**Comment by retro-wertz** [comment]
.srm are used by retroarch when using the RETRO_MEMORY_SAVE_RAM api and this is used too for retroachievements. although if you are able to use retroarch's retro_memory_map/retro_memory_descriptors to expose RAM, then that would work too. not sure if WRAM is normally enabled in non-battery enabled roms, or how this is done in mesen, but mmap should also expose wram and enable achievements to roms like Metroid which does not have save ram but wram address is used for retroarchievements.

**Comment by fr500** [comment]
If the memory is being read / written directly then the regular I/O based one should be disabled in my opinion.

**Comment by fr500** [comment]
@SourMesen let me know if there are any other special cases I need to handle

**Comment by SourMesen** [comment]
@fr500 Sorry, meant to take a look today but been busy with a number of things. I think the simplest/safest solution would be to add a conditional in BatteryManager::SaveBattery to not save any file if the extension is ".sav" (instead of disabling battery saves for everything but FDS).  This should allow fds/external storage to work properly and stop the .sav files from being created.  (The core will still attempt to load them if it finds one, but that's not really an issue)

**Comment by SourMesen** [comment]
This should be fixed with 8b31493fdac6219f2517f6c6e1a4c55ea0b36348 - .sav files will no longer be created for the libretro core.
