### ISSUE TITLE
Castlevania III - Dracula's Curse bug

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#327]
The bug that is letters "S" and "E" is cropped after you get to the BLK 6-03, and we have "CORE" / "NEMY" instead of **"SCORE" / "ENEMY"**

![akumajou densetsu j _000](https://user-images.githubusercontent.com/21690438/36384404-d4730314-1597-11e8-9772-a599d92f6b6e.png)

And now look & compare how should BLK 6-03 / 6-04 (from 5:22)

https://youtu.be/CToOaLLnnj8

**Comment by dragon2snow** [comment]
this game is Akumajou Densetsu,not Castlenia III - Dracula's Curse?

**Comment by retro-wertz** [comment]
you are playing Akumajou Dracula and comparing to Castlevania III?

anyways, disable side clipping or whatever that option is called in mesen

**Comment by SourMesen** [comment]
It's not the overscan settings since his picture is 256px wide.
But you're comparing Castlevania 3 to Akumajou Densetsu (CV3's Japanese version), which are not the same game.
Took a while to find a video (seems like most videos take other routes): https://www.youtube.com/watch?time_continue=227&v=nZc6Lj7wdXU
I'm not sure if that video was recorded on a console, but it does look like it might have been.
I can't confirm, but I'd be tempted to say this might be the game itself that has a bug?

**Comment by retro-wertz** [comment]
@SourMesen  interesting....
@Arcus87 can you possibly upload savestates of the stages where you think the issue is?

**Comment by cyrilleCh** [comment]
if I remember correctly. CVIII uses a MMC5 mapper which allows it to have a 3rd nametable which is useful on this level "flood" with its vertical scroll raster effect. The water screen uses the 3rd nametable which leaves 2 nametable to do the horizontal scrolling without glitch.
Akumajou uses a Konmai VCR6 mapper which does not allow to have 3 nametable so to make the effect "flood" they are forced to pass the scrolling mode "single-screen" which causes pallet glitch and needs to activate the black band. So I think everything is normal on this level.

**Comment by SourMesen** [comment]
The MMC5 vs VRC6 + cutting off the black border on the left side explanation makes a lot of sense - that's probably what's actually happening here.

It's easy to check this with Mesen's debugger by looking at the "Draw left BG (8px)" checkbox - if it's checked during that scene, this is normal.

**Comment by retro-wertz** [comment]
wait left side? vrc6 always has clipping on the left side of the screen
even with normal overscan clipped. anyways this is probably a no biggie and
is happening to real hardware.

**Comment by SourMesen** [comment]
As far as I'm seeing, the VRC6 version has a 256px wide image with nothing hidden? So clipping the 8px on the left would result in cutting off the SCORE/PLAYER/ENEMY labels, like in the screenshot above.
