### ISSUE TITLE
Castlevania III - Dracula's Curse graphics bug

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#328]
![akumajou densetsu j _001](https://user-images.githubusercontent.com/21690438/36396070-eaf8a6ac-15c4-11e8-8cde-496fd13fd78e.png)

I'm not sure if that happens on real famicom. If this is emulation bug, please take a look on it

**Comment by Arcus87** [comment]
Graphics bug with blocks also in BLK 7-06

**Comment by retro-wertz** [comment]
you should consolidate your reports into a single thread so its easier to track. you already opened similar issue....

**Comment by SourMesen** [comment]
As far as I can tell from gameplay videos, this appears to be the tiles breaking under the character's weight - you can hear a sound effect as the tile changes color.
