### ISSUE TITLE
0.9.4 debugger cannot edit CPU status and flags

### ISSUE THREAD

**Issue by wangsitan** [SourMesen/Mesen#336]
**0.9.4** debugger cannot edit CPU status and flags

How to repoduce:

Break the game, edit CPU status (A/X/Y/PC) or flags (C/Z/N/...), and then try to continue the game, it will fail. The error message (I translated it from Chinese to English) is: 

> System.EntryPointNotFoundException: cannot find entry point "DebugSetState" in "MesenCore.dll".

In an old version, MesenDatach (based on **0.9.3**), which you sent to me, this bug doesn't exist.

Error message:

![debug_set_state](https://user-images.githubusercontent.com/5144551/37249791-1e1835c0-2529-11e8-9d16-ef09c53c7913.png)

**Comment by SourMesen** [comment]
I can't reproduce this on my end.  Are you using a 32-bit version of Windows?
You can also try this recent build: https://www.mesen.ca/MesenMar10.zip to see if it helps (this build contains a lot of debugger-related improvements/changes, too)

**Comment by wangsitan** [comment]
Oh, I forgot to tell you my environment, sorry for that. Yes, I'm using 32-bit Windows7.
I downloaded and tried this recent build, it works fine for me. I think I should close this issue.
By the way, I notice the debugger has been improved a lot, such as I can configure the shortcut-keys. It's becoming more and more awesome. Thank you for your effort =)

**Comment by SourMesen** [comment]
Sometimes the 64-bit version will allow incorrect function definitions to work properly, whereas 32-bit causes a crash.  I almost never test the 32-bit version though, so sometimes I don't notice these right away. Good to know it's fixed, though!

And yea, I've been spending a lot of time improving some things in the debugger - customizable shortcuts are something I finished yesterday, actually.  Let me know if you happen to find anything that's no longer working properly.
