### ISSUE TITLE
OverflowException when attempting to view nonexistent Save RAM or Work RAM in the debugger

### ISSUE THREAD

**Issue by KarolS** [SourMesen/Mesen#337]
Version: 0.9.3 and 0.9.4, downloaded from mesen.ca
OS: Windows 10

Steps to reproduce:
1. Open any ROM without Save RAM or without Work RAM or without both
2. Open Debugger → Tools → Memory Tools
3. From the dropdown, pick Work RAM (if it exists), Save RAM (if it exists) or NES RAM
4. Scroll down to the very end while pondering the utter chaos of random data
5. Switch the dropdown to Save RAM or Work RAM, whichever doesn't exist

Expected behaviour: 
1. Seeing the meditative emptiness of non-existing memory

Actual behaviour:
1. An error pops up and the Memory Tools window becomes unusable until you reopen it

> An unexpected error has occurred.
> Error details:
> System.OverflowException: Wymiary tablicy są poza obsługiwanym zakresem.
>    w Mesen.GUI.InteropEmu.DebugGetMemoryAccessStamps(UInt32 offset, UInt32 length, DebugMemoryType type, MemoryOperationType operationType)
>    w Mesen.GUI.Debugger.ByteColorProvider.Prepare(Int64 firstByteIndex, Int64 lastByteIndex)
>    w Be.Windows.Forms.HexBox.PaintHexAndStringView(Graphics g, Int64 startByte, Int64 endByte)
>    w Be.Windows.Forms.HexBox.OnPaint(PaintEventArgs e)
>    w System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>    w System.Windows.Forms.Control.WmPaint(Message& m)
>    w System.Windows.Forms.Control.WndProc(Message& m)
>    w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SourMesen** [comment]
Thanks for the report - this should already be fixed in the current code (the work/save ram options are no longer shown in the dropdown if the loaded game doesn't have any)
You can try this build: https://www.mesen.ca/MesenMar15-2.zip
It's essentially the same as 0.9.4 but with a lot of debugger improvements and bug fixes.

**Comment by KarolS** [comment]
Looks like it works fine now.

I also checked how the debugger handles the situation when Save RAM and Work RAM have different sizes and both the 0.94 and the version you posted handle that correctly.
