### ISSUE TITLE
Cheats not working

### ISSUE THREAD

**Issue by Inotamira** [SourMesen/Mesen#338]
Unless I'm just really missing something here, cheats simply aren't altering values in the games memory like it should be. I'm specifically trying to alter the rupees value in the first Zelda game, value is at 066D, change it to FF, and the game acts like nothings been done, counter works as normal in the memory viewer, no change is made. Is this something not fully implemented yet?

Edit: Yep, I'm the idiot. Turns out you have to click okay for them to become active. On the flip side however, why shouldn't they modify on the fly like other emulators do? Possibly a feature to add perhaps :P?

**Comment by Inotamira** [comment]
I more mean that once it's typed in and added to the list, it's active, that way you aren't forced to close the list when hunting for values and can see the affect.

**Comment by SourMesen** [comment]
Ah, my bad, I didn't remember you had to press OK on the cheats dialog to apply them, it's been a long time since I built the cheat UI.
In that case, it would make sense to change the behavior I think - I'll take a look when I get a chance.

**Comment by SourMesen** [comment]
Changing any cheat in the cheat list should now automatically apply the changes to the game, without needing to click ok, pressing cancel will revert the changes (89a8b26fa106a69828c9328be4dbd3bd8027c284)
