### ISSUE TITLE
Suggestion: Option to hide non-changing bytes in cheat search

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#339]
Suggestion: An option in the cheat search that detects which bytes in the memory have had any changes made to them - over a period of time chosen by the user. It would then give an option to only show pages with changes or only show pages without changes.

**Comment by SourMesen** [comment]
Isn't it "kind of" possible to do this at the moment by using the "Previous value was" equal/not equal filters? You can also use the debugger's memory tools to highlight bytes that are written/read by the game, too.
At some point, I'd like to create a more complete memory comparison/tracking system, but that would probably be a separate tool from the cheat finder (e.g part of the debug tools)

**Comment by Cibomatto2002** [comment]
Didn't think about using the debugger. Thanks
