### ISSUE TITLE
[Libretro] some retro achievements not unlocking

### ISSUE THREAD

**Issue by zoharxero** [SourMesen/Mesen#341]
Some achievements not unlocking, same problem as nestopia described here:

https://github.com/libretro/docs/pull/10

The morph ball achievement in metroid dosent work.

**Comment by SourMesen** [comment]
Thanks for the report - I'm aware of the issue, it's been on my list of things to get done, but haven't gotten around to it yet.

**Comment by SourMesen** [comment]
With the changes in 82f8676a09a26802a6f97c2f0bd4842bf50a7c11, retroachievements should be working in most games, including Metroid.
