### ISSUE TITLE
Lua interface to Memory Access Counters

### ISSUE THREAD

**Issue by spiiin** [SourMesen/Mesen#342]
It will be very cool, if "Memory Tools -> Access counters" information will be accessible from lua.
With functions like accessCounters.getState(CounterViewType, CounterSortType) and accessCounters.reset() it will be possible to make advanced data-debugging tools. Very simple use case for that - script to showing what ROM bytes was used to draw PPU name table part.

**Comment by SourMesen** [comment]
Thanks for the request!

I've added emu.getAccessCounters(memtype, operationtype) and emu.resetAccessCounters().  There is no sorting (since the C++ does not support this, the UI is doing the sorting), but you can easily do the sort in Lua if you need it.
