### ISSUE TITLE
Hide zero values option in Memory Access Counters

### ISSUE THREAD

**Issue by spiiin** [SourMesen/Mesen#343]
It will be useful option for show only non-zero values of counters in Memory Access Counters for sorting by addresses, but hiding not needed values. Also, values in table can't be copied now (I'm trying to press ctrl+A for select, ctrl+C for copy on Windows version, but copy doesn't work), so user even can't do this filtering with external scripts.

**Comment by SourMesen** [comment]
Thanks for the request!

I've added an option to hide unused addresses (no reads/writes/exec) in the UI in 37c633da14530915448a5d0c3b247b18151e3290
Select All/Copy shortcuts (right-click) were added in bf2e733cc372f94fad2fb9958a189001eb69aab8
