### ISSUE TITLE
Cannot run under Linux Mint

### ISSUE THREAD

**Issue by andre-paris** [SourMesen/Mesen#344]
Hi, 

I can't run Mesen 0.9.4 under Linux Mint 17.3 with mono 5.10.1.4
I've attached the stacktrace:
[stacktrace.txt](https://github.com/SourMesen/Mesen/files/1857026/stacktrace.txt)

**Comment by SourMesen** [comment]
Did you build the version yourself, or is this the version released on GitHub/the website?
It appears to be crashing in GetMesenVersion(), which is a function in the C++ core (libMesenCore.dll) that returns a constant value, so it's not something I would ever expect to fail.

**Comment by andre-paris** [comment]
It's downloaded from the site: https://www.mesen.ca/#Downloads

**Comment by SourMesen** [comment]
You may need to build Mesen yourself to get it to work properly on that version of Linux Mint.
I tried Mint 17.3, but it required manually updating mono, gcc and/or clang, etc - I gave up before I managed to get it to build (and the prebuilt version did not run).

On the other hand, Mint 18.3 worked fine - installing mono-complete and libsdl2-2.0.0 was all I needed to get the prebuilt version to launch.  (This was with Mono 4.2.1)

**Comment by retro-wertz** [comment]
mesen under linux should work fine if you do compile it your self. i have
mint as backup OS or when i needed somethings thats bases on LTS release of
linux (older, stable files etc)
