### ISSUE TITLE
First line of text is broken in Taro's Quest. 

### ISSUE THREAD

**Issue by kurayami6** [SourMesen/Mesen#345]
Taro's Quest is the unreleased English version of Jajamaru Ninpou Chou. 

![capture](https://user-images.githubusercontent.com/31968468/38143688-6b4403ba-348d-11e8-9014-e3c656e924fa.PNG)

The text after that is fine.

![capture2](https://user-images.githubusercontent.com/31968468/38143701-7a2a2486-348d-11e8-824f-c3e3babcde95.PNG)

The issue is not present in Jajamaru Ninpou Chou.

![capture3](https://user-images.githubusercontent.com/31968468/38143725-9b4ece50-348d-11e8-87dc-de01c6fac412.PNG)

**Comment by SourMesen** [comment]
Thanks for the report! This was an issue with the game database entry for this game (fixed by d3c5074b245ba88674cf0948f9224cf11b3c54f8).  You should be able to make it work properly on your end by disabling the game database in the preferences window.
