### ISSUE TITLE
Audio latency issue

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#360]
![latency](https://user-images.githubusercontent.com/13199529/38410604-b20c5612-398d-11e8-8a56-ddddace837fd.png)

1) If you set latency to 100ms there is warning message appears
2) If you try to set latency manually (via keyboard) - it always reset to 15ms

**Comment by SourMesen** [comment]
Thanks! Both of these should be fixed by 2dc0a9024079ac9df58fafbbabe596affb79f4eb
