### ISSUE TITLE
Request: Display "F11 to exit Fullscreen" on the Pause screen

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#368]
In all Fullscreen display modes, the Pause screen that appears when pressing Escape should display a message like "Press F11 to exit Fullscreen" since Escape pauses the program.

**Comment by SourMesen** [comment]
Thanks for the suggestion - a5756aabbee1708c18a2cd31890c04dd0f18b0bf adds a message to the bottom right of the screen when in fullscreen & paused.
