### ISSUE TITLE
Somari is not working?

### ISSUE THREAD

**Issue by Sun-in-jang** [SourMesen/Mesen#369]
I found your emulator is best than others like fceux / nestopia, but it's doesn't launching Somari.

**Comment by kurayami6** [comment]
Works fine for me. 

![capture](https://user-images.githubusercontent.com/31968468/38769064-4a5afd2a-4040-11e8-9dc3-0a94d3d4dd52.PNG)

**Comment by Sun-in-jang** [comment]
**Somari (SOMARI-P) (NT-616) (Unl) [!]**

**Somari (SOMARI-W) (Unl) [!]**

those two roms not working. **Somari (Unl) [p1]** and **Somari (Unl) [p2]** works fine. This two roms have same UNIF-board / mapper?

**Comment by SourMesen** [comment]
Those roms are mapper 116, which is not supported yet.  Unsupported mappers are listed here: #136

**Comment by Sun-in-jang** [comment]
This is strange.

Somari (Unl) [p1].nes  >> Mapper: 4 (Mirroring: Horizontal)
Somari (Unl) [p2].nes >> Mapper: 4 (Mirroring: Vertical)

Somari (SOMARI-P) (NT-616) (Unl) [!].nes >> Mapper: 4 (Mirroring: Horizontal) doesn't work
Somari (SOMARI-W) (Unl) [!].nes >> Mapper: 116 (Mirroring: Horizontal) doesn't work

**Comment by SourMesen** [comment]
Somari (SOMARI-P) (NT-616) has a bad header - it's not mapper 4, and gets changed to mapper 116 by the game database.  Disabling the game database and attempting to load it as mapper 4 results in a green screen.

**Comment by Sun-in-jang** [comment]
Hope you will add all mappers and UNIF-boards one day, and got fixed all database :) Will be watching on Mesen, i like it very much
