### ISSUE TITLE
Tom & Jerry (and Tuffy) issue

### ISSUE THREAD

**Issue by Sun-in-jang** [SourMesen/Mesen#370]
![tom jerry and tuffy u _000](https://user-images.githubusercontent.com/38378342/38769812-abc28576-4011-11e8-890f-fa10779fe8e1.png)

Game bug or its emulation issue. Rom file from GoodNES V3.23b

When you ending level and it's counting score for every 50,000 pts = 1 UP = this bug happens. Doesn't happening in the Japan version, which is marked with " [!] " for unknown reasons, while the USA version marked with it.

**Comment by SourMesen** [comment]
I was able to reproduce the problem, but this is very likely to be a bug in the game itself.  It only occurs when you get a multiple of 50k thanks to the bonus points gained at the end of the level.  Triggering this normally is pretty unlikely, so it's possible this is a lesser known bug with the game.  I have been unable to find any video that matches the conditions needed to trigger the bug - unless you have proof that this bug doesn't happen on a real NES console (or if the bug doesn't occur in other emulators), I would assume that the game itself is bugged.
