### ISSUE TITLE
"LAGFIX" fast-forwards through "hidden" frames for near-instant response times.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#372]
Better than reality: New emulation tech lags less than original consoles
"LAGFIX" fast-forwards through "hidden" frames for near-instant response times.

We've previously written about how difficult it is to perfectly emulate classic video game consoles even with powerful modern computer hardware. Now, the coders behind the popular RetroArch multi-emulator frontend are working to make their emulation better than perfect, in a way, by removing some of the input latency that was inherent in original retro gaming hardware.

Read more from here.

https://arstechnica.com/gaming/2018/04/better-than-reality-new-emulation-tech-lags-less-than-original-consoles/

**Comment by retro-wertz** [comment]
yeah right. lets forget about accuracy and just incorporate hacks...

**Comment by kurayami6** [comment]
This reads like a copy pasted spam advertisement. Which I'm sure is against Github's rules.
