### ISSUE TITLE
Add "RAW" palette for libretro-core

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#373]
Hi, Sour!
Can you add RAW palette to the mesen libretro core, like nestopia have?

It need for shaders like this:

https://forums.libretro.com/t/add-nes-pal-composite-signal-simulation-shader-to-retroarch-package/15848

https://github.com/libretro/RetroArch/issues/6647

**Comment by SourMesen** [comment]
Hey,

Thanks for the suggestion - it shouldn't be too hard to add.  I'll take a look when I get a chance in the next few days.

**Comment by SourMesen** [comment]
This should be available as of a086acde87cb4d4bab78675bf9e5da63d68b7451 (should be in the next build the buildbot makes).  I added it as a "Raw" option in the palette selector.

It should be identical to Nestopia's core's behavior, hopefully.  Let me know if you have any issues with it!
