### ISSUE TITLE
Add "ANTOSA" Game Genie code to database for Super Mario Bros and some multi game cartridges containing SMB

### ISSUE THREAD

**Issue by chexo3** [SourMesen/Mesen#375]
Causes pipes to render upside down if they don't lead to a warp zone.

Tested and working as intended 1-1 for:
Super Mario Bros (U)
Super Mario Bros + Duck Hunt (U)

No effect for Super Mario Bros + Duck Hunt + Track Meet (U)
Causes running out of time/fast music on Super Mario + Tetris + World Cup (E)

**Comment by SourMesen** [comment]
Thanks for the suggestion - I don't really intend to add extra codes to the database, though.  The codes included in Mesen were downloaded from another source on the internet (can't quite remember which).  Players can easily manually add any cheat they want, and trying to maintain a cheat database on top of everything else isn't really something I want to do.
