### ISSUE TITLE
Mesen not reporting correct hz in PAL mode

### ISSUE THREAD

**Issue by retrorepair** [SourMesen/Mesen#377]
It seems the screen refresh is only being reported as 60hz regardless of pal or ntsc mode. This is a problem for retroarches new CRT mode as it will only ever output as an ntsc resolution, even when a PAL game is loaded.

**Comment by SourMesen** [comment]
What is making you say that it's being reported as 60hz?  PAL mode plays at 50fps, and as far as I can tell, everything seems to be correct, code-wise.  If by resolution you mean aspect ratio, this should be configurable by the aspect ratio option (which has an Auto option to switch between NTSC & PAL ratios)

**Comment by retrorepair** [comment]
Apparently I was mistaken, it looked like it would only ever report 60hz but it is definitely working as expected now! Sorry for wasting your time!

**Comment by retrorepair** [comment]
It would actually seem that the confusion stemmed from using a "(World)" rom with the PAL setting enabled which did not give a PAL video output. Not sure if this behaviour is intentional? I would have thought it would override the filename tag?

**Comment by SourMesen** [comment]
Which setting are you talking about when you say the "PAL setting"? Do you mean the "Region" setting is set to "PAL" in the Mesen core's options?
If it's a setting inside the game itself, there is no way for the core to know about this - you'll still need to set the region to PAL manually in Mesen's settings.  Most (World) roms most likely run as NTSC when the region is set to "Auto"

**Comment by retrorepair** [comment]
Yes I'm referring to the region setting in mesen's options in retroarch.

Auto does indeed invariably (always?) Choose NTSC for World roms but it seems choosing PAL does too.

I'll double check this tomorrow and report back.

**Comment by retrorepair** [comment]
Well it's doing what it should so no idea what happened there. Sorry, will make sure 100% before opening another issue!

**Comment by SourMesen** [comment]
No problem - thanks for taking the time to retest it!
