### ISSUE TITLE
Debugger crash

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#38]
The Debugger will crash on any game. Just load the game then select debugger.

![capture9-7-2016-2 36 40 am](https://cloud.githubusercontent.com/assets/21169038/18305285/12d4a6c6-74a4-11e6-9fc6-f7a216258d3a.jpg)

**Comment by SourMesen** [comment]
Thanks for the bug report.

This should be fixed by bab9296

**Comment by SourMesen** [comment]
Should be fixed in 0.5.1 - let me know if you still get a crash

**Comment by Cibomatto2002** [comment]
It works now thanks.
 

    On Wednesday, September 7, 2016 7:22 PM, SourMesen <notifications@github.com> wrote:
 

 Should be fixed in 0.5.1 - let me know if you still get a crash—
