### ISSUE TITLE
A better rom format.

### ISSUE THREAD

**Issue by chexo3** [SourMesen/Mesen#381]
I feel like for a NES emulator focusing on accuracy we need a better way to represent roms. 

The idea I had was that you could use a hardware description language, and an efficient simulator for it. The rom image could include, instead of a reference to a specific hardcoded mapper, refer to a mapper with a specific checksum, stored as an HDL file. This could be stored separately, in a mappers folder, or be included in the rom file.

**Comment by SourMesen** [comment]
Thanks for the suggestion.
While not necessarily a bad idea in theory, there are a number of reasons why this isn't really practical.
For one, there are already over 20k different .nes ROMs in circulation - these are never going to go away and will still need to be supported (so creating another format for ROMs just adds more burden on emulator authors).
Beyond this, most NES emulators are no longer actively developed, so odds are none of them would support this (which would destroy any chance of such a format ever gaining popularity).
And then there's also the fact that you wouldn't actually gain any actual accuracy out of doing this (but performance would certainly be reduced), and it would probably be a lot harder to integrate this into an emulator vs just writing regular code to describe the mapper.
