### ISSUE TITLE
Problem of resize in palette select color window

### ISSUE THREAD

**Issue by hksy** [SourMesen/Mesen#385]
パレット選択ウィンドウ（および映像設定ウィンドウのパレット編集）について気になる点を報告します。

ウィンドウのサイズを変更、最大化してもパレットのPictureBoxがサイズを正しく追従しません（幅は変更されず、高さは縮小だけは追従しています）。

また、ウィンドウサイズを変更しPictureBoxの高さを狭めているときにクリックすると、
クリックした位置のパレット色ではなく、ウィンドウサイズ変更前の位置にあったパレット色を取得しています。

https://github.com/SourMesen/Mesen/blob/fe8125e58db83f2365fafc14c13a911f1f48a692/GUI.NET/Debugger/ctrlPaletteDisplay.cs#L104
ここのクリック位置検出にて、PictureBoxに設定されている元のBitmapのサイズを参照しており、
実際に表示されているサイズ（picPalette.Height）とは異なる値を使用しているためだと思われます。

Windows7の場合、picPaletteの初期サイズが338x311と正方形になっていないため、
初期状態でもクリック位置検出にズレが発生しており、0x38-0x3Fの行が特に選択しづらくなっています。

**Comment by SourMesen** [comment]
バグ報告、ありがとうございます！
hksyさんが思っていたようにpicPalette.Image.Height/Widthの所が原因です。
WindowsのDPI設定が100％なら問題ないのですが、125％以上にするとバグが発生します。 
483fd3f128a0025dcae371e129b414e884a121b2 で直しました。
その上、ウィンドウのサイズを変更するのは不可能にしましたので、そっちも直しているはずです。
