### ISSUE TITLE
Shortcut Keys Request

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#39]
Are you going to add more Shortcut keys later? Like the - and + it would be nice to map that to the gamepad so I could slow or speed up the game.

**Comment by SourMesen** [comment]
Added increase/decrease speed shortcut actions in 477f663

**Comment by Cibomatto2002** [comment]
Thank you.
 

    On Sunday, September 11, 2016 6:30 AM, SourMesen <notifications@github.com> wrote:
 

 Added increase/decrease speed shortcut actions in 477f663—
