### ISSUE TITLE
Add to Watch shortcut in Memory Tools causes an error

### ISSUE THREAD

**Issue by krozett** [SourMesen/Mesen#394]
I can enter watch values manually in the Debugger, but if I right-click on a location in the Memory Tools and click "Add to Watch", I always get this error:

![mesen memory watch](https://user-images.githubusercontent.com/1661295/40764566-70cafe78-645e-11e8-9153-37832ee61676.png)

It happens on both Windows and Linux.

**Comment by SourMesen** [comment]
Thanks for the bug report!
This is fixed by ab8af4693a6aa96466088c59176468d567cf8ee1
