### ISSUE TITLE
Translation Support 

### ISSUE THREAD

**Issue by L1cardo** [SourMesen/Mesen#395]
I want to translate Mesen into Chinese , but I don't know how to do . Can you tell me where the user interface text is? I may do something about translation.

**Comment by SourMesen** [comment]
Hey, thanks for the offer!

There are mainly 2 files that need to be translated to add a new language:
[GUI.NET/Dependencies/resources.en.xml](https://github.com/SourMesen/Mesen/blob/master/GUI.NET/Dependencies/resources.en.xml)
[Core/MessageManager.cpp](https://github.com/SourMesen/Mesen/blob/master/Core/MessageManager.cpp)

For MessageManager, you only need to translate the parts that begin with "u8", between lines 8 and 79 in the file.

For resources.en.xml, you need to translate the "Title" tags and the content of each tag.  e.g, the words "Preferences" and "General" in this example:
```
<Form ID="[...]" Title="Preferences">
  <Control ID="[...]">General</Control>
```

If you can give me the translation for those 2 files, I can take care of the little bit of coding that is required to add the language to the language selection dropdown, too.

Let me know if you have any other questions.

**Comment by L1cardo** [comment]
OK. I will do my best to translate these 2 files , but it will take some time .

**Comment by SourMesen** [comment]
No problem, take as much time as you need!  Let me know if you need help with anything

**Comment by L1cardo** [comment]
Hi!
Finally I have finished the Chinese translation for Mesen .
Please check it and let me know if there is any error.
[Mesen Chinese translation.zip](https://github.com/SourMesen/Mesen/files/2274491/Mesen.Chinese.translation.zip)

**Comment by SourMesen** [comment]
Thanks a lot!  I've integrated your translation in the code and the latest Appveyor build has it, you can try it here: https://ci.appveyor.com/api/buildjobs/nb862k20w1idix2k/artifacts/MesenDevWin-0.9.6.7.exe

Feel free to open another pull request if you notice anything that needs to be fixed.
Thanks again for taking the time to do this!
