### ISSUE TITLE
Full screen mode in Hogan's Alley and Duck Hunt

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#40]
How can I shoot off screen in full screen mode? I can do it in window mode but not full screen.

**Comment by SourMesen** [comment]
You should technically be able to shoot offscreen by clicking in the black area around the game's picture.
Also, if you hold the mouse's right button down and left click on the game's picture, it will count as shooting off screen.

**Comment by Cibomatto2002** [comment]
I did not know that. there needs to be a guide for this emulator.

**Comment by Cibomatto2002** [comment]
I did not know that. there needs to be a guide for this emulator. 

    On Saturday, September 10, 2016 3:01 PM, SourMesen <notifications@github.com> wrote:
 

 Closed #40.—

**Comment by SourMesen** [comment]
I do plan on writing a guide eventually, but it would take a fair amount of time, and currently new features are added and changes are being done so often that I would need to update the guide constantly, which would slow down development.

**Comment by Cibomatto2002** [comment]
That's true I enjoy all you do for the Emulator sometimes I fill like i ask much from you.
 

    On Sunday, September 11, 2016 5:49 AM, SourMesen <notifications@github.com> wrote:
 

 I do plan on writing a guide eventually, but it would take a fair amount of time, and currently new features are added and changes are being done so often that I would need to update the guide constantly, which would slow down development.—
