### ISSUE TITLE
the sound have problem under switching the region function"auto"

### ISSUE THREAD

**Issue by zkdpower** [SourMesen/Mesen#401]
for instance,i play the game"guardian legend,(the europe)"，meanwhile the region default setting is "auto"，if i power off the game and switch to others,then i change back,the background sound error(blemish) occuing,i notice that "guardian legend,(the europe)'s region is "PAL",and others is "NTSC",if i loading the state between "PAL"and "NTSC",the sound will occur error,strictly called "nonsynchronous blemish".

**Comment by SourMesen** [comment]
Thanks for the report - this is fixed by 44ca91adb13cb1b9163e813d075115dbb57654c7
