### ISSUE TITLE
fatal error: 'string' file not found

### ISSUE THREAD

**Issue by BasicRoom** [SourMesen/Mesen#402]
When using the make command to build Mesen from source in Linux mint (Ubuntu 16)  i get this error:

`mkdir -p Utilities/obj.x64 && cd Utilities/obj.x64 && clang++ -fPIC -Wall --std=c++14 -O3  -Wno-parentheses -Wno-switch -m64 -c  ../AviWriter.cpp
In file included from ../AviWriter.cpp:22:
../stdafx.h:3:10: fatal error: 'string' file not found
#include <string>
         ^
1 error generated.
makefile:122: recipe for target 'Utilities/obj.x64/AviWriter.o' failed
make: *** [Utilities/obj.x64/AviWriter.o] Error 1
`

Am i doing anything wrong?

**Comment by SourMesen** [comment]
Usually this is because g++ is not installed.
You can try installing it w/ apt-get, e.g:
```sudo apt-get install g++```

You can also try installing ```libc++-dev``` if installing g++ doesn't solve it.

**Comment by retro-wertz** [comment]
apt-get build-essential

should take care of the basic compiling needs.


not sure if Mesen is on ppa, but

apt-get build-dep Mesen (or mesen if thats the name used)

should be able to get dependencies needed to compile, in this case Mesen

**Comment by BasicRoom** [comment]
> sudo apt-get install g++. You can also try installing libc++-dev if installing g++ doesn't solve it.

I seem to have both the files and the newest version because that is the message i get when i try to install them. 

> apt-get build-essential. should take care of the basic compiling needs.

I then get: `E: Invalid operation build-essentials`

> apt-get build-dep Mesen (or mesen if thats the name used)

then i get `E: Unable to find a source package for Mesen` With both Mesen and mesen

**Comment by SourMesen** [comment]
Your clang installation is probably broken somehow - I'm not really much of a Linux expert though, so I can't really offer much advice.

If you're using the latest commit, you can try running ```USE_GCC=true make``` to compile with GCC instead.  ```LTO=true USE_GCC=true make``` will compile with LTO which gives a decent performance boost, too.  But keep in mind that GCC tends to produce slower code than clang (as far as Mesen goes), so if you can get it to compile w/ GCC, you might still want to try to figure out what is wrong with your clang installation.

**Comment by BasicRoom** [comment]
> If you're using the latest commit, you can try running USE_GCC=true make to compile with GCC instead. LTO=true USE_GCC=true make will compile with LTO which gives a decent performance boost, too. But keep in mind that GCC tends to produce slower code than clang (as far as Mesen goes), so if you can get it to compile w/ GCC, you might still want to try to figure out what is wrong with your clang installation.

Yeah. That made it work!

Trying to install clang does not return any error just says that i already have the latest version. I might just try to reinstall it or something. 

> Edit: Mesen is not on PPA, so it's normal for it to complain that it can't find the package.

Alright good to know. 

Well then i can mark it as solved. And hope i at some other time get to fix clang. 

Thanks for the help!
