### ISSUE TITLE
Option to reduce input lag

### ISSUE THREAD

**Issue by Sun-in-jang** [SourMesen/Mesen#405]
I'm not sure, but does Mesen have this one? If no, then can you add it? Nestopia / fceux / puNES don't have option, your emulator might be first

**Comment by SourMesen** [comment]
Thanks for the suggestion - I'm aware of a few different techniques used to reduce input lag. I may get around to implementing one or more of them eventually, but it probably won't happen soon.  If you need very low input lag, you are probably better off trying to use RetroArch (either the Mesen core or any other NES core)
