### ISSUE TITLE
[Libretro] Sound Regression (Warbles and Pops?)

### ISSUE THREAD

**Issue by Awakened0** [SourMesen/Mesen#408]
I grabbed the latest win64 nightly off the buildbot (dated 2018-06-17 13:05) and compared it to the core I was using before (dated 2018-04-18). There are little warbles and pops at the end of most notes in the main theme of Zelda 1 in the latest core. The older one sounds nice and smooth. Unfortunately I don't know what commit the older build is based off, just the date on the .dll file. I'll attach the old win64 build here if someone wants to test it against the latest:

[mesen_libretro.zip](https://github.com/SourMesen/Mesen/files/2109562/mesen_libretro.zip)

**Comment by SourMesen** [comment]
Thanks for the report! I'm pretty sure I know what's causing it.  I improved the sound system for the standalone build, which makes it vary the output sample rate to keep in sync with the video better than before - but I think a portion of my changes is also being applied to the libretro core, which will definitely cause issues.  It should be an easy fix.

**Comment by SourMesen** [comment]
This should be fixed by e18fab05574e316ab99a219cf39efc38d86c5079 - the next build the buildbot makes should contain the fix.  Please let me know if it sounds like it used to on your end once you test the build.

**Comment by Awakened0** [comment]
The buildbot just put up a new build. I tested it with Zelda 1 and a few other games and everything sounds good. Thanks!
