### ISSUE TITLE
Cutted screen on big resolutions [win10]

### ISSUE THREAD

**Issue by eq-soft** [SourMesen/Mesen#409]
It seems that there is some restriction for screen height:
![2](https://user-images.githubusercontent.com/40371185/41562626-e087e37e-7355-11e8-9f8e-d727bd3c9e3f.png)

It reproducing in windowed mode and independent from filters. When some screen height reached it starting to cut the video.

Mesen 0.9.5, Windows 10, 3200x1800 (scale 250%, but it reproducing with 100% too), Intel HD Graphics

**Comment by SourMesen** [comment]
Thanks for the report - this is a bug in 0.9.5 that was fixed a few weeks ago (see #312).  You should be able to use the build posted there (or use one of the appveyor builds - linked in the readme) to fix the issue on your end.

**Comment by eq-soft** [comment]
Sorry for duplicate, thank you!
