### ISSUE TITLE
(enhancement) individual channel panning

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#41]
Since MESEN is one of most-advanced NES emulators related to of APU/effects, i have an request:

Can you add channel panning mixer like did in many NSF-players?
NSFplay for example: 
http://savepic.su/7456580.png

**Comment by SourMesen** [comment]
Sorry for the long wait!
Channel panning has been added in e24514781fb0a449303c54a20780bcf26ca4c1da
Note that it doesn't offer as many options as NSFplay (i.e you can't pan each channel of the VRC7 individually, etc.) and activating the fake stereo modes will have the side-effect of ignoring all the panning options.

**Comment by Nicholas-Steel** [comment]
Currently there is no individual channel panning for the Special Audio Chips like VRC 6, VRC 7 etc.

**Comment by SourMesen** [comment]
Yes, this is by design for now - adding panning to each channel of the audio chips would have required a lot more changes.  I'll probably add panning for them at a later date, though.
