### ISSUE TITLE
compiling for non x86_64/i386 linux

### ISSUE THREAD

**Issue by wyatt8740** [SourMesen/Mesen#410]
This is more of a question than anything, but how does one need to change the makefile to build for 32 bit powerpc?
(this is mostly for experimental reasons.)
the MESENPLATFORM variable settings of x86 and x64 are both obviously inaccurate here.

**Comment by wyatt8740** [comment]
Update: tried compiling it with 'x86' and it failed on what appears to be a modified file from DirectX(?!?) for linux.
(SpriteFont.h includes xmmintrin.h, which is Intel-specific.)
IMO It's a pretty big drag if it's not portable just because someone decided to retrofit DirectX headers instead of using an open standard. Is there some way around needing this header/code? Or is it 'intrinsic' (if you'll pardon the SSE pun)?

**Comment by SourMesen** [comment]
This was done for the sake of simplicity when I made the Linux port vs having to change a bunch of stuff (and/or add more dependencies) just to display some text on the screen.  The code is ported from DirectX TK, but it is extremely stripped down and only contains the bare minimum to load and display a .spritefont font.  The intrinsic usage is limited to a couple of tiny functions and can easily be removed if there is a need to.

But the real question is, what platform are you trying to compile for exactly?  The only PowerPCs that I can think of that would run in an environment where Mono's WinForms is available/usable would be very old macs?

**Comment by SourMesen** [comment]
I took a few minutes to strip out xmmintrin.h usage from the code, so there should be no CPU-specific code left in the codebase (106c3c908a03103cd5a5a826561308b06b9549d0)

As for how to compile for PowerPC, though, I can't really help much - typically, there are switches available in gcc/clang to select the target platform.  If you are building from a PowerPC machine, you might just need to remove the -m32 / -m64 switches from the makefile to make it target PowerPC.

**Comment by SourMesen** [comment]
Closing this for now since there's nothing more I can do on my end right now.  Also, if you're trying to run this on an old PowerBook, odds are that it might not be powerful enough to run Mesen at 60fps.  And if Mono is causing you problems, you might have better luck trying to build the libretro core and testing that instead.

**Comment by wyatt8740** [comment]
It's not powerful enough. I'm almost certain of that. But I wanted to "see if it could be done." I guess Mono's regressed a great deal since it started trying to incorporate MS's .net core in terms of big endian support.
