### ISSUE TITLE
Undo Load State

### ISSUE THREAD

**Issue by Lululalu** [SourMesen/Mesen#411]
Can you add an option to undo load state? Sometimes you can end up loading the wrong save state by mistake.

Thanks.

**Comment by SourMesen** [comment]
You can actually already do this by rewinding - the rewind feature will undo the load state as well.

**Comment by SourMesen** [comment]
I've added a note in the documentation about being able to use the rewind button to undo a load state action.  I don't think there's a specific need for an "undo load state" button when it can be achieved w/ the rewind button already? I'm closing this for now, if enough people request this I could probably add a shortcut in the "shortcut keys" tab for this (though that would also require code to actually be able to undo a load state, without relying on the rewinder, so I'd prefer to avoid having to do so)
