### ISSUE TITLE
Problem with Name Table displaying other tiles instead of the right ones

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#414]
Hi , Thanks for this awesome Emulator.

I would like to share this problem ( which I don't understand if it's from the Mesen or anything else ).

When I load a rom , opens the PPU Viewer > Name Table

Tiles are displayed wrong ( Displays other tiles randomly )

But when I open it in FCEUX it works

The problem is in two as I understood

1- FCEUX loads almost Tiles , but not all of them. Mesen loads tiles that FCEUX doesn't load and vice versa.

2- The problem doesn't always occur , sometimes it gets back to work ( without doing anything ).

**Comment by SourMesen** [comment]
Games often change the CHR banks during mid-frame.  The nametable viewer displays the contents of memory like it was at the specified scanline & cycle at the bottom of the window. Try changing the "scanline" value and you should be able to display the tiles the way you want them.

**Comment by raousoft** [comment]
Works like a charm :)

**Comment by raousoft** [comment]
Works like a charm :)

**Comment by raousoft** [comment]
Works like a charm :)
