### ISSUE TITLE
Mapper 180 is not working

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#417]
Hi , thanks for the amazing yet surprising Emulator dear Sour.
..

- I tried loading the game: **Crazy Climber (J)**
Which uses Mapper 180 , and Crazy Climber Controller ( can't find it on Mesen )

- The game displays green color background , with no info about it , no CHR viewer , no debug assembly code , nothing , I tried the rom from several sources ( and which they all work on FCEUX ).

Hope I find something about it , that's all what I found :
[180.txt](https://github.com/SourMesen/Mesen/files/2131308/180.txt)

**Comment by raousoft** [comment]
This is the log
------------------------------------------------------
Loading rom: Crazy Climber (J).nes
File CRC32: 0x738881A7
PRG+CHR CRC32: 0xC68363F6
[iNes] Mapper: 180 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 0 KB
[iNes] CHR RAM: 8 KB
[iNes] Mirroring: Vertical
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 180  Sub: 0
[DB] System : Famicom
[DB] Board: HVC-UNROM+74HC08
[DB] Mirroring: Horizontal
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 0 KB
[DB] CHR RAM: 8 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[DB] Input: 2 standard controllers connected

**Comment by raousoft** [comment]
Problem was because I used the dev build MesenDevWin-0.9.5.129.exe
Problem solved : runs on stable build

**Comment by SourMesen** [comment]
Thanks for the report!
This is actually a real bug caused by a change I did a couple of months ago.  It should be fixed by 982302fa15d47e3e8725fc9a4de2f5e71965d409
