### ISSUE TITLE
Two requests for this great emulator :P (Volume slider for Turbo & Rewind / Window Locking)

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#420]
Firstly, would it be possible to add a volume slider for turbo/rewinding? Basically there's a Master and all the various channels, but I'd like to have it be even quieter for when turbo is on, here's a screen shot of Bizhawk for example.

https://i.imgur.com/BvQ3XYR.png

Secondly, could an option be put in that locks the window size from your mouse cursor from accidentally dragging it and changing the size of it, basically to disable the ability to drag the window borders with the cursor.

https://i.imgur.com/9Eu6k0T.png

**Comment by SourMesen** [comment]
For your first request, would a "Reduce volume when rewinding/fast-forwarding" option (and have it around the same volume as the "Reduce volume when in the background" option) be good enough?  I'm just trying to avoid adding a 13th (!) volume slider unless it's really necessary.

**Comment by ImSpecial** [comment]
I'm not sure what "Reduce volume when in the background" is or what it sets at, because mine pauses when it's in the background, for the record I have my PC speakers quite loud, so I keep Mesen's master volume at around 40%, I'm not sure what I'd set the turbo sound too, but my guess would be half that so around 20%, honestly it's just one more slider. :P

**Comment by SourMesen** [comment]
These are implemented by fcaea65100de7a7b9a428d29f3e5ee9afe4566ab and d10b11f0b3cba54ceade76b1b76a28ac491bc7b8

The window resize option is in Preferences -> Advanced, the volume reduction option I combined with the existing reduce volume in background option and added a "volume reduction" slider to choose how much the volume is reduced - they're in the general tab in audio settings.

An appveyor build with the changes should be available in a few minutes.

**Comment by ImSpecial** [comment]
Very cool and thank you. You made adding those look easy, I'll have to come up with something more tough next time.

I'll give the appveyor build a test run later and so if you don't hear back from me it's because everything's all good.

**Comment by SourMesen** [comment]
Thanks for testing! That bug should be fixed in ee2a3aedc498516669135173b98ab169c454bf5f
