### ISSUE TITLE
De-dithering

### ISSUE THREAD

**Issue by Lululalu** [SourMesen/Mesen#422]
Can you add a de-dithering filter that can be combined with other filters and shaders to Mesen?
Several old games are better played with it.
![b5dd5d3](https://user-images.githubusercontent.com/32398857/42050128-7c10e982-7ade-11e8-80a5-c921dbcb41d2.png)

Thank you.

**Comment by SourMesen** [comment]
Closing this since it's part of the roadmap (support for shaders in general) - there is no ETA for this though.
