### ISSUE TITLE
a question about the name mesen

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#426]
Hi , Dear Sour , thank you for the efforts bringing to us the best actual Nes emulator according to me.

I'd  like to apologize also for the amount of issues stealing your time , but we really need you

I want to start translating the emulator to Arabic , I already understood what files to translate and the other things like ( translate what between tag ID and so on ... ).

But I already have to know what does MESEN mean ?

and Out of subject little bit , the icon that looks like an eye , what does it says ? I really and honestly like it's design ( the choose of colors ) but I don't like it being an eye , but that would be selfish of me to say to change it , but I really hope to improve it to something better.

Thank you a lot !

**Comment by SourMesen** [comment]
The name is actually kinda linked to the eye icon.  But the eye icon itself isn't that great, so if someone comes up with something better/less creepy that still fits the name, I'm happy to change it.

Essentially, Mesen's name comes from 2 things:
-It's "NES EMulator", backwards -> Mesen
-It's the Japanese word used to talk about a person's gaze or point of view (目線 - めせん - Mesen), which is the reason why the logo is an eye icon.

**Comment by raousoft** [comment]
I really knew that it's nes backward , and even taught about if it was a snes version it will be Mesens LOL XD.

Aha now it makes sense ,
