### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#427]
I don't know how to pull request for the two files for Arabic translation 

first it's an incomplete translation for now ( until I see how does it looks ) , because of the 1% that indicates the number of cheats for example or what file is loaded , in Arabic it can be in the first of the translation if it's done incorrectly.

Here are the two files.
[MessageManager.cpp+resources.ar.xml.zip](https://github.com/SourMesen/Mesen/files/2150430/MessageManager.cpp.resources.ar.xml.zip)

sorry again I really don't know how to pull request .

**Comment by Lululalu** [comment]
Does Mesen support RTL languages? Just curious about it.

**Comment by SourMesen** [comment]
Thanks! Don't worry about the pull request, I can integrate the code as needed.

WinForms supports RTL natively, and it seems to mostly work (I'm actually impressed that it does, but won't complain!):
![arabic](https://user-images.githubusercontent.com/21093973/42113484-6b5db4fe-7bb9-11e8-9996-d5ac23da646f.png)

The text seems to be displaying properly, I think?  (I know nothing of Arabic, so I can't really tell).
There's a tiny issue with the OSD (e.g the game loaded message at the bottom) that I need to fix before I can commit this, but other than that it seems to be working fine so far.

**Comment by raousoft** [comment]
for the menu , or let's say in general , the win form ( which is based on .NET ) will work as it is in the picture. And I was sure that the OSD will not show them properly , I will send another file which contain a converted arabic text with our tools which we use in softwares that doesn't support this kind of languages , as 3D software like 3ds max and blender ...etc etc

anyway , I will update the file that contain the text in the OSD ( for me I still can read it ) , it's for Game loaded , so I will update a file and we see if it works , but I really need to identify all the OSD messages from the other ones.

**Comment by SourMesen** [comment]
Ah, so the OSD writes the text incorrectly then?  I'm not sure how easy it will be to fix, but we can try.

Finding the OSD messages is easy - everything in MessageManager.cpp is for the OSD. Everything in the XML file is for the rest of the UI and will not be shown in the OSD.

**Comment by raousoft** [comment]
this is the MessageManager , I tried to use another method to make the text appear right , but if it displays this time question marks ( ?????? ??? ??? ) then propably it's not supported.

[MessageManager.zip](https://github.com/SourMesen/Mesen/files/2151231/MessageManager.zip)

**Comment by raousoft** [comment]
When I go to CHR Viewer ( window ) and choose a tile , then switch to Name Table ( window) , nothing happens , sadly I think it's a logical problem that can't maybe be called a problem.

**Comment by raousoft** [comment]
this is how to describe the issue somehow

https://github.com/mpcabd/python-arabic-reshaper

**Comment by SourMesen** [comment]
Ends up looking like this:
![osd](https://user-images.githubusercontent.com/21093973/42125737-49c36e92-7c4a-11e8-8f8b-a0520128235c.png)

It looks like the order is correct, but the characters seem to be getting cut off?

**Comment by raousoft** [comment]
is it with the file that I gave you ?

It's already enough , not perfect but very enough and 99% readable.

Just one thing is that you didn't provided the 1% that points to the ( game title ) , I understand why , but it's ok I think. It's the first step :D

**Comment by raousoft** [comment]
Well I started translating , I already finished the MessageManager.ccp , and around 300 lines from the resources file , I will not translate more for now until I try the translation ( to figure out where to place the 1% tag correctly ) I wish I can have VS2017 to compile it myself so I can see real-time changes , but I don't have it ( nor I can pay for it for now ).

One question about OSD , is there a chance to RTL it ? I mean the message starts from the maximum right.

As for the menu , font is working , but the RTL is not applied in the picture you provided , when it is RTL-ed ( File will be in the right , followed by Game pause reset menu , followed by Options ..etc from right to left , then the remaining space after Help , will remain in the left).

and thank you :D

**Comment by SourMesen** [comment]
For your info, Mesen is built with VS2017 Community, which is completely free and can be downloaded from Microsoft's website.

RTL for the OSD might be hard, it could involve a decent amount of changes.
The main window in the screenshot I showed was not set to RTL (only the Audio configuration window was), so that's why the menu is not reversed - it should be fine if RTL is turned on.

**Comment by SourMesen** [comment]
Are you still interested in doing this translation?  If not, I'll close this issue.
If you are, unless you can provide a translation within the next couple of weeks, I will likely not be able to integrate it into a proper release until next year (due to upcoming vacations this fall)

**Comment by raousoft** [comment]
@SourMesen 

Yes of course always interested , but I really tried a lot to understand things but I am still struggling.

Since I am aware now of how to compile, I still need to know how to change the font for the OSD (Since you mentioned before that you generated the font based on characters , I understand that , but where/how to find/even-try to change the font in VS2019 , I really am facing a hard time trying to see the results of the translation (Since I don't want it to be a YetAnotherTranslation, since a lot just don't care and uses bots (google translate) , and that's against my interests.

I still keep trying until I find a way to display it correctly , otherwise also beside the OSD, I can't find where to translate the debugger menu (in the main menu) nor the debugger window itself / PPU viewer ..etc (Since I am exactly interested in those things more than others).

and thanks a lot for your efforts again , I really appreciate every moment of Mesen and Mesen-S
