### ISSUE TITLE
Exclusive fullscreen mode bug

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#428]
If I use Exclusive fullscreen mode I get a black screen.

**Comment by SourMesen** [comment]
Is this new? Or has it always been this way? I haven't really changed anything about exclusive fullscreen since I first implemented it.

**Comment by raousoft** [comment]
It works fine for me .

I hear a little ( sound freeze like ) but it's obvious since sharing CPU / GPU with other programs makes MESEN go slow / buggy audio for a while ( or when using another exhaustive program in background ). 
But I think it's something different occurring in this situation.
Well just to inform sorry for the intervention.

**Comment by Cibomatto2002** [comment]
No it's not new I just never did turn it in.

**Comment by SourMesen** [comment]
Is there anything that shows up in the log window after trying to enter exclusive fullscreen mode?  e.g error messages or the like

**Comment by Cibomatto2002** [comment]
All it shows is 

------------------------------------------------------
Loading rom: Metroid (USA).nes
File CRC32: 0xA2C89CB9
------------------------------------------------------
[DB] Initialized - 15539 games in DB
PRG+CHR CRC32: 0x70080810
[iNes] Mapper: 1 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 0 KB
[iNes] CHR RAM: 8 KB
[iNes] Mirroring: Horizontal
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 1  Sub: 0
[DB] System : NesNtsc
[DB] Board: NES-SNROM
[DB] Chip: MMC1
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 0 KB
[DB] CHR RAM: 8 KB
[DB] Work RAM: 8 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[DB] Input: 2 standard controllers connected

**Comment by SourMesen** [comment]
@Cibomatto2002 I just made a couple of changes to exclusive fullscreen mode (for #528), could you see if this happens to have fixed the problem you were having?  If not, can you try different resolutions and see if it changes anything?

**Comment by Cibomatto2002** [comment]
Problem still there even after getting a new computer Dell Inspiron 5676. Changing to different screen resolutions did nothing. 

Operating System
	Windows 10 Home 64-bit
CPU
	AMD Ryzen 7
	Summit Ridge 14nm Technology
RAM
	16.0GB Dual-Channel Unknown @ 1197MHz (17-17-17-39)
Motherboard
	Dell Inc. 0VYXHD (AM4)
Graphics
	ELEFW328 (1360x768@60Hz)
	4096MB ATI AMD Radeon RX 580 (Dell)
Storage
	931GB Seagate ST1000DM010-2EP102 (SATA )
Optical Drives
	No optical disk drives detected
Audio
	High Definition Audio Device

more info on it here if you need it.

https://www.amazon.com/Dell-Inspiron-Desktop-Processor-Graphics/dp/B07Q3G3B67/ref=sr_1_4?keywords=desktop&qid=1572883298&refinements=p_36%3A2421881011&rnid=2421879011&sr=8-4

**Comment by SourMesen** [comment]
Ok, thanks for testing.  I still have no clue what's causing this, then, unfortunately (especially surprising for you to get the same issue on 2 PCs, while nobody else has reported this.)

**Comment by Cibomatto2002** [comment]
I got to thinking could it be the T.V that's the problem ? I'm not at home right now but when I get home I will try to find what brand it is and tell you.

**Comment by SourMesen** [comment]
It's unlikely to be the TV, at that point that would be the video card's job, and I would expect the same issue to occur in any software you try to use.

I just did some other changes, which might also have an impact on your issue, could you give it another try with the latest appveyor build?

**Comment by Cibomatto2002** [comment]
It's working now thanks :)

**Comment by SourMesen** [comment]
Great! Thanks for the confirmation!
