### ISSUE TITLE
Text Hooker Unexpected error

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#429]
Hi dear Sour,

I got this error message , when trying to enable 'Auto-copy to clipboard'

with scan line set to 260 , still get (1 millisecond of glitch y name table) this is why I wanted to auto copy cuz text hook is fast displays text then gone.

![mesenerror](https://user-images.githubusercontent.com/37517008/42120918-adda6374-7c1b-11e8-9b15-511c82222d8a.png)

**Comment by raousoft** [comment]
ADD:

When I tried to set Cycle to about 263 , mesen crashed with the ( has stopped working )

with this details:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	MesenDevWin-0.9.5.130.exe
  Application Version:	0.9.5.0
  Application Timestamp:	5b3033c0
  Fault Module Name:	StackHash_29f9
  Fault Module Version:	6.1.7601.24117
  Fault Module Timestamp:	5add228d
  Exception Code:	c0000374
  Exception Offset:	00000000000bf6b2
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	29f9
  Additional Information 2:	29f98c43b5527fe06cf17774fd84e882
  Additional Information 3:	4b5e
  Additional Information 4:	4b5e938bfbad87fd36d07bf5e94ec99e

**Comment by SourMesen** [comment]
Thanks for the bug reports!
They should be fixed by 28aeacef9f0802a513ca635cc29647d13a93a548 and b0a007de392c77700e0ef5450724af09fb25b5b4
