### ISSUE TITLE
Only curious, but any plans to go x64-bit for Mesen?

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#430]
I'm not sure if there's any performance gains to be had moving to x64-bit, but in most cases going x64 is the way to go with very little downside. I don't think I've seen anything said from you on this, so I'm only wondering here, what are your thoughts, etc.

**Comment by SourMesen** [comment]
Mesen is actually both 32-bit and 64-bit already, the .exe ships with both versions & it will load the appropriate one based on your OS.  If you're on a 64-bit OS, it should already be running in 64-bit mode (should easy to check in the task manager).  The 64-bit version is typically 10-15% faster than the 32-bit version, IIRC (I don't actually run the 32-bit version very often so I'm unsure)
