### ISSUE TITLE
black screen on reset

### ISSUE THREAD

**Issue by Moodie92** [SourMesen/Mesen#438]
this happened in number of games i dont recall all of them but most recently  pirates, there is no error but black screen 
![screenshot 8](https://user-images.githubusercontent.com/40892036/42915732-f35fac20-8b01-11e8-9531-45720884e147.png)
and here is a log window
![screenshot 9](https://user-images.githubusercontent.com/40892036/42915741-02c8518a-8b02-11e8-8e2a-162cfc0d5e58.png)

**Comment by SourMesen** [comment]
Thanks for the report - as far as I can tell, this is the same issue as the one you reported in #431 with the SMB multicart.  I can reproduce the problem in 0.9.5, but the latest dev build resets the game properly in the same scenario.
