### ISSUE TITLE
Github downloads

### ISSUE THREAD

**Issue by CowCowCowCow** [SourMesen/Mesen#44]
Any chance we could get signed binary downloads from github + hashes in the future?

Thanks for Mesen, very impressed with it so far!

**Comment by SourMesen** [comment]
Thanks for the suggestion! I've never looked into signing files, so I can't promise anything, but I'll see what I can do about this when I get home from vacation in a couple of weeks.

**Comment by SourMesen** [comment]
It took a lot longer than I originally said, but I've finally gotten around to getting this done.
I've added a signature file to the latest release (0.8.0) and will be doing the same for all releases from now on.
Additionally, signature files will be available on Mesen's website, here: https://mesen.ca/signatures/
