### ISSUE TITLE
Empty Screenshots with NTSC + Disabled Vertical Blending + 0 Scanlines

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#445]
When using the NTSC filter with Vertical Blending disabled and Scanlines at 0 the screenshots are all empty. So far they've all been black, not sure if it's actually showing the background color of the games or if it's just purely empty.

The screenshots work when Vertical Blending is enabled or when Scanlines is set to anything higher than 0.

Everything else is at 0, bilinear is on and turning it off seems to change nothing for making screenshots work, merge fields is off and turning it on seems to change nothing for making screenshots work.

In case there's something in the PNGs what reveal a problem here's two screenshots where all that was changed is the scanlines are at 1 for the screenshot with a visible image and the scanlines are at 0 for the screenshot without a visible image.
[Screenshots.zip](https://github.com/SourMesen/Mesen/files/2255741/Screenshots.zip)

**Comment by SourMesen** [comment]
Thanks for the report - this was because all the pixels in the PNG file were set to maximum transparency (fixed by acebd1a8177f06460863cbb7052400511f08838b)
