### ISSUE TITLE
(Libretro) Core doesn't compile anymore for Linux

### ISSUE THREAD

**Issue by twinaphex** [SourMesen/Mesen#446]
Hi,

this is the error log our buildbot currently produces for us when trying to build Mesen for Linux x64 -

http://p.0bl.net/26025

**Comment by twinaphex** [comment]
Seems there is a similar issue for Windows x64 -

http://p.0bl.net/26062

**Comment by SourMesen** [comment]
Thanks for letting me know - these should be fixed by 27ee26c6cb2aa1f863cf17a991372f32a2270245
