### ISSUE TITLE
Cheat Finder's "Previous value was" is reversed

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#448]
Using "Previous value was smaller" finds values that were larger and are now smaller, "Previous value was greater" finds values that were smaller and are now larger.

Also a hex option for the value input would be useful, I've had to convert numbers with an external program too many times, often converted from hex values that came from Mesen in the first place.

**Comment by SourMesen** [comment]
I've fixed the inverted logic (ce123bdb9499e982ef72d72d90f2ae6e6a4877e3), I'll keep note of the request for a way to easily input/convert hex values as an improvement to do in the cheat finder eventually.
