### ISSUE TITLE
Magmax

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#45]
The NSF player will play track 2 to slow. Here is the NSF file if you need it.
[Mag Max (1986)(Nichibutsu).zip](https://github.com/SourMesen/Mesen/files/489038/Mag.Max.1986.Nichibutsu.zip)

**Comment by SourMesen** [comment]
Thanks for the bug report, I'll take a look when I get back from vacation in a couple of weeks.

**Comment by SourMesen** [comment]
As far as I can tell, this plays at the same speed in Mesen as in all other emulators/NSF players I have tried.
Maybe you had the "Region" setting set to PAL when you tried played the track?

**Comment by Cibomatto2002** [comment]
Track 2 plays to slow I got region set to auto also I set it to NTSC still the same problem. Here it is on another NSF Player playing at the right speed.

https://www.youtube.com/watch?v=fu6iZOALBcI&feature=youtu.be

**Comment by SourMesen** [comment]
The video you linked is pretty much exactly what it sounds like in Mesen on my end with the NSF file you provided.  Can you attach the settings.xml you have in your Mesen folder?  Maybe you have some option enabled/disabled that is causing it to play differently on your end.

**Comment by Cibomatto2002** [comment]
[settings.zip](https://github.com/SourMesen/Mesen/files/549606/settings.zip)

**Comment by Cibomatto2002** [comment]
Here is a video of what it sounds like on my computer.

https://www.youtube.com/watch?v=5S7MQoMNwD8&feature=youtu.be

**Comment by SourMesen** [comment]
I think I'm just not understanding the problem at this point - your video sounds pretty much the same as what Mesen/FCEUX/Nestopia sound like on my end, I can't hear any difference, and if I time FCEUX/Nestopia's playback and compare it with Mesen, I get pretty much the exact same sound at the exact same times, so everything seems to be playing as expected?

**Comment by Cibomatto2002** [comment]
I think it's something wrong with my computer because when I try it on my laptop it sounds correct. Sorry I wasted your time.

**Comment by SourMesen** [comment]
No problem, sorry I wasn't able to figure out what the problem was!
