### ISSUE TITLE
Message in different language

### ISSUE THREAD

**Issue by stubl** [SourMesen/Mesen#452]
I noticed when a shortcut key is set the same as another shortcut key a message appears saying there is conflict, however this message is in a different language not english

My display language is set to user account default (english) and Im using the latest Mesen 0.9.6

**Comment by SourMesen** [comment]
Thanks for the report!
This is fixed by 53797acc99ef2d324236f10e14ee873cd071ef96, along with a couple of other minor fixes to the English resources.
