### ISSUE TITLE
AccessViolationException in HistoryViewer

### ISSUE THREAD

**Issue by hksy** [SourMesen/Mesen#453]
ヒストリービューアにて記録が存在しない場合、「ここからゲームを再開する」を選択すると以下の例外が発生し、OKを押して続行すると以降一切の入力を受け付けなくなります。

> 予期しないエラーが発生しました。
> 
> エラーの詳細:
> System.AccessViolationException: 保護されているメモリに読み取りまたは書き込み操作を行おうとしました。他のメモリが壊れていることが考えられます。
>    場所 Mesen.GUI.InteropEmu.HistoryViewerResumeGameplay(UInt32 seekPosition)
>    場所 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    場所 System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    場所 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    場所 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    場所 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    場所 System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    場所 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    場所 System.Windows.Forms.Control.WndProc(Message& m)
>    場所 System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    場所 System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>    場所 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>    場所 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>    場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    場所 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    場所 Mesen.GUI.Program.Main(String[] args)

Mesen 0.9.6にて以下の手順で発生しました。
1. ROMを開く
2. デバッガを開く
3. 停止と再起動をする
4. ヒストリービューアを開く
5. 「ここからゲームを再開する」を選択

このときヒストリービューアの画面でゲームが再生されるのもおかしいかもしれません。

**Comment by SourMesen** [comment]
バグ報告、ありがとうございます！ 7247b0cb4b6e12f79ab4c90a785a4495bf01258d と 2e99f5aac15ec956b45b591d956d5d1ff359f4aa で直しました。

これからは「停止と再起動」を押した後、ゲーム内で1秒以上経たない限りヒストリービューアを開く事はもうできません。これで「ここからゲームを再開する」を選んだ時のエラーはもう発生しないはずです。

あと、最後まで再生しても、再生が続くというバグも直しました。
デバッガが開いてるままヒストリービューアを開く時に発生したバグです。
