### ISSUE TITLE
Detected as Trojan by Windows Defender

### ISSUE THREAD

**Issue by dratyan** [SourMesen/Mesen#46]
Currently, on Windows 10, Mesen 0.51 is being detected as a "Trojan: Win32/Fethar.B!cl" by Windows Defender

**Comment by ImJezze** [comment]
I cannot confirm, please check the hash values of your Mesen.exe

CRC32: A35F94AE
MD5: 0D34946C7328F60016D47DCA4D722271
SHA-1: 210B54E589F7D4CF3FD69CE363CE0B8B532EDD53

Also no detection at www.virustotal.com/en/file/865e89f16ef234d0c11d5f967ef32fa29f0d6c6a64069e1d8bdf7598f63b1bf7/analysis/

**Comment by SourMesen** [comment]
If you downloaded Mesen from the official website, I can assure you there is no virus in it (the file's content match what is seen in the code on GitHub) - if you downloaded it from one of the websites that host the download themselves, then I can't guarantee anything.  I would suggest you download Mesen from mesen.ca and see if you still get warnings.  If you do, it is definitely a false positive by windows defender.
