### ISSUE TITLE
Port to PS Vita [NES Metroid HD Pack]

### ISSUE THREAD

**Issue by julioapc16** [SourMesen/Mesen#464]

**Comment by SourMesen** [comment]
Unfortunately, the PS Vita is probably far too slow to run Mesen (even without HD Packs).

My phone currently runs Mesen around 50fps (with a quad-core 1.5ghz ARM CPU). As far as I can tell, the PS Vita has quad-core 333mhz ARM CPU.  I doubt Mesen would run any faster than 10-20fps on it.  According to [this list](http://emulation.gametechwiki.com/index.php/Emulators_on_Vita), even Nestopia doesn't always run at full speed on the PS Vita, and Nestopia is a lot faster than Mesen is (and probably faster than Mesen ever will be).
