### ISSUE TITLE
Can't run patched ROM with PRG ROM exceeding mapper limits

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#468]
Tried running this translation http://www.romhacking.net/translations/3751/ and Mesen only gives me a green screen. FCEUX can run it so I reckon the file itself wasn't patched improperly, though beat did give an error when patching it, can't imagine why as I appear to have used the right files.

I believe the only limit-exceeding aspect is a PRG ROM of 256 rather than 128.

**Comment by torridgristle** [comment]
I don't think there's a quick way to port ROMs to one of the mappers that already support oversized ROMs so an option to allow all mappers to have this ability would still be useful.

I see it as an option similar to removing the sprite limit or overclocking, something to avoid a fault, perceived or genuine, in the ROM's code.

I reckon there's a few ways to handle this:
- It's off by default and is enabled per-game and saved to the config with the ROM's CRC or however game-specific overscan settings are saved.
- It's on by default, is disabled for everything in Mesen's DB so good ROMs don't use it + the DB has an extra value for oversized ROM support for future proofing should there ever be a problem with disabling the oversized ROM support purely by checking for the existence of a CRC in the DB with the assumption that they'll all need it disabled and thus isn't worth specifying, and is described in the emulation settings as being needed for some ROM hacks.
- Same as before but it's off by default and is turned on, either globally or per-game, but the DB still has priority.

Only issue I can foresee is the possibility for an easy mistake that disables oversized ROM support in the mappers that already support it when it's added as an option. Beyond that, I think that using the DB of good ROMs to ensure that the oversized ROM option is disabled for "real" ROMs is fairly userproof.

**Comment by SourMesen** [comment]
For now I removed the 4-bit restriction on PRG banking for the VRC1 (f25e6f55327cb7f78974f2288dd36bbfefb2ebf5), which allows this particular hack to work.  When I have the time, I'll look into adding an option (although it might be pretty hard to find the mappers that allow oversized roms considering there's 290+ of them implemented)
