### ISSUE TITLE
HD pack folder name

### ISSUE THREAD

**Issue by liaodahao** [SourMesen/Mesen#470]
Mesen doesn't generate the folder name correctly if the rom name has "." character when installing HD pack.
For example,
rom name: Super Mario Bros. (World).nes
then the generated folder is "Super Mario Bros" after installing the HD pack,

Mesen 0.9.6, Windows 10 x64

**Comment by SourMesen** [comment]
Thanks for the bug report!
This is fixed by 005affab4bec688b2625e69995b0ddf9eabbcc6b
