### ISSUE TITLE
NTSC filters remain enabled when running in non-NTSC modes

### ISSUE THREAD

**Issue by rzumer** [SourMesen/Mesen#471]
Obviously, NTSC filters are not designed to simulate PAL displays, so it seems logical that they should be disabled automatically when running a PAL title. This is reproducible using the libretro core, version 0.9.6. While this could be left as the user's responsibility, adjusting configuration per title is inconvenient, and I cannot think of any use for an NTSC filter in non-NTSC modes.

**Comment by SourMesen** [comment]
Thanks for the suggestion - forcibly disabling NTSC filters in PAL mode isn't really something I want to do, though.  Odds are that some users do like to use the NTSC filters on PAL games (regardless of whether or not this results in an "accurate" PAL experience), so removing the functionality altogether is definitely not something I can do.  Which leaves adding an additional option to automatically disable NTSC filters on PAL/etc games, which I suppose could be useful in very limited scenarios, but I think having the user take care of this themselves is a better solution.

**Comment by rzumer** [comment]
The main use case for applying an NTSC filter is improving the accuracy of the display compared to real hardware. While some people *might* be interested in viewing PAL content with NTSC filters turned on, that goes so far against the point of such a filter that it doesn't seem like a sane default behavior. I think that an setting per standard or a setting to force override a default behavior and apply filtering regardless of the display would make more sense.

**Comment by vrubleg** [comment]
If a person likes how NTSC filter affects image, they would expect that it should work always, not only when some specific ROMs are loaded.

**Comment by SourMesen** [comment]
As mentioned before, I prefer the current behavior (and I believe most NES emus with NTSC filters have the same behavior as well).  I feel like changing this would only make it less intuitive to the end user, regardless of whether or not this results in an "accurate" PAL experience.
