### ISSUE TITLE
gcc-7 won't build this project

### ISSUE THREAD

**Issue by barbudreadmon** [SourMesen/Mesen#473]
It seems `-fpermissive` is needed due to some nonconforming code in https://github.com/SourMesen/Mesen/blob/master/Core/Types.h : 

> mkdir -p Utilities/obj.x64 && cd Utilities/obj.x64 && g++ -fPIC -Wall --std=c++14 -O3 -D LIBRETRO -m64 -c  ../HQX/hq4x.cpp
mkdir -p Core/obj.x64 && cd Core/obj.x64 && g++ -fPIC -Wall --std=c++14 -O3 -D LIBRETRO -m64  -c  ../Profiler.cpp
In file included from ../DebuggerTypes.h:2:0,
                 from ../Debugger.h:12,
                 from ../DebugBreakHelper.h:3,
                 from ../Profiler.cpp:3:
../Types.h:101:35: error: declaration of ‘PrgMemoryType CartridgeState::PrgMemoryType [256]’ [-fpermissive]
  PrgMemoryType PrgMemoryType[0x100];
                                   ^
../Types.h:54:12: error: changes meaning of ‘PrgMemoryType’ from ‘enum class PrgMemoryType’ [-fpermissive]
 enum class PrgMemoryType
            ^~~~~~~~~~~~~
../Types.h:107:34: error: declaration of ‘ChrMemoryType CartridgeState::ChrMemoryType [64]’ [-fpermissive]
  ChrMemoryType ChrMemoryType[0x40];
                                  ^
../Types.h:61:12: error: changes meaning of ‘ChrMemoryType’ from ‘enum class ChrMemoryType’ [-fpermissive]
 enum class ChrMemoryType
            ^~~~~~~~~~~~~
make: *** [makefile:132: Core/obj.x64/Profiler.o] Error 1

**Comment by SourMesen** [comment]
Thanks for the report.  You just happened to be unlucky - this is just something I broke yesterday (I mostly develop with MSVC, which unfortunately accepts this syntax even though I've disabled all MS-specific extensions).

The errors are fixed by 4bbef43e99e9dc9e852d620c951e9a5696ca8147
