### ISSUE TITLE
Add support for famiclone printer port.

### ISSUE THREAD

**Issue by sczther** [SourMesen/Mesen#474]
Several famiclones support printing out certain stuff through a parallel port. There is a lot of documentation here, so that should help:
https://133fsb.wordpress.com/2010/03/21/famicom-compatible-printer-port-interface/
Also, Subor clones supposedly have different implementation, as discussed here:
https://www.famicomworld.com/forum/index.php?topic=13436.0

Some of them also have support for mice and even floppy drives, but that would probably need more research.

**Comment by SourMesen** [comment]
Thanks for the suggestion!

The mouse used by some famiclones is already supported in Mesen.  Printers are not, but I don't really see myself adding support for them - this would require a lot of code/research for something that I imagine almost nobody would use (first time I've even heard of them).

At the end of the day, Mesen is a NES/Famicom emulator - it supports additional platforms to some extent (e.g Dendy timings, Subor keyboard/mouse), but supporting every single clone and each of their specific hardware/ports is a bit out of scope at the moment.

I've added a note about printers to #361 which is used to track unsupported peripherals/etc.

**Comment by sczther** [comment]
It has just a port to which it shoots the text almost raw. Also, there was no specific printer to it, regular pc printers just know the format. So it would probably be trivial to send it somewhere, maybe even hook it to OS calls for printing. I understand it's not top priority, but it's a fun little thing that has good documentation, as opposed to some other stuff :)
