### ISSUE TITLE
The problem with the sound in 0.9.6

### ISSUE THREAD

**Issue by Fatal1tyart** [SourMesen/Mesen#475]
Hello. I have a problem with the sound in the emulator after the last update of 0.9.6. He farts and crunches =) I tried different sound settings, nothing helped. I rolled it back to the old version 0.9.5 and everything was fine, as it was before. I tested on several games on Windows 7x64, sound card SB X-Fi XtremeGamer. In general, I like the work of the old version, just decided to write about the problem. Thank you! [sorry for the clumsy Google translation]

**Comment by SourMesen** [comment]
Thanks for the report.
If you are having issues with the sound compared to 0.9.5, try enabled the "Disable dynamic sample rate" option here:
![image](https://user-images.githubusercontent.com/21093973/44367087-be569980-a49c-11e8-945b-6084419113a8.png)

When turned on, the sound should behave like it did in 0.9.5, which may solve your problem.

**Comment by Fatal1tyart** [comment]
I also tried this setting. I thought about it in the beginning. And the delay was changing, 50,60,80,100. Different frequencies set and reset the emulator. At first it seemed that the delay of 100 ms helped, but no, the sound still popped. Nothing helped in the end. Just rollback to the old version.

**Comment by Fatal1tyart** [comment]
And the sound in the new version was not very good. Very fret and fart all the time. All effects were turned off. And reset the settings to default. Nothing has changed. The sound became clear, as before, only when I downloaded the old version.

**Comment by SourMesen** [comment]
> At first it seemed that the delay of 100 ms helped, but no, the sound still popped

When dynamic sample rate is disabled, the sound will eventually get distorted - this is also true for 0.9.5, because there is nothing that keeps the audio and video in sync in that version.

Clearly there must be something about your computer that makes it not work properly with the dynamic sample rate option, but I can't really see any reason why it would behave differently between 0.9.5 and 0.9.6 if that option is disabled, I'll have to check if other changes might have caused it.

**Comment by Fatal1tyart** [comment]
It's just weird. The old version works fine. And in the new immediately sound terrible, with any settings. Sound settings in the operating system itself, I did not touch, in the driver of the sound card, too, did not change anything. 0.9.6 just naughty on my PC. Later I will try to delete the saved config files of the emulator and run 0.9.6 completely from scratch. The most interesting is the reason. Read that some have such garbage on windows 10.

**Comment by Fatal1tyart** [comment]
All! I figured it out! It was in the files of configs and save in my documents. I just renamed the Mesen folder to Mesen_ and ran Mesen 0.9.6. I set up a quick: video, control, sound and other trivia. I started a couple of games and the sound is now normal, clean and how nice it is! Now it can be recommended those who have a similar problem, so they delete the old configs in my documents or in the folder with the emulator. Thanks for answers. The problem is solved. Sorry for disturbing!

**Comment by SourMesen** [comment]
Thanks for reporting back with your solution!
If you still have it, could you send me your old config.xml file (the one that was causing the issue)? It might help me fix the problem entirely.  Don't worry about it if you already deleted it, though.

**Comment by Fatal1tyart** [comment]
Yes, the folder mesen_ remained. I'm just not sure exactly what the config was about, or something else. I started using the emulator from version 0.9.3. And since then nothing has been touched in that folder, just updated the emulator. I can certainly send the old config file or other files if necessary.
I attached the file settings.xml, only renamed the extension to txt.
[settings.txt](https://github.com/SourMesen/Mesen/files/2316579/settings.txt)

**Comment by Fatal1tyart** [comment]
Here is another file created in the new folder when you run version 0.9.6. Maybe he will come in handy. Now the emulator and sound works perfectly in the new version.
[new_folder_settings.txt](https://github.com/SourMesen/Mesen/files/2316587/new_folder_settings.txt)

**Comment by Fatal1tyart** [comment]
I apologize if Google translates something crookedly. I do not know much English.
