### ISSUE TITLE
Mesen crashes when pausing game in full screen and using Chinese UI language

### ISSUE THREAD

**Issue by liaodahao** [SourMesen/Mesen#477]
Hi,
I found a problem, open a game, enable full screen, pause the game, then Mesen crashes.
This problem only occurs when using Chinese UI language. I have tried English and Japanese, no such problem.
MesenDevWin-0.9.6.16, Windows 10 x64

Here is the dump file created when Mesen crashed in case you need it.
https://tpedutw-my.sharepoint.com/:u:/g/personal/xlmldh_tp_edu_tw/ERQKzUiptFxEtswGrb67XLUBMuq-OilY95gojfAj_KL-LQ?e=zOmnji

**Comment by SourMesen** [comment]
Thanks for the report!

This is fixed by 199e82a48b863a059453d88eab0fc60e4a45be3d
