### ISSUE TITLE
Flicker Faux-Transparency Smoothing

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#478]
Some games, like New Ghostbusters II (proton beam) and Shatterhand (orange shirt is palette entries 16/26), turn sprites on and off every frame for a transparency effect. Sometimes they're rendered with dithering with my laptop's screen, not sure why but I'm sure it's not Mesen, and it's a little tiring to look at. The intended transparency effect isn't shown in screenshots either.

An option to blend the current and last frame, maybe toggled with a hotkey, would help with games that make heavy use of this faux-transparency. If not the whole screen, then perhaps only the sprites layer and it stops when the background changes beyond a set threshold in order to detect scene changes.

**Comment by SourMesen** [comment]
I tried this on my end, and to be honest, my monitor/eyes cannot see the difference between sprites flashing every other frame vs a sprite becoming semi-transparent every other frame - it looks the same to me.

Doing this, however, does introduce a noticeable amount of motion blur, so I'm not sure anyone would really want to play with this enabled...  Only applying it to the sprite layer while technically possible, would require too many changes to be worth the effort, and I think I would rather avoid the potential code complexity/performance impact.
