### ISSUE TITLE
Linux' libreto makefile moves the file wrong

### ISSUE THREAD

**Issue by DuendeInexistente** [SourMesen/Mesen#479]
> cp ./Libretro/obj.x64/mesen_libretro.x64.so ./bin

It took me a few minutes to figure out why couldn't I find the .so library after running make, but the "cp" is formatted in such a way that it copies to a new file named "Bin" (Not to a folder with that name) in the repo's root folder. It's an easy fix.

**Comment by SourMesen** [comment]
Thanks for the report!  This is fixed by 46c744808a39be3e8335b34893ac83deca9f08fc
