### ISSUE TITLE
Idea for Mesen: Reduce sprite flickering by buffering frames

### ISSUE THREAD

**Issue by medigi** [SourMesen/Mesen#48]
New idea for emulator to add: buffer three frames (adding an input lag of 50/100 ms) , if a sprite gets hidden for a frame of two then reappears, consider it as sprite flickering and show the sprite that would be otherwise hidden during both frames, using an average for its position

**Comment by Nicholas-Steel** [comment]
An interesting idea, most emulators have an option that simply disables emulation of the Sprite # limit that causes things to flicker in the first place though (Sprites normally flicker if too many occupy a scan line).

**Comment by SourMesen** [comment]
I've given this idea some thought over the months, and I don't think the relatively low benefits would be worth the added complexity.
Averaging out the position of sprites would cause glitches in multiple scenarios unless more logic is added to determine whether or not it really is the same sprite, or another sprite that just appeared on the screen.
Closing this for now.
