### ISSUE TITLE
Random Variation for HD Pack Tiles

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#481]
I was thinking about why I don't like HD Packs that are actually higher definition and I settled on one possibility being a lack of variation in tiles being more apparent with the higher resolution that makes the tile grid and repeating elements much more apparent.

I believe a solution to this is randomly, or "randomly", placed variants, similar to the Minecraft mod Optifine's variant feature for texture packs.

Elements I believe will be needed in HD Packs are:
-Specify static seeds in HD Packs so that some generated patterns stay the same
-Specify which elements can use new seeds, perhaps generated on power on / power cycle and stored in savestates, perhaps generated the first time it's run and then a file is generated containing the seed, perhaps check for a certain value in CPU RAM to start the generation of a new seed and save it.
-Control over random / "random" generation frequency, method, and weighted mixes of methods for groups of tiles.
-Voronoi Cell for water / vines / etc, Blue Noise, Gaussian, etc along with a [prime number pattern generation method](https://www.sitepoint.com/the-cicada-principle-and-why-it-matters-to-web-designers/) that could be named Cicada and possibly put through a hilbert curve.
-Specify how Mesen can know when and how the camera moves, like which address to watch and how to use them, so that there isn't an unchanging arrangement of alternate tiles as the camera moves if this poses a problem.

**Comment by SourMesen** [comment]
Thanks for the suggestion.  This would require having a reliable way to identify each individual block on the screen, and keep them identical while the screen is scrolling, etc.  I don't really think there's an easy and reliable way of doing this across an entire game (e.g Metroid's world is huge, and it would be odd if by coming back to the same area, portions of it kept changing, etc.).

Also, most visual elements in the tiles are larger than 8x8, which would require the HD Packs to contain definition for "metatiles" that could then be swapped out with alternative versions, etc. And this wouldn't really help solve the single most glaring problem (in my opinion) of higher resolution packs, which is sprite animation (or lack thereof).

This is probably the kind of thing that would be "easier" to solve by altering the ROM's code to change the game's tiles (and then replace them with HD versions). I'd rather not overly complexify the HD pack system - creating packs is already excessively time consuming as is it, adding to much functionality will make it that much harder to understand (and makes the code that much harder to maintain, too.)
