### ISSUE TITLE
Mesen (Beta) has stopped working

### ISSUE THREAD

**Issue by neodolphino** [SourMesen/Mesen#486]
I am trying to test a game using Mesen, but I can't even get it to load, as it immediately crashes.

I get the message in the subject line.  The additional info is as follows:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Mesen.exe
  Application Version:	0.9.6.0
  Application Timestamp:	5b673f67
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24214
  Fault Module Timestamp:	5b627415
  Exception Code:	e0434352
  Exception Offset:	000000000001a06d
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	2413
  Additional Information 2:	2413de213f38e5efe700010a55469627
  Additional Information 3:	7cc8
  Additional Information 4:	7cc89ccc25e007e694a87ea03c2cef53

**Comment by SourMesen** [comment]
Does this happen with any game you load?  If it's a specific game/rom, information about the ROM would be useful.

If it happens with any rom, I'll probably need more information to solve this.  While the "Mesen has stopped working" message is shown, you can open Windows' task manager, right-click on Mesen and select "Create dump file".  If you send me the file this creates, it should help me understand the source of the crash.

Also, are you using 0.9.6 or one of the AppVeyor dev builds?

**Comment by neodolphino** [comment]
It happens when I simply try to start the program, either by double click, or by dropping a rom on it.

I'm using 0.9.6, the newest version (I also tried with the 0.9.5, just in case).

I'm using Windows 7, btw, if that helps.

Attached is the file you requested.
[WerFault.zip](https://github.com/SourMesen/Mesen/files/2329111/WerFault.zip)

**Comment by SourMesen** [comment]
It looks like this isn't the right dump file - normally it should create a "Mesen.dmp" file when creating the dump for the Mesen process.  WerFault is the process that handles crashes applications.  Try going to the "Processess" tab and finding the line that has "Mesen.exe" in the first column (Image Name), this should be the right process.

Also, could you try running Mesen in a command prompt with the /novideo and/or /noaudio flags?
e.g: ```Mesen /novideo /noaudio```.
If the video/audio components are causing the crash, this should allow Mesen to startup properly (although you will get no video/audio if you load a ROM)

**Comment by neodolphino** [comment]
Using the command prompt caused the same crash on startup with the novideo/noaudio flags.

I made a dump of both the normal start, and the novideo/noaudio start.

Both files are too big for here, so I'll include a file share link:

https://ufile.io/yoitn

**Comment by SourMesen** [comment]
Could you check the version of the .NET Framework you have installed?
Mesen requires 4.5.0 or above, as far as I can tell from your dump file, you have .NET 4.0 installed.

**Comment by neodolphino** [comment]
It looks like that was the issue.  It's resolved now.  Thank you so much! :)

**Comment by SourMesen** [comment]
No problem - happy to hear that solved it!
