### ISSUE TITLE
Option "Allow Left+Right / Up+Down"

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#49]
In emulators Nestopia and FCEUX there is option. I didn't found it in Mesen, maybe i'm somewhere missed it?

Anyway, if there no option for this, maybe you can add it? Thanks for responce

**Comment by SourMesen** [comment]
I can't check right now, but I think the setting for this is in Options -> Emulation -> Advanced

**Comment by SourMesen** [comment]
Option is here:
![untitled](https://cloud.githubusercontent.com/assets/21093973/19417689/5479d83e-9381-11e6-9c43-5ebc5b6f0ed0.png)
