### ISSUE TITLE
BIT (Byte Code $2C) Description Clarification

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#490]
The BIT (Byte Code $2C) description as seen in the debugger says it copies bits from the specified address to flags N and V and it's not clear that V is Overflow. I only figured it out after checking the Nesdev wiki.

**Comment by SourMesen** [comment]
I've added the flag's letter abbreviation in parenthesis in all descriptions, and reworded the one for "bit" to mention the full names (and the abbreviation) (0ea9d4dff1075ed33e9f1cca80088c179825ad21)
