### ISSUE TITLE
Memory Tools: Hex Pasting

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#491]
Currently I can copy and paste hex data from within Mesen's Memory Tools, but pasting hex data from another program into the hex area in the Memory Tools window causes it to be interpreted as text.

Rather than try to guess if the user's clipboard contents should be interpreted as text or hex I reckon it should just assume it should be formatted to whatever the cursor is inside.

**Comment by SourMesen** [comment]
Fixed by 77a5d6c443ef10c0544a4f3654146c0761c2005d
Pasting in the left side will always assume any text in the clipboard is hex (non-hex characters will be ignored).  Pasting text on the right-side will work as before.
