### ISSUE TITLE
PPU Viewer: CHR Viewer: "Copy image to clipboard" Scale

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#493]
The "copy image to clipboard" option in the context menu for the PPU Viewer's CHR Viewer put a 2x scaled version of the image in the clipboard which isn't very useful for editing the bitmaps as they need to be scaled down in whatever program they're pasted into.

Nametable Viewer and Sprite Viewer keep it 1x though, it's only the CHR Viewer.

**Comment by SourMesen** [comment]
Thanks - this is fixed by 77a5d6c443ef10c0544a4f3654146c0761c2005d
