### ISSUE TITLE
Low G Man Crashing In-Game

### ISSUE THREAD

**Issue by BlackGuyRX** [SourMesen/Mesen#497]
Anytime I play Low G Man, the game seems to regularly crash out shortly after or right upon entering the first boss stage. Even after attempting to bypass it and skip right into stage 2 from entering the first hidden stage located in 1-2, it crashed as soon as the stage loaded.
![low g man - the low gravity man usa -180906-005000](https://user-images.githubusercontent.com/6956691/45137560-da318f00-b16e-11e8-9941-92ec90c1f500.png)

I'm running the Mesen Libretro core in the latest RA stable

**Comment by Cibomatto2002** [comment]
SaveState

http://www.filedropper.com/lowgman-thelowgravitymanusa1

DEvWin-0.9.6.24

**Comment by SourMesen** [comment]
Thanks - this was an issue I've been aware of for a long time, but never got around to fixing it.
This should be fixed by 512d971b87d84eb300017ee0d0e4c71ee459d67e
