### ISSUE TITLE
HD Packs: memoryCheck + memoryCheckConstant featuring Bitmasking / AND

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#498]
Just finished working out how the completed stages in Shatterhand are stored for the television screens on the stage select menu and it's another situation that uses individual bits.

$2D and its bits are arranged as such for Areas B through F: 000FEDCB

Currently this is 32 different memoryCheckConstant conditions.

However, if it could be masked to $01 for B, $02 for C, $04 for D, $08 for E, and $10 for F, this could be handled with 5 conditions each targeting the relevant parts of the address, and not extra pieces of data that are unrelated to the intended condition.

I presume bitwise operations aren't uncommon in NES games and thus being able to handle them in the conditions would be superb.

**Comment by SourMesen** [comment]
It seems like adding a "mask" parameter would be enough in this case?

e.g, change it to be:
[content of memory] & [mask] == [value in hires.txt]
where mask would be $FF when empty.

Or am I missing another similar use case?

**Comment by torridgristle** [comment]
I think we're describing the same thing as long as the end result is the ability to have conditions for individual bits of a byte at an address.

**Comment by SourMesen** [comment]
I added a mask parameter in 0d40a57d0781f29a840f9bb09ce3753d9db51244

See doc here: https://github.com/SourMesen/Mesen/blob/master/Docs/content/hdpacks/_index.md#memorycheck--ppumemorycheck
