### ISSUE TITLE
When loading a game via command-line, it resets instead of restoring last gameplay session

### ISSUE THREAD

**Issue by geekley** [SourMesen/Mesen#504]
When loading a game via command-line, it loads the game from the beginning instead of restoring last gameplay session. Then, if you close, the "suspended" data is lost forever.

There sould be a command line option to choose how the game should be loaded.
The values could be, for example:
- don't load, just open game selection with that game selected, ready to open when you press A
- load from the beginning
- restore last gameplay session
- load from most recent savestate
- load from specified savestate [1-10]

**Comment by SourMesen** [comment]
Thanks for the suggestion - having a way to load save states from the command line is not a bad idea.
FYI, you can load the previous session's data after starting the game from the command line, just use the File->Load Previous Session option in the menu (it's also a bindable shortcut)

**Comment by Giermann** [comment]
<Offtopic>
Since I do not reach geekley somewhere else:
@geekley, could you try to have a look at my issue https://github.com/Giermann/WebAppTabs/issues/1

**Comment by SourMesen** [comment]
As of 7814165bb8eab8ad4c56e86abb636eac8722a9c7, a new "/loadlastsession" switch exists to load the game's last known state. 

Loading a save state is possible by specifying the savestate file's path (e.g: `Mesen "C:\path\mystate.mst"` will load mystate.mst and the corresponding ROM file) - this isn't new and has been possible for a long time, as far as I know.
