### ISSUE TITLE
Netplay: could not connect to server

### ISSUE THREAD

**Issue by CHEF-KOCH** [SourMesen/Mesen#505]
Hello, 
first of all, thank you for this amazing emulator it works very well so far. Sadly I'm having troubles understanding how the netplay option works since the [documentation isn't really complete](https://www.mesen.ca/docs/tools.html). Is this feature a lan only feature or does it really works via internet?! I tried to play with someone over the internet (Contra CRC: 0xF6035030) and I couldn't connect, Mesen 0.9.7 always gave us "could not connect to server" error back after several seconds.

Is there a list which co-op game is working or how can I deal with it?! Thanks for the support! 

```bash
Win: 10 x64 Ent. 17763.1 (Build 1809)
Loading rom: Contra.nes
File CRC32: 0xC50A8304
PRG CRC32: 0xF6035030
PRG+CHR CRC32: 0xF6035030
[iNes] Mapper: 2 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 0 KB
[iNes] CHR RAM: 8 KB
[iNes] Mirroring: Vertical
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 2  Sub: 0
[DB] System : NesNtsc
[DB] Board: NES-UNROM
[DB] Mirroring: Vertical
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 0 KB
[DB] CHR RAM: 8 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[Input] 2 standard controllers connected
```

**Comment by SourMesen** [comment]
It is supposed to work over the internet, and I have done so a number of times in the past (although not recently).

If it's not working, odds are a firewall somewhere (Windows, your router, their router, etc.) is blocking the port you've selected, or the host player (who does "Start server") did not properly add port forwarding rules to their router's configuration (Mesen tries to do this automatically, but may not be able to for a wide variety of reasons).  I believe you might also be able to use software such as Hamachi to work around this, but I have not tried Hamachi w/ Mesen (and have not used Hamachi in 10+ years myself)

There are no game-specific restriction, any game can be played over netplay.

**Comment by CHEF-KOCH** [comment]
Alright, thanks for your quick response and the explanation this already helped me. 

I tried to disable the Windows firewall on both ends without any luck so it seems the router isn't automatically opening the port, as you said it seems to be that you have to manually open/forward the ports in your router or use external software - however, I don't like both options since it's a possible  security risk (if you forget to close the port after you're done) or you simply have to trust other software/networks.

I'm closing the ticket now since it definitely works for me (over lan) and I don't think you will change something on the current netplay code because that would require a lot of effort and Hamachi & Co is then probably the easier solution for most people.
