### ISSUE TITLE
Windows file association doesn't respect case sensitive

### ISSUE THREAD

**Issue by CHEF-KOCH** [SourMesen/Mesen#506]
Win: 10 x64 Build 1809 Ent.
Mesen: 0.9.7 (beta)

![mesen](https://user-images.githubusercontent.com/727123/45922153-b0919b00-bec4-11e8-9f60-dd653fb80358.png)

## Problem
Using Mesen's file association  (preferences - folders/files) works in general but it only changes the preview picture in case you use.NES (big) as file extensions. 

## What I expect
I expect that it also recognizes the small .nes file as and change the file picture accordingly. This also affects all other extensions such as FDS etc.

## Additional Info
Opening via double-click, however works just fine.

**Comment by SourMesen** [comment]
This is most likely a case of Windows/Explorer not refreshing the icons properly (I'd suggest checking to see how it looks after a reboot, at the very least).  The code does in fact add the file association for the lowercase name (and not the uppercase one), and Windows does not use a case-sensitive file system, so all file associations created by any program should be case-insensitive.

**Comment by CHEF-KOCH** [comment]
Alright, restarting or killing/restarting the explorer.exe already did it!
