### ISSUE TITLE
AOROM (mapper 7) mirroring not 1-screen until first mapper write

### ISSUE THREAD

**Issue by pinobatch** [SourMesen/Mesen#511]
While trying to get Martin "nocash" Korth's game _Magic Floor_ working on other mappers, I discovered what might be an incorrect behavior of Mesen's emulation of AMROM/ANROM/AOROM (iNES mapper 7). Prior to the first write to $8000-$FFFF, the mirroring is horizontal, as if this were mapper 34 instead of mapper 7. I imagine that on hardware, whether it powers on with the register set to screen A or screen B, the hardware still outputs the same A10 value for all four nametables.

Test ROM works in FCEUX, but the PPU viewer of Mesen shows it reading from the wrong nametable: [Magic Floor AOROM.nes.zip](https://github.com/SourMesen/Mesen/files/2450285/Magic.Floor.AOROM.nes.zip)

I was able to get this particular ROM working by changing it to NROM with vertical mirroring, but I'd still like to understand why it doesn't configure the mirroring before the first mapper write.

**Comment by SourMesen** [comment]
Thanks - mapper 7 now boots up in 1-screen mode (37904b867980610d9b3948c0f31315a6b18b45ee)
