### ISSUE TITLE
CHR Viewer Corrupted PNG Output + Crash

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#514]
Every now and then using the save as PNG feature in the CHR Viewer results in a PNG like this https://i.imgur.com/F4R5cAO.png and I caused a crash in Mesen by trying to save it again over the old busted PNG. Here's the unexpected error that was shown https://i.imgur.com/hkXgBx2.png

**Comment by SourMesen** [comment]
Thanks for the bug report - I haven't been able to reproduce it on my end, but I'm fairly certain it should be fixed by 031f320d44d9bae5a225d2c4d41f829eeca69e8e.  If you still get the crash after that commit, let me know.
