### ISSUE TITLE
add ability to hide mouse pointer for zapper (works great for aimtrak and topgun mouse ir guns)

### ISSUE THREAD

**Issue by jjfmz42015** [SourMesen/Mesen#515]
add ability to hide mouse pointer for zapper (works great for aimtrak and topgun mouse ir guns)

**Comment by SourMesen** [comment]
Is this request for the libretro core? Or the standalone version?

**Comment by jjfmz42015** [comment]
Standalone windows version please and thank you

**Comment by SourMesen** [comment]
Thanks for the request - I've added this option in 8bd292d8d5702085a03a5316a9d6c6116fb1c121.
Go to Input -> Advanced and it should be there.  The feature should be available in the next Appveyor dev build (see the readme for link)
