### ISSUE TITLE
"Turbo A" button doesn't working in Cowboy Kid?

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#52]
How to reproduce:

1) Open game Cowboy Kid
2) Options - Input - Player 1 Standart Controller - Setup
3) Select Preset... - Keyboard - WASD Layout
4) Try to attack using Turbo A button

![mesen1](https://cloud.githubusercontent.com/assets/21690438/19626493/1a718f22-993c-11e6-8f1f-f584062f5f74.PNG)

Video of the problem: https://youtu.be/FOWzpamzOog

**Comment by SourMesen** [comment]
Is your "Turbo Speed" setting set to the fastest speed?
When set to the fastest speed, some games might not detect the button presses correctly.

I'm not sure why it only affects the A button in this game, but if you reduce the turbo speed a bit, it should work correctly.

**Comment by Arcus87** [comment]
Reduced turbo speed a bit, it works now.
