### ISSUE TITLE
I can't enter the level in super mario bros 3

### ISSUE THREAD

**Issue by 3DSFAN2018** [SourMesen/Mesen#522]
how do I enter the level

**Comment by JeffAlyanak** [comment]
I don't have any issues playing through the first few levels of Super Mario Bros 3. Do you have any more details about the issue?

Just for future reference, you really do need to provide more details when submitting an issue. Make sure you include details about:

- Version of any software & OSs you're using
- Detailed description of the issue
- Detailed list of steps to reproduce the issue

**Comment by 3DSFAN2018** [comment]
I play on windows 10 by the way I fixed it

**Comment by JeffAlyanak** [comment]
You should add the steps that you took to solve it and then close this issue.
