### ISSUE TITLE
Start movie recording via cmd line?

### ISSUE THREAD

**Issue by cacciatc** [SourMesen/Mesen#525]
Howdy! 

I am a NES homebrewer and used FCEUX during development of my last project Nebs 'n Debs. I am planning on using Mesen for development of my next project. I am trying to find a way to start the recording of a movie using a command line switch or with a Lua script, but haven't been able to find anything in the docs. Is it possible with Mesen?

**Comment by SourMesen** [comment]
Sorry this took so long - I just added a "/recordmovie" command line option for this.  e.g:
```
Mesen mygame.nes /recordmovie="test.mmo"
```
This will save it in Mesen's "Movie" folder by default, you can specify a path if you want to save it somewhere else.

At the moment, /recordmovie always starts recording from a power cycle, so if you do `Mesen /recordmovie="test.mmo"` while a game is already opened in Mesen, it will power cycle and start recording.

If you have any issues with it (or need more features than this), let me know.

**Comment by cacciatc** [comment]
Awesome! Just tried it out building from master. Works great.

Thanks :)
