### ISSUE TITLE
add ability to assign full screen resolution windows standalone

### ISSUE THREAD

**Issue by jjfmz42015** [SourMesen/Mesen#528]
All user to configure windows full screen resolution rather than using deaktop resolution. this is very handy for those of us that output to tv.

**Comment by SourMesen** [comment]
I just added an option to select the resolution used for exclusive fullscreen mode.
Could you take a look at the latest dev build and see if it's working as expected for you?  If it is, I'll add the same option to Mesen-S, too.

**Comment by jjfmz42015** [comment]
Awesome works.


Could it be possible to add 640 x 480 as well?

**Comment by jjfmz42015** [comment]
so, it seems sometimes it works, sometimes it doesnt,

like i mean sometimes i push f11 it goes to the desired mode, sometime i push f11 and it goes to the desktop mode. pushing f11 to get in and out seems to correct.

dunno if im describing this proper

**Comment by SourMesen** [comment]
I've done a few more changes, which should hopefully fix the bug where you needed to toggle it on and off to make it work properly. Also added 640x480 to the list of resolutions.

Let me know if the issue you were having is solved (but if it's not, it might be hard for to fix it - with these new changes both PCs I have work properly, so fixing something I can't reproduce will be tricky)

**Comment by jjfmz42015** [comment]
works like a charm!

thank you.

**Comment by SourMesen** [comment]
Great - thanks for the confirmation!
