### ISSUE TITLE
4-player adapter

### ISSUE THREAD

**Issue by RaptorMan83** [SourMesen/Mesen#53]
Does this option exists? If not, maybe you can add it in Mesen (would be great)?

**Comment by SourMesen** [comment]
The option is here:
Options -> Input -> "Use Four Score accessory"

If you set the "Console Type" to "Famicom", it is instead in the "Expansion Port" dropdown, listed as "Four Player Adapter"

When the option is selected, you will see 2 extra slots to configure the controllers' key mappings.

Hope that helps!
