### ISSUE TITLE
Memory leak in Event Viewer

### ISSUE THREAD

**Issue by zorchenhimer** [SourMesen/Mesen#531]
I found a memory leak in the Event Viewer the other night.  Mesen was using up eleven gigs of RAM when I found out.  I've narrowed it down to Debugger::GetDebugEvents() in the Core DLL.

I can only get a fix running in debug mode.  Release mode crashes on startup.  I'm chalking this up to my limited C++ knowledge.

**Steps to reproduce:**
1) Open any ROM.
2) Press Ctrl-E to open the event viewer.

The memory usage spikes for a second or two, recovers, then gradually increases by about a MB or two each second, ad infinitum.  Unchecking the boxes in the event viewer has no effect, nor does the active tab.  The leak is paused while the emulation is paused.  Closing the window stops the leak but does not release the memory.

I found the leak in version 0.9.7 and confirmed that the latest master also has the leak.

**Comment by zorchenhimer** [comment]
That was actually the fix i tried!  I can't get it to run compiled as release though, otherwise I would have submitted a pull request.

**Comment by SourMesen** [comment]
I just fixed it on my end (b9703369cfa50409135b16012f612a28a1a5907d) and it doesn't seem to be causing any crashes.
Give the latest appveyor build a try (https://ci.appveyor.com/project/Sour/mesen/build/artifacts) - it should hopefully be working properly.
