### ISSUE TITLE
Crash on savestate load with mismatched hash

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#535]
I'm editing a game's font (nothing in the PRG, pure CHR) and Mesen will freeze up, max out a CPU core, and be unresponsive when I try to load a savestate with what appears to be a mismatched hash near the top of the savestate MST file.

Replacing it with the hash from a new savestate allows it to work fine.

**Comment by SourMesen** [comment]
This should no longer be an issue as of 295a68f43dd235ceab889e51e0168d095b8eb641.
The code will only try to hash up to 100 roms before giving up, which should prevent it from locking up for more than a second at very most (at which point the UI will say that it wasn't able to find a matching rom)
