### ISSUE TITLE
Frameskip option

### ISSUE THREAD

**Issue by RaptorMan83** [SourMesen/Mesen#54]
I didn't found this option. This could be usefull and it's need if host-machines, which can't provide / support required FPS and inquire with system requirements of emulator. This option already in fceux, nestopia and puNES

**Comment by SourMesen** [comment]
Thanks for the suggestion!
NES emulation is relatively lightweight - my old desktop (10+ years old) can run any game at over twice the normal speed in Mesen.  My current desktop (6 years old) with an old i5 CPU can run most games up to around 250-300 FPS (4-5x normal speed).  I imagine almost all desktop and laptop computers bought in the last decade would be able to run all games at full speed.

Also, displaying the actual picture on the screen takes up only a fraction of the time (10-15%) needed by the rest of the emulation.  This part of the process also runs in another thread, meaning that to see any benefit to frame skipping, you would probably need to be running Mesen on a single-core 1ghz CPU.

I will mark this as "won't fix" for now.  In the future, if/when Mesen is ported to other platforms (a Raspberry Pi comes to mind), it may be useful to add such an option.

**Comment by Nicholas-Steel** [comment]
In Wizards & Warriors III intro cutscenes I get around 98FPS during the scroll/parchment text scenes and 110 to 120FPS during the cinematic portions of the cutscenes (one brief instance where it drops to around 86FPS).

Windows 10 x64
Intel i7 920 @ 3.20GHZ
ASUS P6T
Geforce 760 4GB
8GB DDR3 RAM

So I don't think performance should be much of an issue on 2010 and newer hardware!?
