### ISSUE TITLE
feature request Cheat Window resize 

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#540]
I take notes on game cheats so I will know what will happen on a  certain code so could there be a option on how to set the cheat window size? I would like to see it bigger I know you can stretch the window out but it will never stay so could there be a way to make it stay the size i want it to stay?

**Comment by SourMesen** [comment]
Thanks for the request - I've changed it so the cheat window's size & position are saved (4b43d6d9abfef3d22398bf02438f2f69e56eccfa).  Also, the columns will auto-size themselves to display as much of the cheat's description as possible automatically.

**Comment by Cibomatto2002** [comment]
Thank you very much
