### ISSUE TITLE
Dragon Ball Z: Mesen After exiting .Unable to read .sav archive

### ISSUE THREAD

**Issue by sdefkk** [SourMesen/Mesen#543]
mesen ver 0.97 
Dragon Ball Z - Super Saiya Densetsu (Japan) (Rev 1) [En by Saiya v0.99Final] (~Dragon Ball Z - Legend of the Saiyans) ROM

imgage:
http://images2.imagebam.com/8e/53/05/6ca0511060921044.png

**Comment by mkwong98** [comment]
First, this game is not Super Saiya Densetsu, as that game is SNES game. This game is DBZ: Kyoushuu! Saiyajin. The rom of this game usually has a bad header where mapper number is wrong. The correct mapper number is 159 but usually appear as 16. 

http://wiki.nesdev.com/w/index.php/INES_Mapper_016
http://wiki.nesdev.com/w/index.php/INES_Mapper_159

It is possible for the emulator to figure out the correct size (HDNes does it) but fixing the header to see it the problem goes away seems to be faster. Please check the rom header if this is the source of your problem.

**Comment by SourMesen** [comment]
Mesen doesn't implement the EEPROM save feature for mapper 16 at the moment (it's been on my list of things to do for ages, but never got around to it).  That's most likely the issue here, I think.  I'll try to take a look soon, but the simple workaround at the moment would be to use save states instead of relying on the game's save functionality.

**Comment by mkwong98** [comment]
In that case, I apologize for my hasty reply. Are there other known cases of mapper with missing feature? If so then I suggest adding another color to the supported mapper chart to indicate mappers with partial support.

**Comment by SourMesen** [comment]
It's hard to say, really.  At the very least, it's more or less the only "TODO" in the code that hints at an incomplete mapper implementation.

**Comment by SourMesen** [comment]
Support for Bandai's EEPROM save data is available as of c4dbe9929cb79a78cd03fabe7bdbcb90f240aa04.
The games I've tested all appear to work properly, let me know if there are any issues with it.
