### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by UltimateFang0sta** [SourMesen/Mesen#545]
Upon downloading mesen and extracting it, when i try to open it, it gives me this error.
Hopefully i can get this solved.
![desktop screenshot 2018 12 17 - 17 02 18 44](https://user-images.githubusercontent.com/32083160/50121324-0f458700-021e-11e9-8bf5-2541c195ebf6.png)

**Comment by SourMesen** [comment]
Thanks for the report.  It looks like some files are missing from the disk, which is strange.
Can you go into Mesen's data folder and see what files are in it?

Depending on what you selected when you first opened Mesen, these files are either in your Documents\Mesen folder or in the same folder as Mesen.exe itself.

The folder should normally look like this:
![image](https://user-images.githubusercontent.com/21093973/50130007-a83dc780-0249-11e9-8f42-fdac76cd6691.png)

Specifically in your case, the missing file appears to be Resources\PixelFont.ttf

**Comment by UltimateFang0sta** [comment]
![mesen files](https://user-images.githubusercontent.com/32083160/50390576-4c1dec00-06fe-11e9-8308-82b7f96d0e36.png)
![mesen files 2](https://user-images.githubusercontent.com/32083160/50390577-4d4f1900-06fe-11e9-8b69-447450c8b672.png)
Thank you beforehand for your response, from what it seems, you are correct, strangely, The file appears to be missing.
I have no idea how this happened, it's strange.

**Comment by SourMesen** [comment]
Closing this for now since I can't really do anything to help beyond this without more information - let me know if you still have issues.

**Comment by UltimateFang0sta** [comment]
Sorry for not answering in a long time, but upon changing the name of the folder, the program did reset successfully, and now i'm able to play again, thanks for the help

**Comment by SourMesen** [comment]
Awesome - thanks for letting me know!
