### ISSUE TITLE
A few issues with Mesen

### ISSUE THREAD

**Issue by EmuMonkey** [SourMesen/Mesen#546]
Hi SourMesen.

First of all thank's for a very good nes emulator, But i had a few issues i would like to address.

1:  I don't know if this is a bug in windows 10 or a bug with Mesen, I recently encountered a bug where mesen would switch from fullscreen to windowed mode when i booted up a game (it also did it when using a command-line in Launchbox like the %romfile% /fullscreen or /fullscreen. I fixed it by disabling screen optimisations in properties/Compatibility  in win 10.

2:Right now i'm having an issue where Mesen occasionally will hang for a few seconds or suddenly fast forwarding (like skipping frames) while playing a game, It does it randomly for a few seconds once in a while when playing. I could be wrong but i don't recall having this issue in the 0.9.5 build. 

Thank's for your hard work with this emulator (that almost run all titles including hacks).

**Comment by SourMesen** [comment]
Thanks for the report.

For 1), are you using the exclusive fullscreen mode?  In that case, there are a number of ways that could cause fullscreen mode to end - I'm not sure how easily I can fix them, though (I'll see if I can reproduce this on my end)

For 2), I can't say I have any specific idea what might be causing this.  How frequent is it? (e.g once every 10 minutes, once every 2 hours, etc.)  I don't think there's too much that has changed between 0.9.5 and 0.9.7 that could be causing this.  While it's "frozen", can you still interact with the emulator's menu/etc, or is it completely frozen?

**Comment by EmuMonkey** [comment]
Hi.
1: Yes i am using the exclusive fullscreen mode with 16:9 aspect ratio selected, Could it have something to do with my high dpi (3840x2160) resolution laptop screen??, It has given me some problems now and then with image scaling so small it's hard to read anything on various applications.  It started happening suddenly on the 0.9.5 build, It went away after i updated to the newest build (1st time i launched it) Then it came back the day after when launching Mesen again.

2: Yes i know it sounds weird, Let's say i play Super mario brothers and start sprinting all i can, Then suddenly it's like the game accelerates to super-sonic speed with absolutely no chance of having control of anything that happens. It's very random and unpredictable (everything from 1 minute to 1 hour). And no!! the game don't freeze, It pauses/hangs with the audio looping for about 2-3 seconds.

First i had a suspicion it could be my external drive, But after testing it on a internal drive it still had this issue.

Hope you can find something useful in all my ramblings.

**Comment by SourMesen** [comment]
The game accelerating after a freeze is normal, it's trying to make up for the time it was frozen.  The real question is why it's freezing in the first place, but I'm not quite sure what could be causing it.  As a random guess, can you try this build (https://www.mesen.ca/MesenTest.zip)?  It disables a background task in Mesen that could potentially be linked to the freeze up issue, but hard to say.

For the emulator leaving fullscreen mode, just to clarify, are you saying that if you open up Mesen (without a launcher, etc) and then load a game, it enters fullscreen mode and then goes back to window mode instantly?

**Comment by EmuMonkey** [comment]
For the emulator leaving fullscreen mode, just to clarify, are you saying that if you open up Mesen (without a launcher, etc) and then load a game, it enters fullscreen mode and then goes back to window mode instantly?


Both, It does/did it when manually launching Mesen and also when using a front-end like launchbox, If i launched mesen from mesen.exe it would start out in windowed mode, after i hit F11 to enter fullscreen it would jump back to windowed after a few seconds. But if i launched from launchbox with a fullscreen command-line it would begin in fullscreen and the reverting to windowed after about 5-10 seconds, And it keeps changing back everytime it enters fullscreen.

according to the freezing/acceleration part it does both also, The emulator can also decide to just accelerate suddenly without hanging/freezing, And it mostly happens when something is fast-paced in a game.

regards.

**Comment by SourMesen** [comment]
Could you test if the latest dev build fixes the freeze/acceleration problem?
https://ci.appveyor.com/api/buildjobs/0mfo4s3s8bnwaju2/artifacts/MesenDevWin-0.9.7.63.exe

**Comment by SourMesen** [comment]
Good to know the freeze issue is fixed!

For the fullscreen issue, my suggestion would be to NOT use exclusive fullscreen.
Exclusive fullscreen automatically ends if the window loses focus (e.g because of a notification, another application, the user pressing the windows key, etc.) - there isn't much I can do about it.

The regular fullscreen mode should work just as well (in fact, it tends to work better than exclusive fullscreen on my end - it has less input lag), and should avoid the issues with fullscreen mode suddenly exiting.
