### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by haboutnnah** [SourMesen/Mesen#548]
I have just installed Mesen for the first time and there was audio, but then I closed it and now there is none. I tried nuking all settings but the issue persists.

**Comment by SourMesen** [comment]
In the audio options, there's a dropdown called "Device" that lets you select which audio device outputs the sound.  Have you checked to see if it's using the right device?  I'd suggest trying out all of them just to be sure.

Also, if you haven't tried yet, rebooting your computer might not be a bad idea, either.
