### ISSUE TITLE
Pocket Games 150 in 1

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#55]
ROM launching and works, but games with different graphical bugs. Can you investigate it?

**Comment by SourMesen** [comment]
Thanks for the report.

Unfortunately, I don't have access to the ROM you are talking about.
Could you show me the ROM's info from Tools -> Log Window menu?

For example:
>Loading rom: rom.nes
File CRC32: 0x6A102F20
PRG+CHR CRC32: 0x345EE51A
[iNes] Mapper: 245 Sub:0
[iNes] PRG ROM: 1024 KB
[iNes] CHR ROM: 0 KB
[iNes] CHR RAM: 8 KB
[iNes] Mirroring: Vertical
[iNes] Battery: Yes

**Comment by Arcus87** [comment]
------------------------------------------------------
Loading rom: PocketGames_150-in-1_CoolBoy_Unl_U__33.unf
File CRC32: 0x342A72E7
PRG+CHR CRC32: 0x32F1176B
[UNIF] Board Name: COOLBOY
[UNIF] PRG ROM: 32768 KB
[UNIF] CHR ROM: 0 KB
[UNIF] CHR RAM: 8 KB
[UNIF] Mirroring: Horizontal
[UNIF] Battery: No
------------------------------------------------------
[DB] Initialized - 3009 games in DB
[DB] Game not found in database
[DB] Input: 2 standard controllers connected
------------------------------------------------------
Loading rom: PocketGames_150-in-1_CoolBoy_Unl_U__33.unf
File CRC32: 0x342A72E7
PRG+CHR CRC32: 0x32F1176B
[UNIF] Board Name: COOLBOY
[UNIF] PRG ROM: 32768 KB
[UNIF] CHR ROM: 0 KB
[UNIF] CHR RAM: 8 KB
[UNIF] Mirroring: Horizontal
[UNIF] Battery: No
[DB] Game not found in database
[DB] Input: 2 standard controllers connected

**Comment by RaptorMan83** [comment]
A little request for SourMesen - maybe u can do mapper support for this rom? It have many nice games, i'm already have this one for my famicom

**Comment by SourMesen** [comment]
Thanks, I'll try and add support for this in the near future.

**Comment by SourMesen** [comment]
Support for these boards has been added (2a313a541959fc809bc19c658ae9179ead0e81cb) - will be available in the next release of Mesen
