### ISSUE TITLE
Family Basic Keyboard Mapping window off screen

### ISSUE THREAD

**Issue by dualcam** [SourMesen/Mesen#550]
Options -> Input -> Ext Port -> Family Basic Keyboard -> Setup
Top of the mapping window is off the top of the screen.  Can't see the top row.

**Comment by dualcam** [comment]
Just discovered that the keyboard mapping window initial position is relative to the input settings window.  So if the input settings windows is first dragged down then all the keyboard mapping widows will be visible.

**Comment by SourMesen** [comment]
FYI, this should be fixed by a66b196831107552b099cf5c1c8de8109810acca.
The popup window will always appear on-screen, no matter where the input window is.
