### ISSUE TITLE
Request: 3 mappers support

### ISSUE THREAD

**Issue by deathfoetus** [SourMesen/Mesen#56]
#215, #220 and #236

I checked mapper table, this three are good (not bad, not potentially bad and are support by both emulators Nestopia & Fceux)

**Comment by SourMesen** [comment]
Thanks for the suggestions.
Mapper 215 support was added yesterday (74b4d32)
Mapper 220 will probably be added soon, too.
As for mapper 236, I do not know of any game that actually uses it.

**Comment by Arcus87** [comment]
those all mappers for multicarts, but i'm suppose some games also uses them.

**Comment by SourMesen** [comment]
Mapper 220 support was added (9aa6f1deaf3b9d7eda8013ff36e08fab73488f79).
I have not seen any game using mapper 236, so I will not be adding support for it yet.
Mapper 215 & 220 are supported in version 0.5.2 (released today)
