### ISSUE TITLE
Hex editor or Memory Watch or "Edit iNES Header" for Mesen

### ISSUE THREAD

**Issue by iastSA** [SourMesen/Mesen#57]
I think something of this one will be useful, because fceux already have this (mesen have Debugger)

Or add this all features for Mesen, in near future

**Comment by SourMesen** [comment]
Thanks for the suggestions.
The debugger is a work in progress and the features you mentioned are all features I plan on adding, but I don't know when I'll have the time to do so.

**Comment by SourMesen** [comment]
Closing this since all of these tools are now available in Mesen (as of the latest commit)
