### ISSUE TITLE
Compiling on rpi3b+ 

### ISSUE THREAD

**Issue by Askmewho** [SourMesen/Mesen#571]
I know it an underpowered sbc. and even than it doesnt have an opengl backend i like to try an standalone mesen on raspbian under mesa driver. 
I use standard rpi3 flags. the compiling goes well until this:

/tmp/lto-llvm-d60d9d.o: En la función `os_tmpname':
ld-temp.o:(.text+0x28ad0): aviso: the use of `tmpnam' is dangerous, better use `mkstemp'
clang: error: unable to execute command: Segmentation fault
clang: error: linker command failed due to signal (use -v to see invocation)
makefile:138: fallo en las instrucciones para el objetivo 'InteropDLL/obj./libMesenCore..dll'
make: *** [InteropDLL/obj./libMesenCore..dll] Error 254

thanks for the effort!

I will try another clang version.

**Comment by SourMesen** [comment]
The libretro core should compile on raspberry pis just fine.  For the standalone build though, even if you manage to get it to build, you may have issues at runtime with Mono for the UI.

But well, the last time it was benchmarked, Mesen runs at around 30-40 FPS on a raspberry pi 3.  The mono UI would probably run pretty slowly on that sort of hardware, too.

The specific crash you're getting appears to be a compiler bug with clang, so your options are to try another version of clang or trying to build with GCC instead.

**Comment by Askmewho** [comment]
ok! i will try gcc instead. Yeah, thats ok, but Just I want to try the mesa driver, not the retropie legacy driver. it never "fail" me on performance hahahha

btw, this its an early emulator. could I ask why its so demanding for be a nes emulator? It the only one capable of use hd packs, but seems to me than its pretty demanding to be a nes emulator. sorry if you think than I am being disrespectful with your effort. thanks for the quick answer.

**Comment by Askmewho** [comment]
dammit! even on gcc-8.1 and g++-8.1 it fails on the same step!! 
I will try to figured out how to solve the issue...
if you have something in mind please advice me. thanks anyway. 

/tmp/ccON0gj1.ltrans13.ltrans.o: En la función `os_tmpname':
<artificial>:(.text+0x96a8): aviso: the use of `tmpnam' is dangerous, better use `mkstemp'
cp libMesenCore..dll bin/pgohelperlib.so
cp: no se puede crear el fichero regular 'bin/pgohelperlib.so': No existe el fichero o el directorio
makefile:138: fallo en las instrucciones para el objetivo 'InteropDLL/obj./libMesenCore..dll'
make: *** [InteropDLL/obj./libMesenCore..dll] Error 1

**Comment by SourMesen** [comment]
The gcc crash appears to be different (and may be an issue with the makefile?)

> cp libMesenCore..dll bin/pgohelperlib.so

There shouldn't be 2 dots in the filename here, it should be "libMesenCore.dll"

As for performance, Mesen is fairly comparable to other NES emulators with similar accuracy (e.g puNES has similar accuracy and runs about as fast and it's faster than Nintendulator).  That being said, it's probably not as fast as it could be, but making it a lot faster would probably also require making the code a lot harder to understand/read.

Also, if you're trying to use HD packs, keep in mind they require a lot of CPU time, too, so that's probably going to make things worse on a raspberry pi.

**Comment by Askmewho** [comment]
Well... you were right... I downloaded the source code of a release and was the makefile the problem.

guess what... goes horrible. and the cpu not even goes full load (dont know why)
I will try other flags. Ive had to replace the x86 flags with rpi3 flags (and remove -m32) because the UI needs to set a target. maybe if you make a opengl backend to improve the performance on opengl capable arm gpu's like videocore IV (at least on mesa) it could get better... 

the experiment was fun anyway....I guess.... thanks!

**Comment by SourMesen** [comment]
It's possible the code itself doesn't agree with ARM CPUs (e.g maybe the solutions I've used for locking isn't quite as solid on ARM CPUs, etc.).

What graphical backend is used has no impact on performance - all the emulator does is display a single texture representing the NES' screen, it's probably 0.1% of the CPU time used by the emulator.  Also, the Linux build does already use OpenGL (via SDL2)

**Comment by Askmewho** [comment]
This emulator was a request from a friend of mine than lives on california (i am argentinian) and loves you emulator. He has a more capable sbc, the tinkerboard.  He has a problem anyway. I replace the flags with the tinkerboards and sen him the makefile. He build it and on execute he has a lot of problem... i will send you a pic. He has an old mono, but the same version i have, so, thats could not be the issiue.

**Comment by SourMesen** [comment]
This is a bug that was fixed in b8422ca9564b567eef7159246a533549fd0a1129, and there was also a follow-up minor fix in 439e1d9dd5b225ee51e793c1b1e7d434bc4d1ba1.

So it should be fixed if you use the latest commit.

**Comment by Askmewho** [comment]
good!
