### ISSUE TITLE
4k displays better support? 

### ISSUE THREAD

**Issue by Gregoras** [SourMesen/Mesen#572]
We have 2019 and 4k (3840x2160) displays (especially tvs) are pretty common. Mayby it's time for supporting better scaling methods for this displays?

So NES PPU resution is 256x240 (in PAL region) with some quirks in NTSC version (256x224?). With 8:7 Pixel Aspect Ratio this resolution produce on CRT screen image with something similar to 4:3 aspect.
The best way to displays 240p signal on modern monitors is scaling with integer factor. But modern flat screens suports only 1:1 PAR and reproducing non-square pixel isn't possible. So integer ratio scaling messed up image geometry and using another interpolation bring us blurry image.

4k display, due high dpi, give us possibility for scaling NES images with respect for image geometry and sharpness. We could simply project single game pixel to 56 pixels (8x7) matrix on screen to imitate 8:7 NES PAR.This give us resolution of 2048x1680. This resolution is still less then 50% of 4k screen, but this only way to get clear image with perfect geometry. And on 65" 4k tv is equivalent of ~40" screen.

**Comment by SourMesen** [comment]
I'm not sure what you mean?  Mesen supports scaling up to 10x (or any scale if you go in fullscreen or maximize the window).  This is 2560x2400, which is more than the height of a 4k screen.

If you want a 2048x1680 picture, you can get that, too, by setting the scale to 7 and using the NTSC aspect ratio (a similar question/request was done in #317)

**Comment by retro-wertz** [comment]
think he wants NES to render in 4K natively in wide-screen mode

**Comment by SourMesen** [comment]
As far as I know, there's nothing that needs to be changed for this, so closing this for now.  Let me know if there's something that's missing that prevents you from using Mesen on a 4k monitor, but as far as I know, it should be working properly already.
