### ISSUE TITLE
fullscreen on startup

### ISSUE THREAD

**Issue by VadimOsovsky** [SourMesen/Mesen#574]
is there a way to enable fullscreen on start-up without the need to go fullscreen?

**Comment by SourMesen** [comment]
There is no built-in way to do this, but my suggestion would be to create a shortcut to launch Mesen and use the /fullscreen option to launch it in fullscreen.  e.g:
`Mesen.exe /fullscreen`

**Comment by VadimOsovsky** [comment]
Thank you!
