### ISSUE TITLE
64bit compability issue

### ISSUE THREAD

**Issue by rien333** [SourMesen/Mesen#575]
I noticed the following error while trying to load some external lua library (i.e. `require "posix"`) with Mesen:
```bash
/usr/local/share/lua/5.3/posix/init.lua[...]/lua/5.3/std/normalize/init.lua:936: module 'bit32.bor' not found
```
I understand this error to indicate some incompatibility between Mesen (build from source for the `x64` arch) and my 64bit lua (I'm running a 64bit Linux system without 32bit libs). If something else is at play, then this issue is probabely largely irrelevant and can be closed if you like.

Indeed `Mesen/bin/x64/Release/Mesen.exe` is reported to be 32bit:
```bash
$ file Mesen/bin/x64/Release/Mesen.exe
Mesen.exe: PE32 executable (GUI) Intel 80386 Mono/.Net assembly, for MS Windows
```
I suppose there is a good reason to have this executable be 32bit, but now that basically all large non-windows  OSes (Ubuntu, macOS) are dropping/have dropped 32bit support, it becomes a larger a hassle to keep Mesen running on those systems, as (likely) illustrated by my lua importing issue. 

BTW, importing external Lua libraries initially gave me an error as well because Mesen seems to assume that lua related data is stored in `/usr/local/` instead of  plain `/usr/` (the Arch Linux default). (Maybe worth an other issue?)

**Comment by SourMesen** [comment]
Mesen is not 32-bits unless you specifically compile it to be, it defaults to compiling in 64-bits and on any 64-bit computer it will run as 64-bits.

The report you're getting is likely just incorrect because the .NET UI is set to run in either 32-bit or 64-bit, but favors 64-bit whenever the OS is 64-bit.

I've never tried importing external Lua libraries, so I can't say what might be wrong there.

**Comment by rien333** [comment]
> The report you're getting is likely just incorrect because the .NET UI is set to run in either 32-bit or 64-bit, but favors 64-bit whenever the OS is 64-bit.

Are you referring to the information reported by `file`? Is it some kind of binary that contains both 32bit  and 64bit architectures,  or can run in both? 

lf you're not referring to the information provided by `file`, I wonder why the exe is reported to be 32bit.

**Comment by SourMesen** [comment]
The official release builds of Mesen are 1 single .NET executable that can run in either 32-bit and 64-bit modes (and will favor 64-bit when available). This .exe file contains 4 different native binaries (the C++ core): 64-bit windows, 32-bit windows, 64-bit linux, 32-bit linux, which allows the same file to be run on all supported architectures.

I was referring to the `file` report, yes.  I'm not familiar with that tool, but I'm assuming it's just reporting partial information about the .NET binary in this case (or maybe that's just how it reports all .NET binaries, without checking if they're set to 32-bit/64-bit/Any CPU

**Comment by rien333** [comment]
Allright, thanks for the clarification. Weird how `file` reports somewhat misleading information. I'll look into why it does this, but I think the issue can be closed.
