### ISSUE TITLE
Game Genie Encoder/Decoder

### ISSUE THREAD

**Issue by cyperium** [SourMesen/Mesen#576]
For us that create game genie codes it would be great to be able to input address, value and compare and get a game genie code, this could be done in the cheat tool, by encoding/decoding on-the-fly.

The request should optimally work the same as in fceux.

**Comment by SourMesen** [comment]
Thanks for the request!
The cheat window will now auto-convert to/from game genie/pro action rocky/custom codes whenever a conversion is possible, while you type.  (fixed by a29cc4c8d0a0759c06a2d1065fffd559f9f2f735)
