### ISSUE TITLE
game translation

### ISSUE THREAD

**Issue by VadimOsovsky** [SourMesen/Mesen#577]
## Hello, SourMesen!
I'd like to ask for an alternative for rom file translation, that would be something like text overlay, a combination of hd pack builder and text hooker.
This would be very useful since there are numerous limitations for rom hacking. Take the fds version of the Legend of Zelda as an example, there is an English translation for it and the guys did an amazing job translating it, but due to the game's limitations the dialogs turned out to be very squeezed and as a result lost a lot of original color.
After coming across your emulator I regained interest in emulation, and thinking of switching back to emulators from original consoles due to different extra features the emulation provides. So this would help us easily translate a game into any language without learning rom hacking and with no limitations.

**Comment by mkwong98** [comment]
Once I used conditions to check which scene is currently shown and replaced Japanese text with English in the story scenes in Double Dragon II Japanese version so I'm very interested to your idea. Can you explain how the text hooker and the HD pack would work together?

**Comment by SourMesen** [comment]
This sounds a bit like what was suggested in #423.
The problem I see with this is that it locks down the translation to being used with Mesen which is far from ideal when considering portable devices and the like.  Locking down a translation to a single emulator when translating can take hundreds of hours depending on the game isn't really a good idea.

**Comment by VadimOsovsky** [comment]
Man, your emulator is already miles better than any other, when i was testing different emulators on an input lag (cuz this was the main reason why i switched to original hardware), i was very impressed. I really hope that most people will be using yours. If you implement this feature and set a standart for a translation format that will make the translating less constrained and more accessable than rom hacking, a lot of people would love it and I even think other emulators might soon follow your idea!

**Comment by VadimOsovsky** [comment]
> Once I used conditions to check which scene is currently shown and replaced Japanese text with English in the story scenes in Double Dragon II Japanese version so I'm very interested to your idea. Can you explain how the text hooker and the HD pack would work together?

This may not necessarily be the HD pack bulder, what I was talking about is some sort of overlay to cover the original text. The only thing im concerned about is that in most games text is programed to appear letter by letter, usually with a sound, not really sure how to solve that, maybe try to extract the sound and play it manually while muting the in-game text sound, but I'm not sure it's possible. Gosh, I wish I knew assembly...

**Comment by VadimOsovsky** [comment]
But anyway rom hacking has NOT proven to be the best way of translating early games due to their limitations, so at the moment the only possible solution to get a high quality translation for a mortal (aka a person who doesn't know an assembly language) without disassembling the whole game is only through such trickery as overlaying. Although maybe in future we'll get rom translating utils that will simplify the job and make it accessable and without limitations.

**Comment by mkwong98** [comment]
Instead of HD pack, I think Lua script will do a better job at catching which message is being shown and displaying the translation as subtitles on screen or in another window. No rom hacking is needed and Lua script should be able to handle messages with dynamic names and numbers.

**Comment by SourMesen** [comment]
For now, I'm still of the opinion that it is better for translations to be done through rom hacking, even if it is more difficult that way.  This ensures that the translation is usable on a wide variety of systems, and works on any NES emulator in the future, rather than locking it down to just Mesen, which may not be available on all platforms, and may not always be what people can use or want to use.
