### ISSUE TITLE
Request: Remember current view in debugger

### ISSUE THREAD

**Issue by cacciatc** [SourMesen/Mesen#578]
When using the debugger I almost always want to be in source code view (CTRL-Q). It would be nice if Mesen remembered my last used view. Or perhaps I could set it as the default (maybe there is already a way?)

Thanks!

**Comment by SourMesen** [comment]
I'm guessing you're using the 0.9.7 release?  The latest dev builds should be doing this already, it was implemented a month or so ago, I think.

**Comment by cacciatc** [comment]
Yep, I am. Cool will check out the dev builds.
