### ISSUE TITLE
Request: Option for auto region detection to use rom name

### ISSUE THREAD

**Issue by retrorepair** [SourMesen/Mesen#579]
I was wondering how trivial it'd be to add an option to override header region detection to use the (region) tag in the rom file name?

A lot of roms are either (world) or (usa, europe) and auto detection will always default to ntsc in these cases.

I have all my roms in region folders and use CRT switching and it's a bit of a pain that some of these games default to ntsc.

I imagine I wouldn't be the only one in this situation?

**Comment by SourMesen** [comment]
The header doesn't have NTSC/PAL information in 99+% of cases, the code already relies on either the internal game database or the filename (if not found in DB) to select the region.
When a game isn't in the DB, the code looks for the following tags to set the game to PAL: "(e)", "(australia)", "(europe)", "(germany)", or "(spain)"

I'm not sure why you would expect "(world)"/"(usa, europe)" games to default to PAL, though? Usually this means the game was either unmodified for its PAL release or it detects NTSC/PAL and auto-adjusts, in both scenarios NTSC most likely makes the most sense from a gameplay perspective in those cases.

**Comment by retrorepair** [comment]
I don't necessarily want it to default to pal, just to whichever (tag) is in the filename. I have a folder for each and all games have either the (europe), (japan) or (usa) tags depending on the folder.

I like playing the games in the original format, I think its great that you can and personally that's how I remember playing them so prefer it.

Either way, it'd be helpful if the auto detection could be optioned to prefer filename over database I think.

**Comment by retrorepair** [comment]
By the way, I disabled the database and it still set it to ntsc, even though the filename (.zip and .nes) have the (Europe) tag.

**Comment by retrorepair** [comment]
Confirmed filename region setting is broken in current libretro build under Xenial (16.04).

With database disabled (all data removed), all roms default to NTSC regardless of header or filename designations with the Auto region setting.

**Comment by retro-wertz** [comment]
When a game isn't in the DB, the code looks for the following tags to set the game to PAL: "(e)", "(australia)", "(europe)", "(germany)", or "(spain)"

> Confirmed filename region setting is broken in current libretro build under Xenial (16.04).
> 
> With database disabled (all data removed), all roms default to NTSC regardless of header or filename designations with the Auto region setting.

broken? or do you have wrong filename tags (case-sensitive)

`When a game isn't in the DB, the code looks for the following tags to set the game to PAL: "(e)", "(australia)", "(europe)", "(germany)", or "(spain)"`

**Comment by retrorepair** [comment]
Broken. I've tried all the options there and none work regardless of case. I initially thought that too.

**Comment by SourMesen** [comment]
Thanks - that was a regression from when I implemented VS Dual System support a year ago.  The filename tags I listed earlier should now have an impact when loading games that aren't in the database.

As for adding an option to override the DB to use the filenames, I'm not quite sure it's useful - the majority of games have different CRC values depending on whether it's the PAL or NTSC version, licensed games that are identified as NTSC in the database and have a PAL release with the exact same code should be relatively rare, as far as I know..

You can also modify the rom's header to force it to play as PAL, rather than NTSC.  NES 2.0 headers override the contents of the database completely.
