### ISSUE TITLE
Instruction taking longer than expected

### ISSUE THREAD

**Issue by domgetter** [SourMesen/Mesen#580]
I was trying to learn why SMB3 has the little visual glitch above the menu bar, and when checking the timing of the interrupt routine, I noticed a variation in the number of cycles that would run.

Sometimes the `TYA` and `PHA` instructions take longer than expected.

<img width="947" alt="before_7_cycles" src="https://user-images.githubusercontent.com/971452/53009951-3e38ce80-3402-11e9-8b14-265f504e02a0.png">

Here we can see that the cycle count is at 78255192, and `PHA` takes 3 cycles, so running one instruction should put the cycle count at 78255195, but as we can see here:

<img width="947" alt="after_7_cycles" src="https://user-images.githubusercontent.com/971452/53010039-6de7d680-3402-11e9-8354-05aa68cb3298.png">

The cycle count is now at 78255199, and `PHA` took 7 cycles for some reason.

On some runs they take the expected amount of time, sometimes `PHA` is longer, and sometimes `TYA` is longer.

Let me know if you want more screenshots of this behavior.

**Comment by SourMesen** [comment]
My first guess would be that the DMC channel's DMA is pausing the CPU to perform its data transfer at that exact moment, causing it to jump from 3 to 7.  I'm pretty sure SMB3 uses the DMC channel?

**Comment by domgetter** [comment]
Ah, yes, the additional cycles coincide with DMC timer running down to 0.
