### ISSUE TITLE
Why does Mega Man 2 have sound problems with Game Genie

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#581]
Why is it on the real NES if you use a Game Genie you will have sound issues on Mega Man 2?

**Comment by SourMesen** [comment]
http://forums.nesdev.com/viewtopic.php?t=3426
Essentially, the game genie changes the power on state, and megaman relies on that power on state (e.g it doesn't properly initialize every sound register, so the game genie's menu permanently affects the way the music sounds)

**Comment by Cibomatto2002** [comment]
Thanks I had no idea what was going on.
