### ISSUE TITLE
Crash when attempting to play movie with no game opened

### ISSUE THREAD

**Issue by Nallebeorn** [SourMesen/Mesen#585]
Version: 0.9.7
OS: Windows 10

Whenever I attempt to open/play a .mmo movie file while no game is opened, Mesen crashes with a System.AccessViolationException error. This happens when trying to play a movie from the game select screen, as well as if Mesen is associated with .mmo files and the file is opened directly. It doesn't seem to matter *which* game I'm in, as long as something is loaded. Full error message and stacktrace below:
![image](https://user-images.githubusercontent.com/7013489/53485075-923c5680-3a85-11e9-9b44-fc78b1eaca8b.png)

**Comment by SourMesen** [comment]
Thanks for the report!
This is fixed by f5bee853c77bd70e729682a7655e0900189dd022
