### ISSUE TITLE
Mapper 186 doesn't emulate the tape drive

### ISSUE THREAD

**Issue by abridgewater** [SourMesen/Mesen#587]
"Master using it and you can have this."

[studybox.org.txt](https://github.com/SourMesen/Mesen/files/2920256/studybox.org.txt)

More seriously, this includes a description of the tape data encoding, the overall sequences for controlling the tape drive and reading data, and a bunch of other guesswork. There's quite a bit left to figure out, of course, but this should be a good start.

**Comment by SourMesen** [comment]
Thanks for taking the time to investigate this and document it!
I'm somewhat busy with another project atm, but hoping to get around to this in the not-so-distant future (although it will probably have to wait until after I release 0.9.8)

**Comment by SourMesen** [comment]
And it's finally done!
Thanks again for all the help on this one, would never have figured this out on my own :p
