### ISSUE TITLE
a problem with Castlevania romhacks

### ISSUE THREAD

**Issue by RandomGuyWhoBreathes** [SourMesen/Mesen#588]
when I load the IPS for any romhack (Castlevania specifically, maybe not for ALL games) it says that the OP failed and the CPU crashed. I can't find the solve anywhere on the internet and I can't fix it myself, please help!

**Comment by retro-wertz** [comment]
read the documentation that came with the patch/hack. it should include the correct rom to use (based on hash crc/md5) and if the patch requires the rom to be headered or not.

**Comment by SourMesen** [comment]
I can't help you with specific rom hacks - if they don't work, either the hack itself is incorrect (e.g maybe it doesn't work on real hardware, for example), or you applied it to the wrong ROM.
