### ISSUE TITLE
Auto Save State feature continues saving even when emulation is paused

### ISSUE THREAD

**Issue by Bohman-Timothy** [SourMesen/Mesen#589]
Bug: Automatic state saving continues even when the emulation is paused. Saving state at specified increments should only count the time that the game emulation is active. Currently, the save state is recreated multiple times (despite being the *same* state) if the game is paused long enough.

I'm using: Mesen version 0.9.7 on Windows 10.

**Comment by SourMesen** [comment]
This is fixed by 246e8a2c0a92076c9fad4d39f0233563c94728c7 - time is no longer counted while the game is paused.
