### ISSUE TITLE
Import all cheats at once/ Random game

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#59]
Can you please add import all cheats at once I have so many to import. :). Can you add random game let the emulator choose what game you play.

**Comment by SourMesen** [comment]
Thanks for the suggestions.

However, importing all the cheats is not something I want to add - it makes the cheats window hard to use and has potential performance implications.  Importing cheats from the DB for a new game is just 3 clicks - it's not that bad :)

As for the random game option, I've added a "Load Random Game" option in the Tools menu, it's not perfect though.  It will ignore zip & 7z files (performance concern) and can only find games in folders that you have loaded your last 10 games from.  For the most typical scenario (a single folder containing all games), it should work fine, though. (2cbae24ded05dfb4aff0a46ca0ec1c5ac862a1a4)
