### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by LordEcnelis** [SourMesen/Mesen#592]
So there are games that have the right aspect ratio (without black boards), like Castlevania or Contra:
![r1](https://user-images.githubusercontent.com/48351793/54023858-cba34f00-4174-11e9-9210-40f7207e0346.jpg)
And there are games with an annoying black border that shouldn't be there:
![b1](https://user-images.githubusercontent.com/48351793/54024088-73208180-4175-11e9-8f9f-e64e7fe3c20e.jpg)
![b2](https://user-images.githubusercontent.com/48351793/54024091-73b91800-4175-11e9-80bd-bec4bd690994.jpg)
No matter what filter or aspect ratio I choose, I can't get rid of these black boards, but I know that they're not present on the original games, as we can see in some YouTube videos, for example:
https://www.youtube.com/watch?v=ff3fjUCCVac
https://www.youtube.com/watch?v=ueeKMQSS4bw
Any ideas on how I can get rid of these black boards? Sorry for my horrible english ;/

**Comment by cyrilleCh** [comment]
It's normal black strip present on original games. Your videos aren't full screen and hide black strip (like overscan on TV CRT).  You can custom overscan for specific games with Mesen :)

**Comment by SourMesen** [comment]
The overscan options in Video->Overscan are what you are looking for.
All NES games have a 256x240 resolution, and those black bars are a part of it - NES games rely on the fact that CRT TVs will hide a portion of the screen at all times to hide those black bars.  This is what the overscan settings are there for.
