### ISSUE TITLE
Mapper30 4-screen not working correctly

### ISSUE THREAD

**Issue by michel-iwaniec** [SourMesen/Mesen#593]
Black Box Challenge, a 4 screen game, does not work correctly with Mapper30. The title screen displays incorrectly, and so does the intro. Most likely due to misinterpreting the iNES header flags for Mapper30.

The slightly-hacky-standard for Mapper30 is to define 1-screen vs 4-screen in the iNES header based on whether the mirroring bit set to H / V. 
Basically 4-screen mirroring should be used when the 4-screen mirroring bit is set to 1 and the H / V mirroring bit is set to 1. And 1-screen mirroring (controlled through register) should be used when the 4-screen mirroring bit is set to 1 and the H / V mirroring bit is set to 0. When the 4-screen mirroring bit is set to 0, standard H / V mirroring applies.

More details can be found here:
http://wiki.nesdev.com/w/index.php/UNROM_512#Nametable_Configuration

The game can be freely downloaded here:
https://slydogstudios.org/r/Black%20Box%20Challenge.nes

**Comment by SourMesen** [comment]
Thanks for the report!
This should be fixed by 03f160a949f361e08c5e05b4e68da88658312ade
