### ISSUE TITLE
The opening screen of Dark Seed (Unl) is broken

### ISSUE THREAD

**Issue by kurayami6** [SourMesen/Mesen#594]
Here it is in Mesen

![Capture](https://user-images.githubusercontent.com/31968468/54066430-b49f5280-4283-11e9-8ed2-e194f9fbd701.PNG)

And here it is in fceux

![Capture2](https://user-images.githubusercontent.com/31968468/54066435-c5e85f00-4283-11e9-9338-d8cee5be9cc7.PNG)

**Comment by SourMesen** [comment]
Thanks for the report - looks like another case of a game not initializing memory properly, though.  If you set the ram to initialize to 1s instead of 0s, the problem disappears, and if you set it to random, other random pixels on the screen are sometimes glitched.
