### ISSUE TITLE
Remove splite limit glitch

### ISSUE THREAD

**Issue by ImJezze** [SourMesen/Mesen#60]
When the option "remove sprite limit" is activated sometimes you can see glitches and they flicker when you pause the game (not pause the emulation).

Here is an example of Castlevania III, look at the wipe.

![removed-sprite-limit-glitch](https://cloud.githubusercontent.com/assets/11963815/20247205/6f93c7b4-a9c6-11e6-9e4d-ad906b7a6251.png)
(left w/ sprite limit, right w/o sprite limit)

Similar glitches are visible in other games too.

**Comment by SourMesen** [comment]
Thanks for the bug report!
This should be fixed by 98e6a83c15d72a68f501e80725f0cb97d86115c9
