### ISSUE TITLE
Nuke.YKT VRC7 instruments dump

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#600]
Instruments was dumped by Nuke.YKT some days ago (no rhythm mode ones yet)

1)
https://github.com/TASVideos/fceux/commit/45dcb3e2426641775e89c6a984481787ffb543ab

2)
https://freenode.irclog.whitequark.org/~h~yamahasynths/2019-03-15#24228789;

3)
https://siliconpr0n.org/archive/doku.php?id=vendor:yamaha:opl2#ym2413_instruments

**Comment by SourMesen** [comment]
Thanks for the info!

The values has been updated in c241eb56c4e62937c6d3e7735f9e8ecb411b91e2

**Comment by eugene-s-nesdev** [comment]
Rhytms is dumped too, but it unused (VRC7 chip lacks this output)
https://github.com/bbbradsmith/nsfplay/commit/2541a7f544d625870afcd712416d5228f95f6c61
https://github.com/bbbradsmith/nsfplay/commit/072cb73b779eb49235335486a1be5d269d36cf8f
