### ISSUE TITLE
FDS disk access sound support

### ISSUE THREAD

**Issue by rzumer** [SourMesen/Mesen#604]
It is a common emulator feature for systems that support disk formats to provide an audio indicator of disk access by including or allowing users to add their own disk drive audio samples. I could not find any sign of such a feature in Mesen, so I would like to submit it as a feature request. Since FDS titles usually load in large chunks with a visual indicator, it is not very important, but it would be nice to have nonetheless.

**Comment by torridgristle** [comment]
Aw, that'd be cute. I've got Mesen set up to fast-forward through loading but there's still enough time for a little sound.

**Comment by SourMesen** [comment]
While I understand that this might be interesting to some people, I don't believe it's worth the extra code complexity. Sorry!
