### ISSUE TITLE
Mesen doesn't appear in Taskbar sometimes

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#605]
When I open a ROM and Alt+Tab over to a different program so that Mesen isn't in focus when it opens, Mesen won't appear in the Taskbar (Win7) until I focus on the Mesen window by Alt+Tabbing to it or clicking on the window.

**Comment by SourMesen** [comment]
That's odd, I don't actually do anything to control whether or not it appears in the taskbar, so it sounds like it might be a WinForms issue.  Probably related to this: https://stackoverflow.com/questions/659506/what-causes-a-window-to-not-appear-in-the-taskbar-until-its-alt-tabbed-to-in-vi

Do you have the option that prevents the mouse from resizing the window turned on? Based on that stackoverflow thread, that option could potentially be triggering the problem.

**Comment by torridgristle** [comment]
Yeah, I've got that enabled. That seems to be causing it; when the option is enabled it won't show up in the taskbar until I focus on the window, but with it disabled it always shows up in the taskbar.

**Comment by SourMesen** [comment]
This should be fixed by 510353cd7a3904f27675d4510b7d5e38b2150684
