### ISSUE TITLE
Graphical glitch/bug in Double Dragon /w and /w-out sprite limit

### ISSUE THREAD

**Issue by MickeyMentol** [SourMesen/Mesen#61]
![double dragon u _000](https://cloud.githubusercontent.com/assets/23460052/20276813/996a22f0-aaa6-11e6-8d87-05cf0c36a998.png)

In lower right corner u can see a little glitch/bug in DD1

**Comment by SourMesen** [comment]
Thanks for the report!
This is actually a known bug in the game itself, not an emulation bug.
> **Double dragon**
A garbage sprite (Probably sprite-0 hit?) can be seen on the lower right of the game screen.
http://wiki.nesdev.com/w/index.php/Game_bugs
