### ISSUE TITLE
Ai Senshi Nicol FDS issue

### ISSUE THREAD

**Issue by pixelslivewallpaper** [SourMesen/Mesen#611]
Hi!

I've found an issue when level 3 was loaded.

![1](https://user-images.githubusercontent.com/14002440/55878083-9f278c00-5b93-11e9-9a1c-0a54fb9f9c9d.png)

![2](https://user-images.githubusercontent.com/14002440/55878088-a353a980-5b93-11e9-995d-fd3c50b088cb.png)

Game: Ai Senshi Nicol (Japan) [b].fds (1b303d37).
Save states:
[Ai Senshi Nicol (Japan) [b]_3.zip](https://github.com/SourMesen/Mesen/files/3063730/Ai.Senshi.Nicol.Japan.b._3.zip)

Can you include an option that allows us blowing into the cartridges or disks?... just kidding :)

Thank you.

**Comment by retro-wertz** [comment]
[b] means a bad rom dump. but this probably a rom issue since i do have
this stage3 issue in fceux using no-intro verified rom. sometimes it works
sometimes not.

**Comment by pixelslivewallpaper** [comment]
Yes, using the level select code you can jump straight forward to stage 3 and it loads ok.

![Ai Senshi Nicol (Japan)  b _014](https://user-images.githubusercontent.com/14002440/55897020-a06ab000-5bb7-11e9-95c0-9af2ac00402f.png)

Maybe this issue should be closed.


Thanks for the support.

**Comment by SourMesen** [comment]
Since you haven't gotten the problem with the proper dump (e.g one that's not marked as [b]), I'll close this for now - let me know if you get the same issue with the correct rom.
