### ISSUE TITLE
dragging tile from one bank to other

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#612]
Hi dear Sour,

When I tried to drag a tile from the bottom bank to the upper bank (I though I can copy tile from bank to bank). An error occurred :

![image](https://user-images.githubusercontent.com/37517008/55983103-412d9e00-5c92-11e9-8703-4ab59e6e5319.png)

Build: 0.9.7 (Latest Stable).

**Comment by SourMesen** [comment]
Thanks for the report - this was already fixed by another change done in between 0.9.7 and 0.9.8.
