### ISSUE TITLE
Screenshots do not save when loading roms from compressed .zip files

### ISSUE THREAD

**Issue by Apocalypse612** [SourMesen/Mesen#613]
Just as the title says - when loading a rom from a compressed .zip file, the screenshot will not save. It says it saves screenshot 00, but it does not. Repeating this action will re-attempt to save screenshot 00 and continuously fail from my tests. 

Save functionality works just fine if you unpack the rom. I'm unsure if this issue affects other compressed file formats that hold roms (if additional ones are even supported).

Thanks

**Comment by SourMesen** [comment]
Thanks for the report - this should already be fixed in the latest dev builds (it was reported/fixed in #512)
