### ISSUE TITLE
Feature Request: Force PPU Mask to draw left 8px

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#615]
I've made a few cheatcodes to make games draw the left 8px of BG and Sprites since sometimes games look fine.

There should be an option to force this behavior without working out cheat codes, and perhaps on a per-game basis. Or a global option with per-game overrides, like the way overscan cropping is handled.

**Comment by jackwilsdon** [comment]
Is this not already supported? (Force background display in first column / Force sprite display in first column)

![Screenshot from 2019-04-12 23-57-29](https://user-images.githubusercontent.com/1843197/56070249-c0989b80-5d7e-11e9-8697-ae012fb2d2e4.png)

**Comment by SourMesen** [comment]
Yes, this is already supported.
I don't think this is useful enough to warrant the extra code/UI complexity overhead of adding support for per-game settings, though.
