### ISSUE TITLE
View Tile in chr , hardly know where it is

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#617]
Hi dear Sour, 

When I right click on a tile in the NameTable, then I choose to view it in chr , a square in gray appears to show you where the tile is .While most of the chr is small chunks , I can hardly see that gray square .

Kindly , if you can change it's manner , maybe add 1px to that square in red or maybe an animation to know where it is , thank a lot :D

**Comment by SourMesen** [comment]
Thanks for the suggestion. I've made some minor changes and changed the color to red, so hopefully it's easier to see now.
