### ISSUE TITLE
[Feature Request] Support for (more) dip switches

### ISSUE THREAD

**Issue by Anuskuss** [SourMesen/Mesen#618]
There are non-VS games which have dip switches (like [Nintendo World Championships 1990](https://www.mariowiki.com/File:Standard_Cartridge_-_Nintendo_World_Championship.jpg) and some Camerica games) but Mesen doesn't support them AFAICT.

P.S. Nestopia already got it down if you need some reference.

**Comment by SourMesen** [comment]
Thanks for the request - this is already possible in the latest dev builds (since 72fc0de3832910bff796d95e57342b3716dd2975), although it doesn't offer any documentation for the dipswitches beyond the number of available switches.

You can try it out by using one of the recent appveyor builds (linked in the readme)

**Comment by Anuskuss** [comment]
My bad, thank you for implementing this!
Are you aware of any resource which documents carts with dip switches and their respective usage or would you be interested in creating a small db and documenting that yourself? There shouldn't be too many carts that come into question and having a small description of what the switches do would be really handy.

**Comment by SourMesen** [comment]
Nestopia has a lot of them, but they're hardcoded in the code in various places, so finding/extracting all of them would require some work.
The dipswitches in Mesen are all defined here: https://github.com/SourMesen/Mesen/blob/a13f2dd3a83299c1facbd9b2ce6c7769b6001188/GUI.NET/Dependencies/DipswitchDefinitions.xml
It would just be a matter of adding them here for the non-VS games that have them, but I don't really have the time to try to find all the games and complete that DB at the moment.
