### ISSUE TITLE
[Feature Request] 4 Channel Audio Output

### ISSUE THREAD

**Issue by TayVerde** [SourMesen/Mesen#619]
Would it be possible to add 4 Channel audio output to Mesen?

The reason behind this is I would like to isolate the different NES audio channels in a live playback setting.  The existing Channel mixer has all the functionality need but the panning window would need more options.

I am open to programming this functionality myself. Any help in the right direction would be greatly appreciated!

**Comment by SourMesen** [comment]
It shouldn't be overly hard to add, but I'm not sure the added code/UI complexity is worth it considering it's very unlikely to be used by most people (I'd imagine channel panning is probably not used much as it is).

If you want to try implementing it (at the very least for your own use), you want to look at SoundMixer.cpp, that's essentially where all the code for panning is at the moment.  Look at where the _hasPanning flag is set/used and you should have a pretty decent idea of how it's done right now.
There's also some work that needs to be done in Windows/SoundManager.cpp and/or Linux/SdlSoundManager.cpp depending on your OS

The UI is in frmAudioConfig.cs, and AudioInfo.cs holds the saved config + sends it to the C++ core via function calls in InteropEmu.cs file.

Hope that helps!

**Comment by TayVerde** [comment]
Awesome!

Thank you so much! That's definitely the info I need to get started! I will let you know if I get it running!
