### ISSUE TITLE
$AD isn't displayed in the hex viewer's ASCII column

### ISSUE THREAD

**Issue by zorchenhimer** [SourMesen/Mesen#620]
The ASCII for hex value `$AD` is not displayed in the ASCII column in the memory viewer:

![combined](https://user-images.githubusercontent.com/6540297/57036078-493d8580-6c21-11e9-9027-809ab64655bc.png)

An exaggerated example:

![image](https://user-images.githubusercontent.com/6540297/57036138-6d00cb80-6c21-11e9-8b05-2ce877b56361.png)

This is using version DevWin-0.9.7.104.

**Comment by SourMesen** [comment]
Thanks - for some reason the open source component that the hex editor is based on displays dots only for characters in the $7F-$A0 range, and tries to display characters for stuff above $A0, but that doesn't make too much sense in a ASCII/UTF8 context.

I've changed it to display dots for $7F-$FF, inclusively.  A TBL file can be used to customize that range with reasonable characters if needed.
