### ISSUE TITLE
The "Engage Ridley" code in Metroid doesn't work 

### ISSUE THREAD

**Issue by kurayami6** [SourMesen/Mesen#622]
Typing in the code on a real NES turns the game into a broken, glitchy mess. In Mesen however it just causes the emulator to crash with an invalid op code error. 

![Capture](https://user-images.githubusercontent.com/31968468/57138000-db49b780-6df4-11e9-9e45-872f7bdb2936.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/57138019-e7357980-6df4-11e9-8ece-7e225cefe9d1.PNG)

![Capture3](https://user-images.githubusercontent.com/31968468/57138029-edc3f100-6df4-11e9-8967-0aed2b23d1f8.PNG)

**Comment by tvoybro** [comment]
Hmm, it's funny but same thing happens with Nestopia 1.40, fceux 2.2.3.

**Comment by SourMesen** [comment]
The "Invalid OP code - CPU crashed" message is Mesen's way of saying that an opcode that has unstable/unreliable on hardware or outright freezes the processor was executed. Entering this particular password causes the game "crash" and start executing invalid code - how these unstable opcodes behave on hardware is hard to predict (and might also vary from one chip to another)

There probably isn't really much to be done here - the exact behavior you get on hardware may actually vary from one console to another, too.

**Comment by kurayami6** [comment]
But it shouldn't crash the emulator every time, should it? Since it doesn't crash a real NES every time.

**Comment by jackwilsdon** [comment]
I'm pretty sure it hits undefined behaviour in the real CPU, as @SourMesen said it's "hard to predict" how the invalid opcodes behave on real hardware.

**Comment by MoochMcGee** [comment]
@SourMesen If you're referring to the XAA opcode, it is SEMI-predictable. The Visual 6502 wiki has some info on it from various 6502 chips and environments, I'm pretty sure.

**Comment by SourMesen** [comment]
I wasn't referring to any particular opcode.  Mesen doesn't crash on XAA (though I've apparently never implemented its behavior).  The "cpu crashed" message is only shown for the opcodes listed as "STP" on the nesdev wiki.

**Comment by kurayami6** [comment]
Turns out the code works perfectly in Nintendulator. I wonder what it's doing that Mesen isn't.

![Capture](https://user-images.githubusercontent.com/31968468/60731437-e5ba3600-9f8a-11e9-9383-1928ef57d577.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/60731444-e9e65380-9f8a-11e9-9ce2-24bccb50f051.PNG)

**Comment by SourMesen** [comment]
According to this post (https://forums.nesdev.com/viewtopic.php?p=183605#p183605), the game locks up to a black screen on a metroid cartridge running on a NES for multiple people that tested it.  So it looks like the glitched graphics are more likely to be something caused by emulators than anything else.
