### ISSUE TITLE
[Feature Request] Softpatching for the libretro core

### ISSUE THREAD

**Issue by Papermanzero** [SourMesen/Mesen#626]
Currently the mesen core does not support softpatching for ips files.
https://docs.libretro.com/guides/softpatching/

Softpatching has the benefit to apply patches on the fly without changing the roms itself.
Therefore it would be a great feature to keep the NES rom library untouched but to apply translation or modifications to the games.

**Comment by SourMesen** [comment]
That list is out of date, softpatching has been supported since last august with this commit: 47ba3f828276d7cc3547d12f669aa24df31d7f05

**Comment by retro-wertz** [comment]
Correct. retroarch native soft-patching works with Mesen

![Screenshot_2019-05-13_05-50-46](https://user-images.githubusercontent.com/23315382/57588181-25444300-7543-11e9-9747-eeec99588d0b.png)

**Comment by Papermanzero** [comment]
Thank you :)
