### ISSUE TITLE
Mesen is invisible after a setting change

### ISSUE THREAD

**Issue by SpiderDave** [SourMesen/Mesen#629]
When changing the setting for "Data Storage Location", Mesen tries to restart but doesn't.  Instead it becomes invisible.  I can still hear and control the game, but there's no window.  Have to close it with the task manager.

Windows 7 Pro x64
Mesen 0.9.7 (9/16/2018/7:13 PM)

**Comment by SourMesen** [comment]
Unsure how the location switch could cause this, but the most likely explanation would probably be that the config file saved a window location that is no longer visible on your screen.  Did you change monitors/resolution/etc?

You should be able to use the Window's global "Windows Key"+Arrow Keys keyboard shortcuts to move the window back to your screen.

**Comment by SpiderDave** [comment]
It wasn't in the taskbar either.  I have a second monitor but it wasn't there either.  The only evidence that it was still running was the task manager and hearing the game audio, and having it respond to controller input.

**Comment by SourMesen** [comment]
Thanks for the report - I had misunderstood what you meant the first time around, but was able to reproduce the issue on my end, too.  Fixed by f2401d5bd4ab59e7bb9e1b54cbb0a82a0cd2c4a3 (along with a couple more issues related to this)
