### ISSUE TITLE
Channel bleed through opposite speaker (stereo headphone audio)

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#63]
It would be nice if it was possible to have the right channel bleed through to the left channel at a configurable volume level and for the left channel to bleed through to the right speaker at a configurable volume level. This in addition to the feature request for panning individual audio channels would be awesome.

Basically I want to have it so that in Stereo Audio mode the sounds assigned to the left channel can be heard at 5~% volume out of the right speaker and sounds assigned to the right channel can be heard at 5~% volume out of the left speaker. (NotsoFatso NSF music player for Winamp does this by default for the Triangle channels for example)

This will greatly alleviate problems listening to audio while wearing headphones/imitate sound from desk speakers for those that wear headphones: https://en.wikipedia.org/wiki/Crossfeed

**Comment by SourMesen** [comment]
Thanks for the suggestion.
I added a "Crossfeed" option to the stereo sound options. (2fac266303a2b06a398d4da17999f9df2163b3c3)
It copies a portion (configurable %) of the left channel to the right, and vice versa.
I haven't added the channel panning yet, though.

**Comment by Nicholas-Steel** [comment]
Awesome stuff, thank you :)
