### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by Kucemuroye** [SourMesen/Mesen#631]
I'm not sure if this would be considered a bug but in super Mario bros. (NTSC) there are graphical glitches, although this only happens on the main menu and demo play it would be nice to see this fixed. Also one is where the numbers of the time glitch out but not rendering them unreadable just distracting for me.
![compat 2](https://user-images.githubusercontent.com/51242094/58720853-52954b80-83a1-11e9-9b60-2b1d96f0e9e4.PNG)
![compat 3](https://user-images.githubusercontent.com/51242094/58720867-59bc5980-83a1-11e9-91e3-829970435274.PNG)
![compat 4](https://user-images.githubusercontent.com/51242094/58722073-86be3b80-83a4-11e9-96c1-417034c5fd78.PNG)

![compat 1](https://user-images.githubusercontent.com/51242094/58720784-1d88f900-83a1-11e9-8683-00bed430ce11.PNG)

**Comment by retro-wertz** [comment]
there are smb games that are intentionally bugged like that for fun, this might be one of them.

**Comment by RokkumanX** [comment]
Are we talking about clean verified dumps or Rom-Hacks here?

That have never ever happened to me before and it should definitely not happen with Mesen being one of the most cycle-accurate NES/Famicom/Famicom Disk System emulators in existence.

Super Mario Bros. (everything you need to know)

CRC32: D445F698
MD5: 8E3630186E35D477231BF8FD50E54CDD
SHA-1: FACEE9C577A5262DBE33AC4930BB0B58C8C037F7

**Comment by SourMesen** [comment]
Like the others above have said, this is very likely not a valid dump of SMB.
