### ISSUE TITLE
libretro rotation aspect ratio problem?

### ISSUE THREAD

**Issue by softtwo** [SourMesen/Mesen#636]
No stretch + no overscan crop. At 90 degrees, Retroarch screenshot reports 225x240. I wonder if this should be 240x256?

Can't check standalone atm.

**Comment by SourMesen** [comment]
Probably, but not really much of a concern considering I doubt anybody uses the rotation setting.
I know the cause, but would rather properly test that particular fix before I commit it, so it'll have to wait.

**Comment by Awakened0** [comment]
I opened a report about this on the RetroArch repo: https://github.com/libretro/RetroArch/issues/8876

Noticed it first in FB Neo with rotated vertical games. But it happens in snes9x too. Seems like a frontend issue and not something on the core side.
