### ISSUE TITLE
Feature Request: Mac OS X Support

### ISSUE THREAD

**Issue by chexo3** [SourMesen/Mesen#638]
Mesen and it's dependencies should be able to be compiled for Mac OS X, but I don't have the skills required to turn it into an xcode project, link Mono and SDL, all that stuff.

**Comment by thejunkjon** [comment]
Have you tried this?

// mono for mac
https://www.mono-project.com/docs/getting-started/install/mac/

// sdl 2 for mac
https://medium.com/@edkins.sarah/set-up-sdl2-on-your-mac-without-xcode-6b0c33b723f7

// run Mesen
mono Mesen.exe

I haven't given this a try but I'd imagine it would work just fine.

**Comment by SourMesen** [comment]
Mono support for WinForms on macOS is currently in a pretty bad shape, which is why macOS isn't really supported at the moment.  There are some signs that there might be some progress on WinForms support on macOS in the future, but no real way of knowing when that might happen.

**Comment by chexo3** [comment]
Ah. Maybe another library could be used to replace the functionality of
Winforms? It'd be a bit of work, but it might be a good temporary solution.

**Comment by SourMesen** [comment]
Unfortunately, WinForms is a huge part of Mono (its their implementation of the .NET Framework API) - there is no replacement available.  Until Mono solves the macOS issues with their WinForms implementation, there is not really much that can be done.

**Comment by chexo3** [comment]
Darn.

**Comment by SourMesen** [comment]
Unfortunately, with macOS Catalina removing support for 32-bit applications, Mono's WinForms implementation on macOS no longer works at all (since it was based on an older 32-bit only API).  Until someone writes a 64-bit WinForms wrapper for Mono, macOS support is unlikely (the only option left at the moment is Wine, and that has its own issues, too.)
