### ISSUE TITLE
Bart vs. the Space Mutants (USA) (Rev A)

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#64]
When you die on the game the bottom of the screen will jump. Here is a video. Tried in FCEUX and it does not jump.

https://www.youtube.com/watch?v=VDG0WWinPkU&feature=youtu.be

**Comment by SourMesen** [comment]
Thanks for the report.
I took a quick look at it and it looks like a timing issue.  It'll be hard to fix without breaking something else in the process, so could be a while before I have a fix for this.

**Comment by SourMesen** [comment]
This is fixed by 17d75287bd0f643d5e599b3f6dbee777e89a7653
