### ISSUE TITLE
FDS game don't re-launch, after 0.9.8 launched.

### ISSUE THREAD

**Issue by io3432iooivzs** [SourMesen/Mesen#646]
Hi,
I compiled 0.9.8 on Debian/Buster.
Mono updated by official site's repositry.
But FDS game couldn't launch.

I git cloning '19/7/28. then I compiled from cloning source, FDS launch fixed.
But couldn't launch some FDS games, these games failed to  launch on 0.9.8. these games re-launched failed.

I attach ~/.config/mesen/mono_crash* log file.
[mono_crash.2d7127ec2.0.json.gz](https://github.com/SourMesen/Mesen/files/3438425/mono_crash.2d7127ec2.0.json.gz)

**Comment by SourMesen** [comment]
If you're compiling the 0.9.8 commit (f544688), this is normal.
I had to make a patch of 0.9.8 and rebuild the release to fix FDS games (279c3952711f40b10a444b74b05d04cefa7dafb5).

I would suggest you compile using the latest commit (373c489b01e6634c7c20174ee1f506e93586f2e6) since all commits since 0.9.8 are just bug fixes.

**Comment by io3432iooivzs** [comment]
I compiled today(7/28)'s git clone.
That's patch already included because of FDS games can play.
But, already launch FDS games on 0.9.8 can't launch. appeard error message and crashed.
I pointed out this error, not launed FDS games.

**Comment by SourMesen** [comment]
Sorry, I misunderstood that part. The crash log doesn't really appear to contain any information I can easily use.

If what you're saying is that games you launched before compiling the fix now keep crashing, look in the `Saves` folder and delete the `.ips` files that correspond to the games that are crashing, that should hopefully fix the problem.

**Comment by io3432iooivzs** [comment]
Thanks, some game can luanch to delete *.ips files.
But some games can't launch yet. "Baseball" and "Super Mario Bros".
I guess, games has both casette and fds format, these can't launch?
I attach command line error message as log file.
[fds-boot-error.log](https://github.com/SourMesen/Mesen/files/3438472/fds-boot-error.log)

**Comment by SourMesen** [comment]
I can't reproduce this unfortunately.  Tried loading various FDS games, and all of them loaded properly without crashing on my end as of the latest commit.
