### ISSUE TITLE
Automatically load patches in Mednafen format (filename.zip.ips)

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#651]
When you load a ROM, Mednafen looks for `<FullFileName>.ips`. [Examples](https://mednafen.github.io/documentation/#Section_ips_patching):      

```
Boat.nes - Boat.nes.ips
Boat.zip - Boat.zip.ips
Boat.nes.gz - Boat.nes.gz.ips
Boat     - Boat.ips
```
       
Can you make Mesen also look for patches in that format if there's none corresponding to the filename of the extracted ROM file?

**Comment by SourMesen** [comment]
Thanks for the request!
Mesen will now try to load patches named either "RomName.ips" or "RomName.nes.ips" (assuming the original rom was a .nes file)
