### ISSUE TITLE
Check compressed files for FDS BIOS

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#654]
Mesen 0.9.8 accepts 7z-compressed ROMs, but you need to extract an FDS BIOS file before choosing it.

**Comment by SourMesen** [comment]
Thanks for the request!  I think this is minor enough that it's not a huge deal to the end user.

Currently this is handled by a simple function that takes a few line in the C# UI.  If I wanted to add 7z support, it would need a fair bit of extra code (and would have to be done in the C++ core, etc.) I don't think the additional code complexity that would be involved is really worth the tiny amount of effort it saves.
