### ISSUE TITLE
[Feature Request] Custom integer scales

### ISSUE THREAD

**Issue by MrMinderbinder** [SourMesen/Mesen#656]
When using the integer scales option in fullscreen Mesen scales both the horizontal and vertical by the same integer. There doesn't seem to be a way to scale by different integers, 4x vertical and 5x horizontal for instance, I've tried fiddling with the aspect ratio options but to no avail. It would be nice to be able to simply dial in whatever integers you wanted.

**Comment by SourMesen** [comment]
Hey, sorry for the long delay.

You should already be able to able to achieve any aspect ratio you want by using the "Custom" aspect ratio option, which lets you enter any number between 0.01 and 10.00 (if I recall correctly).

Hope that helps!
