### ISSUE TITLE
Mesen 0.9.8 hangs and crashes when launched through Steam

### ISSUE THREAD

**Issue by Pastell** [SourMesen/Mesen#657]
I added Mesen to my Steam library by using the "Add non-Steam game" feature. I did this so I could use my Nintendo Switch Pro Controller in Mesen, because if you don't launch an application through Steam, the controller is read as sending random inputs at a ridiculous rate.
![mesenhangs](https://user-images.githubusercontent.com/6536055/63462713-883e5380-c429-11e9-86e4-5e0fe3ea75ab.gif)

**Comment by SourMesen** [comment]
Sorry for the long delay.  I unfortunately can't reproduce this on my end - setting up Mesen as a non-steam game does not cause it to freeze (even with the Steam overlay enabled)

**Comment by peaceshi** [comment]
> Sorry for the long delay. I unfortunately can't reproduce this on my end - setting up Mesen as a non-steam game does not cause it to freeze (even with the Steam overlay enabled)

use steam start mesen , and start a game , then click Help->About. window freeze but game seems like OK. maybe this is helpful.

**Comment by SourMesen** [comment]
I still can't reproduce this, unfortunately.  Opening the about window does not cause a freeze, either.
