### ISSUE TITLE
Graphic bug in Toxic Crusaders (?)

### ISSUE THREAD

**Issue by Arcus87** [SourMesen/Mesen#66]
Toxic Crusaders / Ninja Turtles 5 (Unl) [!] - from the GoodNES

both have a graphic bug in **Level 2**
![ninja turtles 5 unl _000](https://cloud.githubusercontent.com/assets/21690438/20695419/7b539432-b5f4-11e6-9436-f85973c30775.png)

**Comment by SourMesen** [comment]
Thanks for the report!  I'll take a look when I have the time

**Comment by dragon2snow** [comment]
I think not bug! is game NT5 game bug

**Comment by Cibomatto2002** [comment]
game works fine. Looks like you have a bad rom.
![capture12-4-2016-12 46 04 am](https://cloud.githubusercontent.com/assets/21169038/20864543/5cbee826-b9bb-11e6-926c-666186b75bc8.jpg)

**Comment by dragon2snow** [comment]
Ninja Turtles 5 (Unl) [!]  is pirate version hack. have bug!

**Comment by SourMesen** [comment]
Thanks a lot for the help, saved me a lot of time!
Marking this as not being a bug since it looks like an issue with the game hack's code
