### ISSUE TITLE
"About" tab window going behind the emulator window when opened.

### ISSUE THREAD

**Issue by AlanRibas** [SourMesen/Mesen#665]
When I open the mesen emulator (0.9.8) by clicking on the "Help" option, and then on the "About" option the window of that option opens. However at the same time this window goes behind the emulator window itself. So I can't click on the emulator window anymore. In this case I need to press the "ESC" or CONTROL + ALT + DEL key. to make everything work again.

**Comment by SourMesen** [comment]
Thanks for the report.  I haven't been able to reproduce the issue, but it should hopefully be fixed by c5418331ed2dc97133530853d0b1c8df00601530.  Let me know if you still have the same issue in the dev builds (or the next official release)
