### ISSUE TITLE
Feature request Simulate NTSC TV gamma ramp.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#67]
Could you add this sometime Simulate NTSC TV gamma ramp?

**Comment by SourMesen** [comment]
Not quite sure what "NTSC gamma ramp" is - a Google search for that exact term doesn't find much aside from a few references to higan/bsnes (less than 2 pages of results).
Either way, the NTSC filter's code not being my own (blarrg's library), it is unlikely I try to add anything to it, especially considering my extremely limited knowledge of NTSC signals.

**Comment by Cibomatto2002** [comment]
All it does is is make the colors look better. Maybe you can make something close to it.

![1](https://cloud.githubusercontent.com/assets/21169038/20739856/08067432-b684-11e6-8fcf-7c7e310306e2.jpg)

**Comment by Nicholas-Steel** [comment]
The NES uses a pelleted display unlike the SNES. You can simulate it yourself by creating a new colour pallet.I personally use FirebrandX's colour palette as it is the most accurate to my memories of the actual console on a CRT display.

Website: http://www.firebrandx.com/nespalette.html
Palette: http://www.firebrandx.com/downloads/Nostalgia-(FBX)..zip

**Comment by Cibomatto2002** [comment]
I like the Nostalgia (FBX) Palette. I use bsnes-plus v073+3 and don't see a way to use Unsaturated-V6. Not to worried about it tho. Thanks for telling me about Unsaturated-V6. and about Nostalgia (FBX).


https://github.com/devinacker/bsnes-plus/releases
