### ISSUE TITLE
(libretro) Shift Button Clockwise (like nestopia)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#671]
Nestopia have "Shift Button Clockwise" core option.

When DISABLED (default) it works like all standart nes cores:
z - B
x - A
a - turbo B
s - turbo A

When ENABLED it works like current MESEN:
z - A
x - turbo A
a - B
s - turbo B

Will be nice to see this implemented in Mesen!

**Comment by SourMesen** [comment]
Hey, sorry for the delay, been taking a break from Mesen(-S) for the past couple of months.

Is this a new option in the Nestopia core? I don't recall seeing it before. Changing the default layout is something that's been requested a number of times now, so this would probably be a perfect solution.

**Comment by eugene-s-nesdev** [comment]
> Is this a new option in the Nestopia core? I don't recall seeing it before
Yes, current nestopia core have this option.

**Comment by SourMesen** [comment]
Just added this in df6b003a36a6d0e43656f70954b55cfd670f6938 - should be behaving the same as the Nestopia core now.  Let me know if you find any issues with it!

**Comment by tryal-star** [comment]
Thank you *a lot* for adding this in! ❤️

**Comment by SourMesen** [comment]
No problem!
