### ISSUE TITLE
Event Viewer: add colour legend

### ISSUE THREAD

**Issue by koitsu** [SourMesen/Mesen#672]
Currently in the Event Viewer, there's no legend/key depicting what coloured dots associate with what feature.  Mouse-over tooltips are sometimes finicky, so having a legend on the right hand side next to each Event Viewer event depicting its associated colour would be super helpful.

Footnote: I took a stab at this myself in VS2019, and got quite literally lost trying to figure out how to do it.  The colours for the events are hard-coded into DebugInfo.cs using `ColorTranslator.FromHtml()` values (and I don't understand why that vs. `Color.FromArgb()` used later in the same file), but even so, I wasn't able to figure out how to add a square coloured box on the right side of each entry in tableLayoutPanel2.

**Comment by SourMesen** [comment]
Super late, but finally got around to this.  The UI is more like Mesen-S now, so you can see and change the colors from the main window.

Also made it so you can show/hide each individual PPU register for more flexibility:
![image](https://user-images.githubusercontent.com/21093973/68825865-b8cd0c80-0669-11ea-8508-cb8da9950fad.png)
