### ISSUE TITLE
Kid Icarus (USA, Europe) (Rev 1)

### ISSUE THREAD

**Issue by anewuser** [SourMesen/Mesen#674]
Mesen 0.9.8 automatically sets the region to PAL instead of NTSC for [Kid Icarus (USA, Europe) (Rev 1)](https://datomatic.no-intro.org/?page=show_record&s=45&n=1176).

**Comment by RokkumanX** [comment]
@anewuser 

According to the MesenDB everything is 100% correct and as it should be, look really close on the entry below:

`D67FD6A6,NesPal,NES-SNROM,NES-SNROM-05,MMC1B2,1,128,,8,8,0,0,,,,,,`

And if you look closer on the page you linked to it says Europe on the Region section and even have comments of being a SCN Swedish cartridge dump, Spain cartridge dump etc.

Being from Sweden I know this, SCN stands for Scandinavia and here in Sweden SCN Bergsala were the distributors of NES games.

Seeing that this specifically is [Europe release only](https://nesdir.github.io/D67FD6A6_Spain.html) everything is in order and Mesen should treat it like PAL.
