### ISSUE TITLE
2000-in-1 Unchained Melody: Invalid OP Code - CPU crashed

### ISSUE THREAD

**Issue by vrubleg** [SourMesen/Mesen#676]
ROM: [edit: removed rom link]
Mesen 0.9.8 shows this error: Invalid OP Code - CPU crashed. It works properly in FCEUX.

**Comment by SourMesen** [comment]
Thanks, I've added it to the game database, which solves the problem.
FYI, there's an issue for people to report unlicensed games that do not work: #128

**Comment by vrubleg** [comment]
@SourMesen, what the database does? Does the rom file has wrong headers? It works in FCEUX. This emulator also uses some DB to solve this issue?

**Comment by SourMesen** [comment]
FCEUX's definition for that particular mapper is different from Mesen/Nestopia's.  There are other games using the same mapper number that work in Mesen/Nestopia but not FCEUX.
