### ISSUE TITLE
0.5s delay after pressing Rewind and before it starts rewinding

### ISSUE THREAD

**Issue by vrubleg** [SourMesen/Mesen#677]
Just in case, I wanted to report that Rewind works not immediately for some reason. A game pauses for 0.5 seconds, and only then starts rewinding. Was it done intentionally for some reason?

**Comment by SourMesen** [comment]
This is normal. For the rewind feature, Mesen only keeps a snapshot of the emulation every half second, so when you start rewinding, it first has to replay the last 0.5 seconds worth of gameplay before it can start displaying the output.  This is done as fast as possible, so on a fast PC that can run the game 4-5x faster than regular speed, this only takes ~0.1 seconds, but if the PC is relatively slow, it could potentially take up to half a second.
