### ISSUE TITLE
12-in-1 (Hwang Shinwei) [p1][!] chess not working?

### ISSUE THREAD

**Issue by dragon2snow** [SourMesen/Mesen#68]
12-in-1 (Hwang Shinwei) [p1][!] chess not working?

**Comment by SourMesen** [comment]
Thanks for the report.
It looks like all emulators have the same problem with this rom.
Do you know of an emulator that can play this rom correctly?
Otherwise, it's possible that it might be a bug with the dump, or the original cartridge.

**Comment by dragon2snow** [comment]
fceux 2.2.3 working.

**Comment by SourMesen** [comment]
Fceux 2.2.3 only works when in PAL/Dendy mode, otherwise it freezes on my end.
Mesen also works when set to PAL/Dendy, though..

**Comment by dragon2snow** [comment]
I have this cart, real platform ntsc working fine.

**Comment by dragon2snow** [comment]
I Redump this cart! this dump is good dump!

**Comment by Arcus87** [comment]
DL Link for redump rom?

**Comment by dragon2snow** [comment]
redump rom,same goodnes rom.

**Comment by SourMesen** [comment]
I've created #128 to keep track of all problems related to unlicensed games and multicarts in the same GitHub issue, so I'm closing this one.
If you have find any other unlicensed cart that doesn't work properly, please post a comment in #128, thanks!
