### ISSUE TITLE
Feature Request: run-ahead

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#682]
Run-ahead is a technique to remove internal processing delay frames from games, resulting in reduced input latency.

With run-ahead, it is possible with an optimized setup for software emulation to have *less* latency than the original hardware!

First conceived by hunterk and implemented by dwedit into RetroArch, it has now been successfully implemented in bsnes standalone as well.

Video from byuu.

https://www.youtube.com/watch?v=1AvOa8yt6Vc

**Comment by SourMesen** [comment]
Thanks for the request!
This is available as of the latest build (it's in Options -> Emulation)
I'll be adding this to Mesen-S soon, too. (e.g within the next few days)

**Comment by Cibomatto2002** [comment]
Thank you Sir. I will enjoy it.
