### ISSUE TITLE
Feature Request: DMC loads in Event Viewer

### ISSUE THREAD

**Issue by domgetter** [SourMesen/Mesen#683]
Would it be possible to add DMC events to the Event Viewer for when the CPU is interrupted/suspended for 4 cycles?

It could be another checkbox on the right side labelled "DMC Reads" or something like that.

**Comment by SourMesen** [comment]
Thanks for the request!
This is available as of ea9e31f44e1b3ea2e673e45b910113954957cd6f. A dot for the last "real" DMC read is shown (but the dummy/alignment reads that precede it aren't shown)
