### ISSUE TITLE
Mindkids 143-in-1 mapper

### ISSUE THREAD

**Issue by litaniast** [SourMesen/Mesen#689]
Chinese multicart called The Best Games of Nes 143-in-1.

It's dumped under the name "Super Game 143-in-1 (The Best Games Of NES)(Mindkids)(Unl).unif" file but it's not playable in current Mesen because of unknown mapper.

The only emulator that playable it is Nintendulator now.

**Comment by litaniast** [comment]
And, another custom mapper from Caltron 9-in-1 http://masterdisk.byethost15.com/blog/libg/index.php?entry=Caltron-9-in-1&i=1

**Comment by SourMesen** [comment]
Thanks for the info - I've added them to the list of unsupported mappers for unlicensed games in #136
