### ISSUE TITLE
Fast forward doesn't start immediately when emulation speed is 1%

### ISSUE THREAD

**Issue by vrubleg** [SourMesen/Mesen#690]
I use slowing emulator down for debugging purposes. To reproduce the issue, just slow down it to 1%, and then try to press "Fast Forward" button in random moments. You will see, that it switches to fast forward mode only when it is going to switch to the next frame (and it takes time when emulation speed is 1%). It would be nice if fast forwarding would cancel current delay between frames.

**Comment by vrubleg** [comment]
Actually, it happens also when you just jump from 1% emulation speed to 100%. As another suggestion, I would suggest to use Ctrl+0 to set emulation speed to 100%.

**Comment by SourMesen** [comment]
Thanks for the report.  I've been aware of this for a long time but never bothered fixing it :p
As of e95bdf420314918eb7294fbd213697cbb4cfa3f5, the emulator should respond quickly to speed changes, pausing or saving a state while running the emulation at a very low speed.
