### ISSUE TITLE
Mesen and FDS games

### ISSUE THREAD

**Issue by jaw9170** [SourMesen/Mesen#691]
Hello-

When I start an FDS game, I get to the "please set disk card" screen.  How do I get passed this screen?  I have the disksys.rom file in the correct location (I think).  DO I have to change disks somehow?  I do have the setting set to automatically change disk sides and auto load the bios.

Thank you,
Jason

**Comment by SourMesen** [comment]
If I recall correctly, there was an issue in the first "release" of 0.9.8 with FDS games.  If you happened to update/download Mesen then (last July-ish?) you might have the bugged version on your PC.  If that's the case, try redownloading it again and see if it that helps.

As far as I can tell, FDS games appear to be working properly here.

Also, the UI would normally prompt you for the bios file if it can't find it (assuming you are using the standalone version)

**Comment by jaw9170** [comment]
Yes sir, that did the trick, thank you very much!  I downloaded the latest version manually and now FDS games work fine.

**Comment by SourMesen** [comment]
No problem - thanks for confirming it fixed the problem!
