### ISSUE TITLE
Castlevania III - Dracula's Curse Graphics Glitch

### ISSUE THREAD

**Issue by mibro0224** [SourMesen/Mesen#693]
When the title screen is left to begin the opening story (scrolling text), the graphics begin to glitch at the top and bottom of the screen. 

See attached image, which shows the glitched graphics at the top of the screen. 

![Castlevania III - Dracula's Curse (USA)-191109-172919](https://user-images.githubusercontent.com/40230382/68531855-277f3280-0317-11ea-90f3-8e70b0e202bb.png)

Using Mesen v0.9.8 Retroarch core with verified no-intro.

**Comment by SourMesen** [comment]
This is normal - the top row in CV3's intro displays garbage (this is common in NES games.)
To hide it, you can use the core's "overscan" settings to hide a portion of the edges of the screen.
