### ISSUE TITLE
"Power Cycle" reloads ROM file instead of just powercycling

### ISSUE THREAD

**Issue by ansstuff** [SourMesen/Mesen#696]
This just cost me 2 hours of romhacking work.
I modified several subroutines and checked the modified behavior from power on (not just reset, because I needed clear RAM). Suddenly I've lost everything except labels and breakpoints, because the Powercycle reloads ROM instead of doing what's implied by its name! guess I should have saved more often. But I'm used to FCEUX, it has one hotkey for powercycling and another one for reloading ROM.

I suggest renaming the command to "Reload ROM" and moving it from "Game" to "File" menu.

**Comment by SourMesen** [comment]
Sorry you lost some work!  But in general, even without power cycling, I wouldn't suggest using it for 2 hours without ever saving - crashes while using the debugger tools do happen from time to time (I try to fix all of the ones I can, but realistically, they involve a *lot* of code, and bugs will definitely exist somewhere in there).

I've added a "Reload ROM" option to the file menu, and kept the power cycle option in the game menu, too.  Reload ROM is identical to reopening the rom manually. Power cycle behaves like it did before, but it will preserve PRG/CHR ROM changes across power cycles.

**Comment by ansstuff** [comment]
Thank you.
I've let my guard down, because Mesen feels so slick and thorough, basically a FCEUX 3.0.0 (except for TAS Editor and a few minor quirks).
Never thought I'd say that, but yeah, you've not only improved over FCEUX (many emus do) but also managed to keep every important feature without workflow regressions. This is impressive.

**Comment by SourMesen** [comment]
Thanks!  A lot of people that used FCEUX did give a ton of feedback over the years, so that's definitely helped take care of the majority of use cases.

A TAS editor is still something I would like to get done someday, though between Mesen and Mesen-S, I'm not sure I will have the time to tackle a feature that big anytime soon unfortunately.
