### ISSUE TITLE
Invalid input (up+down & L+R) filtering is inconsistent

### ISSUE THREAD

**Issue by outoflock377** [SourMesen/Mesen#697]
If you press Left while holding Right, the emulator treats it as a Left input.
But if you press Left while holding Right, the emulator ignores Right press completely.

Same thing with Up + Down, if you are holding Down and press Up, input switches to Up and nothing happens with inputs the other way around.

I have a few suggestions on how to fix it:
1. If both directions are pressed at the same time, they "cancel" each other out and no button press is registered (That's how it works on Nestopia)
2. If the opposite direction is pressed while holding the current one, switch to the opposite direction immediately.
3. If the opposite direction is pressed while holding the current one, ignore the opposite direction. (I wouldn't recommend this)

However methods 2 and 3 might not work if both directions are engaged at the same time. So method 1 is probably the most viable.

**Comment by SourMesen** [comment]
Thanks - only keeping up/left active when both directions were pressed was on purpose, but blocking both directions makes more sense - changed to match Nestopia's behavior (48db2619427355ee141584af0267406106b5713d)
