### ISSUE TITLE
Debugger - no label reference for scoped labels

### ISSUE THREAD

**Issue by andre-paris** [SourMesen/Mesen#699]
In the debugger screen with Source Code View enabled, there's no reference to labels defined inside a scope (ca65 source code):

![mesen-bug2](https://user-images.githubusercontent.com/4292242/68946305-6c7cec00-0791-11ea-90ee-006fa9f24d7c.png)

In the above example, mon_place_adjacent is a scope and crt_id is the label.

**Comment by SourMesen** [comment]
I tried this on my end and it seems to be working properly.  This is almost most likely due to your font not being monospaced - try a monospace font and it should hopefully fix the issue.
