### ISSUE TITLE
emphasis too bright?

### ISSUE THREAD

**Issue by tryal-star** [SourMesen/Mesen#703]
After running the palette.nes rom, was wondering about the emphasis generation.
https://github.com/SourMesen/Mesen/blob/26773a1ecc6c4993aaf26c10b3581b0ecba338de/Core/EmulationSettings.h#L846

Currently it doesn't seem to have much change in color brightness. Compared to others like Nestopia.

Real hardware captures are on last post.
http://forums.nesdev.com/viewtopic.php?p=233739#p233739

A small comparison shows
```
famicom + vcs500
237 237 237 - 000  [1.000]
234 201 198 - 001  [~ 0.841]
191 223 180 - 010
193 194 163 - 011  [~ 0.814]

204 200 247 - 100
199 175 205 - 101  [~ 0.852]
177 196 200 - 110  [~ 0.835]
173 173 173 - 111  [0.729]
```
When 2 or 3 bits are set, the lowest stable value is ~173 = 0.729 with some variations.
When 1 bit is set, it hovers a lot too. A wide average of ~201 = 0.848 from max.

```
mesen
255 255 255 - 000  [1.000]
255 229 229 - 001  [0.898]
229 255 229 - 010  [0.898]
252 252 206 - 011  [0.807]

229 229 255 - 100
252 206 252 - 101
206 252 252 - 110
227 227 227 - 111  [0.890]
```
When 1 bits are set, it has a low value of 0.898.
When 2 bits are set, it has a low value of 0.807 and rest are nearly max (252).
When 3 bits are set, it has a low value of 0.890. Almost same as 1 bit.

Maybe an 8-entry table would help rebalance the tints to something more acceptable?

**Comment by SourMesen** [comment]
The current emphasis logic is rather simple, for each active bit it multiplies that channel by 1.1, and multiplies the other 2 channels by 0.9, which dims them.

Some people have said that Mesen's implementation looks rather close to what they see on their CRT, so like palettes, it's the kind of thing where getting a perfect representation that matches what everybody expects is probably half-impossible.

FYI, Mesen supports 512-color palette files (like FCEUX does, I believe) that allow you to manually set the color for all combinations of emphasis bits, so there is no need to rely on Mesen's default implementation if you feel like it doesn't match what you expect.

**Comment by tryal-star** [comment]
Ah, okay. Thanks for clearly explaining!
