### ISSUE TITLE
Crashes with Mesen .98 Super Chinese 3 (Japan) on Retro Arch

### ISSUE THREAD

**Issue by mcabel** [SourMesen/Mesen#705]
The game [Super Chinese 3 (Japan) ] crashes after pressing Start on the first screen. In the EXE, windows version .98 It works perfectly, as well as in other emulators.

Using windows 8.1 and retroarch 1.81

**Comment by SourMesen** [comment]
Thanks for the report! This was actually unrelated to RetroArch - the game crashed in the same way in recent dev builds for the standalone version, too.

The issue is fixed as of f7ff089689dbdf3fcde8a4b703a0282e77b98885.

**Comment by mcabel** [comment]
Thanks for replying! I was able to confirm this was fixed and was able to go in game properly.
