### ISSUE TITLE
Game crashes when text hook has auto refresh enabled with Translator Aggregator

### ISSUE THREAD

**Issue by mcabel** [SourMesen/Mesen#706]
This happens with AutoRefresh Enabled and Autocopy to clipboard enabled. The game throws an exception which eventually ends up in a crash. The game tested was Super Chines 3 (japan).
[Translator aggregator is a free app that monitors clipboard for text and auto translates it... so Ideally an user can auto capture foreign text with the text hook, and it should be translated on Translator Aggregator, which it does, until Mesen shortly crashes].

Windows 8.1
Emulator version .98

PD.
Also, for some reason, 
the capture window is mirrored and has garbled text below, which sadly interrupts capturing text a bit.(shown on the second image)

![image](https://user-images.githubusercontent.com/10392829/69298145-0225da80-0bdb-11ea-95cc-6e46454923f8.png)
![image](https://user-images.githubusercontent.com/10392829/69298496-0dc5d100-0bdc-11ea-9f0c-8ac150092e5c.png)

**Comment by SourMesen** [comment]
Thanks for the report!
The crash should hopefully be fixed - let me know if you still have issues with it.

RE: Text outside the visible screen being captured, it's still not possible to specify which parts of the screen should be captured, at the moment, but it's something I do want to add eventually.  See #534

**Comment by mcabel** [comment]
Thanks for your reply. Since the view port enhancement lies in the future, I did a small workaround using an autohotkey script. I'll attach it in case you or any of your users/game translators want to use it. Feel free to publish it, share it or delete it. 
 
[nes joy to f5.log](https://github.com/SourMesen/Mesen/files/3880525/nes.joy.to.f5.log)
