### ISSUE TITLE
Pause and advance emulation via Lua API

### ISSUE THREAD

**Issue by shichongrui** [SourMesen/Mesen#707]
Perhaps this is possible and I just don't know how but it would be great to have a lua api to be able to pause execution of the emulator, as well as the ability to execute one frame. My use case is to be able to run a separate script over certain game state that has been read from memory on each frame but may not complete before moving on to the next frame. Thus having tight control of the emulation by having the ability to pause emulation, and advance one frame at a time would be great.

Thanks for the emulator and the lua scripting, It's great!

**Comment by SourMesen** [comment]
If your goal is just to run code at the end of a frame, you can simply run it inside an event callback (e.g using the "endframe" or "startframe" events.  You can technically just loop/wait until the results are ready to return from that callback and the emulation will be stopped until you return from the endframe event.

You can pause/resume the emulation in a number of ways, see: https://www.mesen.ca/docs/apireference/emulation.html#breakexecution
But keep in mind that the entire Lua API is based on a system of callbacks - upon a pause/break, the "codeBreak" event will be triggered, but if you don't resume the emulation from within that event's callback, the emulation will be effectively permanently paused until you manually resume it by hitting resume in the emulator.

**Comment by shichongrui** [comment]
Ah ok that all makes sense. It was just a misunderstanding on my part. I didn't realize that the event callbacks blocked execution until they had returned. I actually think that alone solves my use case. Thanks for the info.
