### ISSUE TITLE
Shooting Zapper away from the screen

### ISSUE THREAD

**Issue by karmic64** [SourMesen/Mesen#708]
Requesting a feature to shoot the Zapper, but not have it detect any light from the screen, possibly using the right mouse button.

Official Nintendo Zapper games use shooting away from the screen in their menus to change options, and pointing at the screen to select them, and while these games support the controller so this can be avoided, it would still be nice to have regardless.

**Comment by SourMesen** [comment]
This is already supported (though I think it may not be documented anywhere) - hold down the right mouse button and click with the left mouse to shoot away from the screen (e.g where the zapper will never detect any light)

**Comment by SourMesen** [comment]
I added a note about this in the input configuration documentation (won't be up on the website until the next version is released, though)
