### ISSUE TITLE
Adjusting audio sample rate mutes right channel (stereo mode)

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#71]
If I adjust the Audio Sample Rate while listening to a NSF audio file the right audio channel will be silenced until I close the emulator completely and re-open it.

Windows 10 Pro AU x64
Realtek ALC1200 Integrated Audio Chip (latest drivers)

**Comment by SourMesen** [comment]
Thanks for the bug report!
This was a bug in the stereo code for "delay" mode.
Fixed by a37992e2996832bdbe3c8662f150501dc1d62301
