### ISSUE TITLE
Arcana screen tearing.

### ISSUE THREAD

**Issue by Apocalypse612** [SourMesen/Mesen#712]
Getting some screen tearing at the ending of Arcana. I'm not sure of the cause. I think you mentioned that Mesen-S runs off of direct-x only, but that's just off the top of my head. I haven't experienced this issue anywhere else, in any other ROM that I've tested so far, which I admit is only a handful. Here's a video sample that I recorded. This is on Mesen 0.3.0.

https://www.youtube.com/watch?v=byi3n7blBmo

Here's another video I found on the net, showing the same cutscene. 

https://youtu.be/VpaVgBgiQm4?t=147

**Comment by SourMesen** [comment]
I'm assuming you meant to open this in the Mesen-S repo :p   No big deal, though.
Do you have a save state I could use to quickly get to that point of the game?

I'm not quite sure what the cause might be here - it looks more like the scroll offsets for each line are slightly off, so it's more likely to be an emulation issue more than anything, I think.

**Comment by ghost** [comment]
Crap! Sorry about that. Yes, I do. Just a moment.

**Comment by ghost** [comment]
Mesen-S V0.3.0
https://gofile.io/?c=9khUwX

If you prefer I move this to the appropriate GitHub repository, I can do that quickly and delete this one. My mistake.

**Comment by SourMesen** [comment]
No worries - I did take a look at the Arcana display issue before my trip, but couldn't find the problem (and do kind of want to compare with bsnes before trying anything else to ensure the actual pixels on the screen are wrong vs it being a graphical display issue.)

I'm not sure how easily the ending is reached from a save file, though (e.g not a save state), so it might take a bit more time until I can verify this.

**Comment by ghost** [comment]
I can verify this for you on Bsnes for you, if you prefer, and post some video footage back here. I can easily get back to the ending with a chapter 5 save file, and fast forward.

**Comment by SourMesen** [comment]
That'd be really helpful, but if you're actually willing to do this, could I ask you to do it on bsnes-plus?  If you did, I could take a save state from bsnes-plus and then use its debug tools to hopefully help me figure out if there's anything wrong, and it should be close enough in accuracy to bsnes to trust on this (make sure to use the bsnes-plus accuracy build)

**Comment by ghost** [comment]
Sure thing. I'll hit this after work ends in a few hours, then I'll get back to you probably tonight with the results.

**Comment by ghost** [comment]
Emu: bsnes-plus-05-x64 (Accuracy Build)

Save state 1 has the ending, as requested. Attached below. Same issue present, with Open GL enabled in settings.

Rom: Arcana (USA).sfc [No-Intro Pack] - MD5: cefe028852135a1695ed9f6e692bc0ca

https://gofile.io/?c=ckDBQk

**Comment by SourMesen** [comment]
If bsnes-plus has the same issue, I'm starting to think this might just be normal then.
I've hunted down some other youtube videos to compare, and as far as I can tell, the only one that doesn't seem to have this display artifact is the first one you posted.

This particular scene uses mode 7, and I know zsnes has had some sort of high resolution mode 7 for a very long time - maybe this is just a recording from an emulator that used some sort of higher resolution mode for mode 7 transformations?

**Comment by ghost** [comment]
I assumed it was the original hardware that was posted in the first video. I no longer have an original console to test this on, but I'm curious to know how it displays on real hardware.

**Comment by SourMesen** [comment]
I'll close this for now, since it seems likely that this is normal (seems unlikely that bsnes-plus would have the exact same issue otherwise.)  If you're curious and want to tinker some more with this, you might be able to use bsnes' recently added HD Mode 7 feature to make the "tearing" appear/disappear (by toggling HD mode on and off), which would imply that the behavior is probably normal and just a result of mode 7's normal resolution.

**Comment by ghost** [comment]
I'll give that a try, I think, in the next few days. Thanks SourMesen.
