### ISSUE TITLE
No video in the emulator on Linux

### ISSUE THREAD

**Issue by pasquinelli** [SourMesen/Mesen#716]
When I run a rom I can step through code with the debugger, view the PPU if I turn on the debug menu, and take screen shots, but the actual emulator itself displays only a black screen that is unchanged by a power cycle. I don't know if it plays audio because my speakers are broken and I don't have headphones.

I'm running:
Pop!_OS 19.10 64 bit
GNOME 3.34.1
Intel Haswell Mobile

**Comment by SourMesen** [comment]
Thanks for the report - this is a known issue, see #319

**Comment by pasquinelli** [comment]
The video is *not* fixed by a power cycle.

**Comment by SourMesen** [comment]
If you read through the comments on that issue, despite the original title, people have already reported that sometimes power cycling doesn't help.  Sometimes several steps is required to get it to show video at all (and it looks like sometimes nothing helps).

If you are using an nvidia card with the nvidia drivers, it's very likely to be the same problem.

**Comment by pasquinelli** [comment]
Ah, i see it now. For whatever help it might be, i'm using an intel open source driver.
