### ISSUE TITLE
Not everything is translated to Russian on toolbar

### ISSUE THREAD

**Issue by ReverseDmitry** [SourMesen/Mesen#720]
Not everything is translated to Russian on toolbar of Mesen
=================
Line 1) Button Name in English
Line 2) How it should be translated to Russian
=================
Load Last Session **(NOT TRANSLATED)**  
Загрузить последнюю сессию
Power Cycle **(NOT TRANSLATED)**
Цикл питания
Power Off **(NOT TRANSLATED)**
Отключить or Выключить or Отключить от питания
History Viewer **(NOT TRANSLATED)**
Просмотр истории or Смотреть историю or История
Video Recorder **(NOT TRANSLATED)**
Запись видео
Load Random Game **(NOT TRANSLATED)**
Загрузить случайную игру
Online Help **(NOT TRANSLATED)**
Онлайн-помощь or Помощь онлайн
Command-line options **(NOT TRANSLATED)**
Параметры командной строки

**Comment by SourMesen** [comment]
Unfortunately, the person that initially translated the UI to Russian hasn't been around in a long time - it's very out of date (anything that I've added in the past 2+ years hasn't been translated to Russian)

I can fix the ones you've pointed out on my end (thanks for the translations), but ideally, someone would need to go through this file:
https://github.com/SourMesen/Mesen/blob/master/GUI.NET/Dependencies/resources.ru.xml
And translate everything that's in English to Russian.

**Comment by SourMesen** [comment]
Thanks for the pull request!
