### ISSUE TITLE
[Requests] Sprites and Palettes

### ISSUE THREAD

**Issue by ReverseDmitry** [SourMesen/Mesen#724]
So I had a few ideas what could be added in Mesen, I am not sure where to post requests so I'm doing it here.
1) Graphical corruptions.
Implement graphical corruptor. How it would work? What it does is corrupt game sprites by swapping sprites from memory randomly, maybe it would even be possible to use seeds for the corruptions to be able to access any corruption later, maybe it could even randomly change pallets of sprites or maybe you could toggle it, maybe also randomly rotate sprites for more variations, maybe you could choose corruption level for some intense randomness or just a little bit, just some thoughts on how it would work. (See screenshot below)
![cldspy8qivf21](https://user-images.githubusercontent.com/58607111/70539952-72d66c00-1b75-11ea-8885-2af7f7c1925d.png)
2) Being able to mirror the screen
There is no real reason to mirror the screen but still worth requesting. I got this idea when I was watching the gameplay of Super Luigi Bros. from NES Remix 2 (official Nintendo game) where you are basically Luigi but playing the SMB1 stages in reverse, text above is of course not mirrored but that's beside the point, here's some YouTube footage
https://www.youtube.com/watch?v=EJnWfQAMw_I
![Legend of Zelda, The (U) (PRG 0)_002](https://user-images.githubusercontent.com/58607111/70591014-a224c180-1be5-11ea-99c8-9bbb68c1567d.png)
3) Invert colors
This feature probably exists everywhere from your phone to Nintendo Switch. Basically inverting colors of the screen. 
![Legend of Zelda, The (U) (PRG 0)_001](https://user-images.githubusercontent.com/58607111/70591048-c41e4400-1be5-11ea-9d38-85aefc5781ae.png)

4) Apply random palette
Palette of the game you're playing would randomly change (maybe make a timer, Mesen users would choose how often they want the palette to randomly change, choose palettes they want to change, etc. Just some ideas on how it would work)

**Comment by SourMesen** [comment]
Thanks for the requests.

Technically, all of these can already be done by using the Lua scripting features in Mesen.  There is actually a script that's available from the script editor window to mirror the screen, already.  And there's also a script that simulates a gameboy's palette/etc, too.

**Comment by SourMesen** [comment]
Like I mentioned above, this is possible via Lua (though it might be rough on performance depending on your PC).  Since these aren't general-purpose features, I think implementing them in Lua is the best solution (otherwise Mesen's regular UI will end up filled with a ton of various "for fun" options.)

If you (or anybody else) implements these features as Lua scripts, I can include them in the "Built-in scripts" dropdown so that everybody has access to them.
