### ISSUE TITLE
Mendel Palace doesn't display properly

### ISSUE THREAD

**Issue by weirdingmyself** [SourMesen/Mesen#725]
The title screen is all messy.

CRC12078AFD

**Comment by SourMesen** [comment]
Thanks for the report.

I can't reproduce this, though - the title screen seems to display properly in 0.9.8 and the latest dev builds.  I compared to FCEUX and the result is identical, as far as I can tell. Can you post a screenshot of what it looks like on your end?

**Comment by weirdingmyself** [comment]
Never mind. It fixed itself.
