### ISSUE TITLE
Feature Request: Fullscreen Exclusive Display Mode (with vsync)

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#73]
This would enable the ability to avoid the DWM in Windows Vista and newer from handling Vsync for the Emulator (or interfering with the emulators vsync/"present" implementation). The DWM is, at least on my hardware, quite terrible at its job and introduces frame duplication/dropping which results in frequent visual stutter/skipping (unrelated to performance).

ie: This display mode would allow for perfectly smooth frame pacing with no perceptible frame dropping or duplication occurring.

I am aware that such a display mode will likely result in an inability to access the emulator UI, "I" am okay with having to leave Fullscreen to access this stuff if it means smooth reliable frame pacing is possible.

**Comment by SourMesen** [comment]
Thanks for the suggestion - I'll see how feasible it would be to add an option for exclusive mode.
Like you said, most of the UI probably wouldn't be accessible from exclusive fullscreen mode, though.

**Comment by SourMesen** [comment]
It's been ages, but I finally got around to this, and I think I have something that works (on Windows anyway, still needs some tinkering on Linux).

If you care to give it a try, feedback (or any crash reports) would be appreciated:
https://www.mesen.ca/MesenExclusiveFullscreen.zip

There's an option in the video options to turn on exclusive fullscreen mode.

**Comment by Nicholas-Steel** [comment]
Only 1 issue with it that I've noticed in my brief time with it.

1) While Fullscreen Exclusive mode is disabled, enter Fullscreen.
2) Configure the setting to enable Fullscreen Exclusive Mode and save the change.
3) Press F11

You are now stuck switching between Borderless Fullscreen and Exclusive Fullscreen and neither mode grants access to the UI in this situation.

**Comment by SourMesen** [comment]
Did the exclusive fullscreen mode help with frame drops/duplication/tearing, by the way? 

I made another build which should fix the problem you were getting:
https://www.mesen.ca/MesenExclusiveFullscreenFixes.zip
Let me know if you find anything else.

**Comment by Nicholas-Steel** [comment]
I can confirm the issue I reported is fixed, I'll need to spend some more time with it to determine if it improves frame pacing etc.

**Comment by SourMesen** [comment]
Thanks for the update - let me know if you find anything else once you get a chance to try it out properly.

**Comment by Nicholas-Steel** [comment]
I mean, it works. I don't know what more to say. The only other thing I'd suggest is for Exclusive Mode to adjust the monitor refresh rate to suit a games region. For example it should set the monitor to 50Hz when playing PAL games in Fullscreen Exclusive mode.

**Comment by mirh** [comment]
Note that sometimes, someway, monitors may lack to advertise a 50Hz mode, and you'd need to warn users and tell them [how](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) to [add](https://forum.doom9.org/showthread.php?t=173571) one.

**Comment by SourMesen** [comment]
Thanks for the feedback. I'll see about switching to 50hz for PAL, but if it turns out to be complex to implement (I need to make this work on both DirectX & SDL, etc.), I might just release the feature as it is now and keep that as a future improvement idea.

**Comment by mirh** [comment]
The "switch" code part should be pretty easy/straightforward regardless. 
But this is the end of it, only if required resolution is among supported ones in the first place (you should check for it before attempting change, I guess?)
And for as much as I know, it's not even just about PAL, since some monitors may just have 59Hz or 60Hz mode (or even both of them, but I'm not sure how close to the precise value you'd desire to be)

The only crazy complexity would be if you wanted to use gpu vendors private tools to programmatically fix this for the user, but tbh I'd call it a day already with a note for the user to let him handle the affair himself.

**Comment by Nicholas-Steel** [comment]
Is this function not available in v0.9.3? I can't seem to find the option.

**Comment by SourMesen** [comment]
It's not - 0.9.3 is a few months old and was released a couple of weeks before I worked on this.  It should be in the next release (probably before the end of the month)

**Comment by Nicholas-Steel** [comment]
Okay, thanks.

**Comment by Nicholas-Steel** [comment]
I think there should be some kind of display mode configuration page of settings for the Fullscreen Exclusive Display Mode option which let you configure resolution and most importantly, the refresh rate.

I have an Asus PG258Q display and when I configure it to 120Hz to use ULMB display mode, Mesen will switch to 144Hz ULMB when entering exclusive fullscreen so I end up with stutter (with regular vsync).

**Comment by SourMesen** [comment]
Can you try this build?  https://www.mesen.ca/MesenExclusiveRefreshRate.zip
It adds a "requested refresh rate" dropdown, which should hopefully allow you to use 120hz mode properly.  I've been able to use these changes to force my monitor to switch between 75hz and 60hz, but unfortunately that's all my monitor supports so I can't really test properly.

This is a pretty bare bones solution, but I'm trying to get 0.9.4 finished over the next couple of days, so I want to avoid changing anything that could unexpectedly break things on some computers.

**Comment by Nicholas-Steel** [comment]
Woo, that works fine. Good job. Video card also seems to correctly switch between ULMB (Mesen) and G-Sync (desktop) modes after setting up an application specific profile for Mesen in Nvidia Control Panel.

**Comment by SourMesen** [comment]
Great, thanks for testing!
