### ISSUE TITLE
[Debugger] System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by andre-paris** [SourMesen/Mesen#735]
This popup shows when open the debug window.
I could reproduce the issue with a MMC5 ca65 configuration and declaring more than 3 CHR of 8 KiB segments (sources and binaries included).
If you comment out the last 3 lines of chr.s the error doesn't show.
![Screenshot from 2019-12-20 11-05-47](https://user-images.githubusercontent.com/4292242/71260390-8920bc80-2319-11ea-82da-5811cbc07912.png)
[mesenbug.zip](https://github.com/SourMesen/Mesen/files/3988595/mesenbug.zip)

 To compile:
```
ca65 -g main.s -o main.o
ca65 -g chr.s -o chr.o
ld65 -C exrom.cfg --dbgfile main.dbg -o main.nes main.o chr.o
```

**Comment by SourMesen** [comment]
Thanks for the report & files!
This should be fixed by 5e61901f2ea74fddfa4884d1ca71c5a6df6fd8d1, let me know if you still have issues with it.
