### ISSUE TITLE
Teenage Mutant Ninja Turtles

### ISSUE THREAD

**Issue by vicde** [SourMesen/Mesen#737]
During intro cut scene, after donatello shown his weapon skills and before his image
has appear, there is a one  garbage frame appear (in left lower part of the screen).
If continue watching intro second time,
that's garbage frame appear between presenting first two turtles.

**Comment by SourMesen** [comment]
Thanks for the report!
Someone has tested this on a real TMNT cartridge on a NES and the glitches during the intro sequence are also visible on hardware, so this isn't a bug (but it is the only licensed game I know of so far that triggers this particular PPU glitch)
