### ISSUE TITLE
Issues with $2000 scroll glitch emulation in Super Mario Bros

### ISSUE THREAD

**Issue by Dwedit** [SourMesen/Mesen#738]
I was just testing out the $2000 scroll glitch feature with Super Mario Bros, and I ran into a few issues.

While I did see the scanline glitch trigger a few times, I also saw some nametable tiles get corrupted on the screen.  One corruption happened when entering the 1-2 bonus area.  Another corruption happened in 4-1 when Firey Mario got hit, instead of writing to the palette, it wrote to some tiles in the nametable, and Mario still had firey colors.

**Comment by SourMesen** [comment]
The $2000/2005/2006 first-write glitch emulation is definitely not quite accurate at the moment. I've noticed issues with it in SMB3 and other games as well.

Currently, the bug will trigger on any write to 2000/2005/2006 done during cycle 257. In reality, this appears to depend on CPU/PPU alignment, so it shouldn't *always* happen, even on cycle 257.
It's also possible I've implemented portions of the bug's behavior incorrectly, too, but the current implementation does match the test roms that were posted on nesdev (ppu_2000_glitch, ppu_2100_glitch, ppu_2005_glitch, ppu_2406_glitch, etc.)

**Comment by Dwedit** [comment]
At the very least, it should only happen during rendering, and not during vblank or forced blanking.

**Comment by SourMesen** [comment]
Well, turns out I'm just dumb then.  I assumed the code was already only triggering during rendering, but that wasn't the case.  Changing it to trigger only while the ppu is actively rendering (e7ca41987c4df7fbcad71f14f5a809bf48f44d3e) fixes the bugs I saw earlier in SMB3, and I'd imagine it'll probably fix the ones you saw in SMB1, too.

**Comment by Dwedit** [comment]
Glad that's taken care of now, and we all make dumb mistakes.

**Comment by SourMesen** [comment]
FYI, another bug was reported related to the $2000 writes specifically: #740 
I was incorrectly corrupting both bit 10 and 11 of V for the $2000 writes, rather than just bit 10.  This is fixed, too.
