### ISSUE TITLE
"Remove sprite limit" does not work

### ISSUE THREAD

**Issue by k600c** [SourMesen/Mesen#739]
From 0.9.8.17 to 0.9.8.69, the function of "Remove sprite limit" does not work.

![111](https://user-images.githubusercontent.com/59216719/71432600-a2f54180-2715-11ea-9dfd-8f9632c20fb9.jpg)
![Gradius II (Japan)_000](https://user-images.githubusercontent.com/59216719/71432602-a5579b80-2715-11ea-9370-b2d6cf21514f.png)

**Comment by SourMesen** [comment]
Thanks for the report!
This is fixed by 33a5d3b0c9f2e6072062a36b8e5b3aae762d38dd
