### ISSUE TITLE
Wizards & Warriors III (USA): vibrating graphics in story cutscene

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#74]
During the story cutscenes (idle at the title screen to see them) there will be a scene involving a aerial view of a castle/city. The green ground is vibrating up/down a lot when it shouldn't be.,

**Comment by SourMesen** [comment]
Thanks for the report!
Looks like this is pretty similar to #64, both are related to sprite 0 hit timing - which means fixing this might be tricky.
I'll close this issue and keep #64 opened to track the problem.

**Comment by SourMesen** [comment]
This is fixed by 17d75287bd0f643d5e599b3f6dbee777e89a7653

**Comment by Nicholas-Steel** [comment]
Awesome stuff.
