### ISSUE TITLE
Super mario bros 3 

### ISSUE THREAD

**Issue by vicde** [SourMesen/Mesen#740]
When enable PPU $2000/$2005/$2006/ first-write scroll glitch in SMB3 (J)(PRG0), floor is
flickering on title screen. 
In SMB3(J)(PRG1) floor just fine, and all Usa version title screen looking normal.

**Comment by SourMesen** [comment]
Thanks for the report!
The code was slightly wrong for the $2000 writes (they ended up corrupting an extra bit which is not supposed to be affected by this glitch)
This is fixed by 984ce9bd05bbbca59ec278f59f454f6d728b581a
