### ISSUE TITLE
add option for bigger FPS OSD font when using 4k

### ISSUE THREAD

**Issue by jjfmz42015** [SourMesen/Mesen#742]
add option for bigger FPS OSD font when using 4k

right now looks tiny on my big screen in 4k

**Comment by SourMesen** [comment]
This is a pretty rare scenario - 4k resolution is not really useful in the majority of cases, and the OSD being small is not a huge problem.
For the sake of UI and code simplicity, I'd prefer to not implement this - the more options get added to the UI, the more complex it is for a user to navigate through the settings, so I'd rather stick to only adding options that are really useful for a large portion of users, as much as possible.
