### ISSUE TITLE
Mesen should prevent restoring to an invalid location

### ISSUE THREAD

**Issue by huxia1124** [SourMesen/Mesen#746]
Mesen should detect invalid window location to restore, and move to primary display if the window is outside of all displays.

This usually occurs when the location is saved at the 2nd display but that display is then removed.
The location is saved in settings.xml

  <WindowLocation>
    <X>-1000</X>
    <Y>615</Y>
  </WindowLocation>

**Comment by SourMesen** [comment]
Thanks for the report!

This is actually fixed in the latest dev builds (was fixed a couple of months ago, I think.)
You can grab the dev builds from the appveyor link in the readme if you need the fix now (or otherwise you'll have to wait until the next official release)
