### ISSUE TITLE
emu.drawLine duration = 0 not permanent?

### ISSUE THREAD

**Issue by cacciatc** [SourMesen/Mesen#748]
Reading https://www.mesen.ca/docs/apireference/drawing.html#drawing-basics I would expect the following code to maintain a red line on the screen indefinitely:

```
emu.drawLine(63+8,0, 63+8, 240, 0xFF0000, 0)
```

However, the line blinks in and out of existence. This is the only script currently running. Mesen 0.9.8

**Comment by SourMesen** [comment]
Thanks for the report!
Looks like this was broken for a couple of years - this is fixed by f1c48acdfe2b055e2fd084b9b9b66344916c85fd
