### ISSUE TITLE
Importing codes with the XML File

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#75]
When Importing codes with the XML File that Mesen makes they will not work because Compare Value is checked and puts a 0 in the box so all my codes i have made will not work I will have to go back and uncheck the Compare Value box so they can work again. 
![capture12-10-2016-11 37 24 pm](https://cloud.githubusercontent.com/assets/21169038/21078374/30302e7e-bf32-11e6-9cc4-ed850bd90ba3.jpg)

**Comment by SourMesen** [comment]
Thanks for the report, this looks like a bug.
When exporting custom codes, the compare value is automatically set to 0, which causes the "Compare value" box to be checked when importing the XML.

You should be able to fix your XML file before importing it if you open the file and remove all occurrences of "<compare>0x00</compare>" in the file.  After doing this, if you import your codes, the compare value checkbox should no longer be checked.

**Comment by SourMesen** [comment]
This should be fixed by fc24993836db85a176731f405f323a312a1635c6.
Unfortunately that doesn't fix your file - you will have to manually remove the "<compare>0x00</compare>" tags in your XML file being importing it for it to work as expected.

**Comment by Cibomatto2002** [comment]
That's OK I just wanted you to know about the bug.
