### ISSUE TITLE
linux megaman 3

### ISSUE THREAD

**Issue by kweonsunho** [SourMesen/Mesen#750]
My os name is Linux mint 19.3 and I play megaman 3.
![스크린샷, 2020-01-15 15-58-39](https://user-images.githubusercontent.com/25223189/72412650-37047700-37b1-11ea-8529-b5f2aeedabfc.png)
but it has grappic error on right bottom, on shadow man.

**Comment by SourMesen** [comment]
Thanks for the report.

This is actually a bug that exists in the game and is also visible on the NES. See: https://wiki.nesdev.com/w/index.php/Game_bugs
