### ISSUE TITLE
Cannot compile on GNU/Linux "MapperFactory.cpp:(.text._ZN4MMC514MapperReadVRAMEt19MemoryOperationType[_ZN4MMC514MapperReadVRAMEt19MemoryOperationType]+0x397): undefined reference to `BaseMapper::InternalReadVRAM(unsigned short)'

### ISSUE THREAD

**Issue by RockfordRoe** [SourMesen/Mesen#751]
Hey, I have recently locally pulled commit 6bc5b89 to my machine, after doing a `make clean` and running `make -j5`, Clang spits out an error 1 output. 

Buildlog can be found [here](https://pastebin.com/hL8H1Spn)

**Comment by RockfordRoe** [comment]
GCC spits out error 1 as well with some information:

 `../BaseMapper.h: In member function ‘virtual uint8_t MMC5::MapperReadVRAM(uint16_t, MemoryOperationType)’:
../BaseMapper.h:153:24: error: inlining failed in call to always_inline ‘uint8_t BaseMapper::InternalReadVRAM(uint16_t)’: function body not available
In file included from ../MapperFactory.cpp:196:
../MMC5.h:561:26: note: called from here
  561 |   return InternalReadVRAM(addr);
      |          ~~~~~~~~~~~~~~~~^~~~~~
make: *** [makefile:137: Core/obj.x64/MapperFactory.o] Error 1
`

**Comment by SourMesen** [comment]
Thanks - this should be fixed with as of the latest commit
