### ISSUE TITLE
FDS Save error

### ISSUE THREAD

**Issue by Batistuta00** [SourMesen/Mesen#752]
Automatically insert disk 1 side A when starting FDS games /ON

Automatically fast forward FDS games when disk or BIOS is loading /OFF

Automatically switch disks for FDS games /ON

Save error occurs in FDS when run ahead is enabled with the above settings (ERR26)

**Comment by SourMesen** [comment]
Thanks for the report!  This was caused by a fairly subtle save state bug that could occur if you took/loaded a save state in the middle of a write operation.  Should be fixed as of the latest commit.
