### ISSUE TITLE
Mapper 30 Flash Saving

### ISSUE THREAD

**Issue by TakuikaNinja** [SourMesen/Mesen#753]
Mapper 30 games such as Black Box Challenge and NESmaker games (Only [this demo](http://nesmakers.com/viewtopic.php?f=52&t=3949) currently supports this) utilize **flash saving** to save progress, which is fundamentally different from regular battery saving. From what I know, FCEUX handles this by saving the byte differences for the whole ROM like a patch file (with a 32 byte header attached). The game would then "self-flash" the necessary data from it upon a reset/power cycle.

Kasumi made a ROM to test this a while ago: [Dropbox Download](https://www.dropbox.com/s/3451vmtho4qs8ov/Mapper30%20Save.zip?dl=0)
**Correct behavior, verified on console:** the counter increments by 1 on each reset/power cycle.
**Mesen's current behavior:** the counter stays at 129 on each power cycle but stays at 001 on each reset.

With Mesen being NESmaker's recommended emulator, I feel this should be addressed before the community makes more games that support saving.

**Comment by SourMesen** [comment]
Thanks for the request!
It's been on my list of things to do for ages now (and has been requested by a number of people before, too), so today was as good as any to get it done. This is available as of b5a0f9a4f1de3b96e8b1b6462ba6402363969c52 (and bf6a8a2de29e64e99f99ce860b8a987b0f80c380 adds the same feature for GTROM boards)
