### ISSUE TITLE
Fullscreen keeps changing back

### ISSUE THREAD

**Issue by ymo1965** [SourMesen/Mesen#754]
Hi,

Love the emulator, but get increasingly annoyed with your full screen option. I am using your emulator through 'Launchbox' but every time I run the emulator again, it defaults back to windowed mode. 

Can you please fix this?

Thanks,

**Comment by SourMesen** [comment]
If you want it to start in fullscreen mode each time, please add the `/fullscreen` switch to the command line options for Mesen in Launchbox.
