### ISSUE TITLE
Hard Drivin' (USA) (Proto) (Unl) Flickering

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#759]
------------------------------------------------------
Loading rom: Hard Drivin' (USA) (Proto) (Unl).nes
File CRC32: 0x39AB0FC7
------------------------------------------------------
[DB] Initialized - 15541 games in DB
[DB] Headerless ROM file found - using game database data.
PRG CRC32: 0x2E9851F2
PRG+CHR CRC32: 0x39AB0FC7
[iNes] Mapper: 64 Sub:0
[iNes] PRG ROM: 128 KB
[iNes] CHR ROM: 256 KB
[iNes] Mirroring: Vertical
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 64  Sub: 0
[DB] System : NesNtsc
[DB] Mirroring: Vertical
[DB] PRG ROM: 128 KB
[DB] CHR ROM: 256 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[Input] 2 standard controllers connected

Windows 10

Here is a video.

https://youtu.be/VFGer5oaXbE?t=9

**Comment by SourMesen** [comment]
Thanks - I've been aware of this for a little while.  Rambo-1 IRQs aren't quite accurate at the moment.
I've added a temporary fix for this, but the game still has a number of issues left.
I'm essentially waiting for the behavior to be properly reverse engineered before fixing anything more for the rambo-1.  There's some on-going work being done here: http://forums.nesdev.com/viewtopic.php?f=9&t=19565
