### ISSUE TITLE
Switch Pro Controller Plus Butten and Home Butten don't work

### ISSUE THREAD

**Issue by FreskoYouTube** [SourMesen/Mesen#761]
I am using my Switch Pro Controller (vJoy and JoyCon Driver) for any other Emulator and the Plus Button and Home Button usualy work,but on Mesen they don't work,same Issue on Mesen-S.

**Comment by SourMesen** [comment]
Thanks for the report.
Unfortunately I don't own a Switch, so I can't test with these controllers, which might make it a bit hard for me to fix this.

Could you send me a screenshot of the mappings for the buttons that do work? e.g:
![image](https://user-images.githubusercontent.com/21093973/73610098-e60ec400-45a1-11ea-9e16-4fc13e59818d.png)

That might give me a clue as to why it doesn't work.

**Comment by FreskoYouTube** [comment]
The Plus Button is normally called "Button25" and the Home Button is normally called "Button28" in other Emulators
![Controller Plugin](https://user-images.githubusercontent.com/52607533/73613901-6b25c780-45fa-11ea-848a-0dd579004009.png)

**Comment by SourMesen** [comment]
Thanks - that was really helpful. There was a bug that meant all buttons above 25 or so were being ignored, which should hopefully fix this.

Could you try the next appveyor dev build and see if it fixes the issue? (should be available in a few minutes)
https://ci.appveyor.com/project/Sour/mesen/build/artifacts

**Comment by FreskoYouTube** [comment]
Nice,it works now,did you fix it for Mesen-S too?

**Comment by SourMesen** [comment]
I just pushed the same fix for Mesen-S, so it should be fixed in the next appveyor build.

Thanks again for the report!
