### ISSUE TITLE
[Linux] Font in debugging tools is not monospace

### ISSUE THREAD

**Issue by mchlnix** [SourMesen/Mesen#763]
I ran Mono using Wine first and figured it was just an artifact of that, but now running 0.9.9 using mono the fonts are still no aligned in any of the debugging tools (see memory tools here).

I tried searching for a way to configure Mono, as it may be a problem on my end, but I didn't find anything.

Is this a known issue?

![grafik](https://user-images.githubusercontent.com/2623773/73607101-3aba3b00-45b2-11ea-85be-2e30b1ee7407.png)

**Comment by mchlnix** [comment]
https://github.com/SourMesen/Mesen/blob/64fb78ae665018b496ac6dbee39b1d980858420e/GUI.NET/Controls/BaseControl.cs#L18

I found this line, which is probably the cause of it. I didn't have the droid line of fonts installed, but even after installing the `fonts-droid-fallback` package, it didn't load anything other than `/usr/share/fonts/truetype/droid` (I `strace`'d it).

In there is only `DroidSansFallbackFull.ttf`. I'm not sure if monospace is included in this as a style, but it definitely doesn't work. An `apt-file` search on my Ubuntu Bionic machine did not return any font packages with `DroidSansMono.ttf`, only four random packages shipping it themselves (probably because `fonts-droid` was removed).

`DejavuSansMonospace.ttf` *might* be a more sensible default. Or just `monospace`, as might use the default monospace font on the system? I have no experience with `mono` though, so I don't know if it works like that.

Here another example in the debugger. 

![grafik](https://user-images.githubusercontent.com/2623773/73608961-25044000-45c9-11ea-8001-e1cec512af7e.png)

**Comment by mchlnix** [comment]
Using `strace` more I found that, when opening the debugger it loads

```
access("/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf", O_RDONLY) = 25
```

and in the memory viewer

```
access("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", O_RDONLY) = 25
readlink("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
readlink("/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
readlink("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
readlink("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
```

But looking at the "D" in the memory viewer it's obviously not a monospace font, either.

**Comment by SourMesen** [comment]
For your info, you can manually select a font for all windows which require a monospace font (memory tools, debugger, script window).  e.g Options -> Font Options -> Select Font, or View -> Font Options -> Select Font, depending on the window.  This should allow you to fix the issue, regardless of the default font that gets used

**Comment by mchlnix** [comment]
Using `strace` more I found that, when opening the debugger it loads

```
access("/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf", O_RDONLY) = 25
```

and in the memory viewer

```
access("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", R_OK) = 0
openat(AT_FDCWD, "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", O_RDONLY) = 25
readlink("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
readlink("/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
readlink("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
readlink("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 0x7fff9cbd39a0, 4096) = -1 EINVAL (Invalid argument)
```

But looking at the "D" in the memory viewer it's obviously not a monospace font, either.

I also found using `fc-match`, that `DroidSansMono` maps to `DejaVuSans.ttf: "DejaVu Sans" "Book"
`, which is obviously not right and probably a mistake by my system.

**Comment by mchlnix** [comment]
@SourMesen How did I never see that? `DejavuSans` was actually the selected font. I guess I only looked into the options menu of the emulator window...

But I think changing `DroidSansMono` is probably not a bad idea, to have a sensible default again. Thanks for the quick response, though :)

**Comment by SourMesen** [comment]
The code is *supposed* to try to install DroidSansMono in your user profile when you first run Mesen, but that may have failed for whatever reason. (I haven't seen people complaining about this in recent memory, but it's possible most people changed the font manually without reporting it)

The main problem with Linux is that from one distribution to another it's pretty hard to know which monospaced fonts might be available, which is why I've been doing this up to now. Is there a monospaced font that is fairly likely to be installed on all systems?

**Comment by mchlnix** [comment]
In the *Ubuntu world probably `DejavuSansMono`, but that's why I suggested trying just `monospace`. On my machine it maps to the dejavu font and I imagine it is a somewhat universal placeholder on Linux. I can select it like any other font in Libreoffice Writer and my terminal and it looks like the dejavu font, as it should.

I'd try if `mono` also resolves it like that. Seems to be the most platform independent.

```
$ fc-match monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"
```

For what it's worth, I've been using Mesen at least since 0.9.6 and the font didn't work back then as well.

**Comment by SourMesen** [comment]
Alright, I got rid of the whole bit where it tried to install DroidSansMono, and instead set it to default to "monospace" for Linux.  Hopefully this allows it to work on all setups.  If you happen to test it on your end, let me know if it works.

Thanks!
