### ISSUE TITLE
Son son (Japan) Flickering

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#764]
------------------------------------------------------
Loading rom: Son Son (Japan).nes
File CRC32: 0xF7C8F42D
------------------------------------------------------
[DB] Initialized - 15541 games in DB
PRG CRC32: 0x06093B5E
PRG+CHR CRC32: 0x10BAEEF3
[iNes] Mapper: 0 Sub:0
[iNes] PRG ROM: 32 KB
[iNes] CHR ROM: 8 KB
[iNes] Mirroring: Vertical
[iNes] Battery: No
[DB] Game found in database
[DB] Mapper: 0  Sub: 0
[DB] System : Famicom
[DB] Board: HVC-NROM-256
[DB] Mirroring: Vertical
[DB] PRG ROM: 32 KB
[DB] CHR ROM: 8 KB
[DB] Battery: No
[DB] Database info will be used instead of file header.
[Input] 2 standard controllers connected

Mesen 0.99 Windows 10

https://www.youtube.com/watch?v=ygCzSXu1g74

**Comment by SourMesen** [comment]
Thanks for the report.
This seems like it's a normal hardware issue though: https://www.youtube.com/watch?v=pdqIRgrg0fs
