### ISSUE TITLE
[Libretro core request] Have independent overscan settings for each screen side

### ISSUE THREAD

**Issue by sammy2142** [SourMesen/Mesen#765]
It would be great if we could have independent options for overscan settings in the core i.e.
Top 
Bottom 
Left 
Right
As some roms require different amounts of pixel cropping each side.

For example Kirby's Adventure (USA) works best with 8 Top 8 Bottom 16 Left and 8 Right.

**Comment by SourMesen** [comment]
Thanks for the request.  The overscan settings have been split in 4 separate options and now let the user pick between 0/4/8/12/16 pixels for each edge.
