### ISSUE TITLE
Mesen hangs when emu.reset() executed

### ISSUE THREAD

**Issue by lazydogP** [SourMesen/Mesen#768]
Here's how I reproduce it in Mesen 0.9.9:

1. Load any game.
2. Open Script Window, delete all the content, type `emu.reset()`.
3. Run the script.

**Comment by SourMesen** [comment]
Thanks for the report - this is fixed by 73ef5f21e9d3b8165ed598a46164691054cc7bcf

emu.reset() and a few other functions are no longer called outside of event/memory callbacks (they were never meant to be called this way)
