### ISSUE TITLE
Cannot run version 0.9.9

### ISSUE THREAD

**Issue by michel-iwaniec** [SourMesen/Mesen#769]
Excited to finally see the new 0.9.9 new release... but unfortunately it seems I cannot even get it to load a ROM.

Starting the .exe first gives me this error messagebox: 
![ErrorMessage](https://user-images.githubusercontent.com/46843052/74108206-b21e3a80-4b6f-11ea-963c-ed00286b2210.png)

Trying to load a .nes file via File -> Open appears to do nothing. (after loading the file, nothing happens)

Trying to load a previously loaded file by clicking on it in the start-up screens grid OTOH gives me yet another error message box:
![ErrorMessage2](https://user-images.githubusercontent.com/46843052/74108319-0bd33480-4b71-11ea-8ea3-fcd834bda269.png)

Funnily enough, this new 0.9.9 version of Mesen appears to incorrectly says "0.9.8" in the lower-right corner of the start-up screen. But I've had no troubles with 0.9.8.

Am using Windows 7 Professional, Service Pack 1.

**Comment by SourMesen** [comment]
If the new "0.9.9" has 0.9.8 written in bottom right, this most likely means that you've ended up with the 0.9.9 UI, but running the 0.9.8 dll.

This most likely means that Mesen is unable to write to the MesenCore.dll file it needs to extract when starting.  If you've just attempted an auto-update, it looks like there might be issues with the auto-update for windows 7 users, which sometimes ends up with a mesen.exe process staying alive in the background.

Try checking task manager and killing any mesen process you find, and/or try rebooting your PC.

**Comment by michel-iwaniec** [comment]
> looks like there might be issues with the auto-update for windows 7 users, which sometimes ends up with a mesen.exe process staying alive in the background.

Doh! You're right, killing the ghost mesen.exe seems to have fixed everything... thanks for the quick reply! :)

**Comment by SourMesen** [comment]
No problem!
