### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by ThallesAps** [SourMesen/Mesen#77]
Hi, first of all, thank you for your hard work on this emulator, you've put a lot of effort on it.

I've made a brazilian-portuguese translation of the emulator, based on the spanish one, but for some reason I can't make a pull request. I didn't write the coding part, though. The pastebin link(or you can just look in my fork): http://pastebin.com/Qx0isNP5

It's not 100% complete, there are 4 lines that I can't figure out(at least yet) how to translate correctly. The lines are 108,109,110,175.

And to finish all this, I'd like to recommend you write a tutorial of how to translate the emulator in the readme or in your site. Thanks again :)

**Comment by SourMesen** [comment]
Thank you for the translation and support!
It's always nice to be able to add another language to Mesen :)

You're absolutely right - I need to write a how-to for the translation process (and a guide for the emulator in general).  I just can't find the time to get documentation done!

There's just a small thing missing from your translation, though.  In the file:
https://github.com/ThallesAps/Mesen/blob/master/Core/MessageManager.cpp
There is a block of code/text for each language supported - could you add one for brazilian-portuguese and translate those texts too?  They're the texts that are shown on the game screen when loading save states, etc.

Thanks again!

**Comment by ThallesAps** [comment]
Didn't see that, my bad. Unfortunately I'll be on vacation for 2 weeks, so if you don't mind waiting a little bit, I'll translate that file as well(and hopefully the missing lines).

**Comment by SourMesen** [comment]
No problem, not in a hurry :) 
Let me know when you're done and I'll integrate it into the emulator.

Enjoy your vacation!

**Comment by ThallesAps** [comment]
Hey, so I've had some spare time and finished the translation.
Again, the MessageManager.cpp file was based on the spanish translation as well. Also, I've translated the missing lines(except for 175, I think it's better this way) and I've made a few tweaks in general.
So if you think everything is okay, it's good to go. Thanks again :)

**Comment by SourMesen** [comment]
Thank you for the translation!  I just committed it, so it'll be available in the next release (75e0de636e3b90840911894dfca9c204f164466d)
Sorry that the translation process is so messy!  The English text is in the actual code, this makes it a lot easier for me to develop, but makes it a lot harder to find the resources when translating. :(

If you have any corrections you want to make, let me know.

Thanks again!
