### ISSUE TITLE
Rasberry Pie 4 Question

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#771]
I Have a Rasberry Pie 3B+ and Mesen runs a little slow on it so I'm thinking about getting the Pie 4 and wanted to know if Mesen and Mesen-S runs at full speed ? Also does it matter about the memory I get? I'm thinking about getting the 2GB model. 

I could not get Mesen-S to run on the Pie 3B+ all l got was a black screen

Lakka Nightly 2020-01-24

**Comment by SourMesen** [comment]
I'm not quite sure about the performance for Mesen-S (not sure about the black screen either.)
Really need to get a raspberry pi and do some testing with it someday.

For Mesen, I've heard that it runs much faster on a Pi 4 vs Pi 3.  According to this spreadsheet it's 3x faster: https://onedrive.live.com/view.aspx?resid=CA4C3FA509AF1016!314785&ithint=file%2cxlsx&authkey=!AAKV4-LVo1GCONE

I don't think RAM should have much of an impact for Mesen(-S), since it should only be using like 10-50mb of ram or so in general.

If you end up buying one and manage to get Mesen-S running on it, please let me know how fast/slow it works.

**Comment by Cibomatto2002** [comment]
I just ordered one with 2GB the price was good $67.99 it should be here in a week I will let you know how it goes. If it does not run Mesem-S do you want me to tell you?

Here is the one I ordered 

https://www.amazon.com/Vilros-Raspberry-Fan-Cooled-Heavy-Duty-Aluminum/dp/B07XTRFD3Z/ref=sr_1_8?crid=2N05LXHIBWFAQ&keywords=raspberry%2Bpi%2B4&qid=1581578714&sprefix=ras%2Caps%2C230&sr=8-8&th=1

Do you think if you added frame skip that it would help Mesen with the pie 3B+ ?  

Thanks for the link it was good reading it helped a lot. :)

**Comment by Cibomatto2002** [comment]
I got my Rasberry Pie 4 Today and Mesen runs what looks like full speed on every game I tried but Mesen-S did not load so I got mu Log file for you to see maybe it will say something that makes it not work.
[retroarch__2020_01_20__18_30_22.log](https://github.com/SourMesen/Mesen/files/4209497/retroarch__2020_01_20__18_30_22.log)

**Comment by SourMesen** [comment]
Thanks - I'm not quite sure why Mesen-S isn't loading based on that log, though.  There doesn't appear to be any obvious error messages in there.

What happens when you load a game? A blank screen?  No audio?  Both?  Does the FPS counter show 60fps?

**Comment by Cibomatto2002** [comment]
No audio A black screen even the FPS will not show.  When I exit Mesen-S the Pie will freeze for maybe 10 seconds or so before I get control over it.

**Comment by 1985a** [comment]
Hello there. I don't have a rpi4 yet, but I saw this problem on my installation.
BTW, I have been facing these issues in other cores like mame, so could you test loading a game with a new retroarch's configuration.

Just make a copy of your actual config.

Note: apparently shaders made me or some kind of stranger configuration that problem.

**Comment by Cibomatto2002** [comment]
I don't use retroarch only Lakka I could install retroarch and try it out for you but I have no idea how to get the configuration you want.

**Comment by Cibomatto2002** [comment]
I just sent this to Lakka-LibreELEC maybe we will get a answer.

https://github.com/libretro/Lakka-LibreELEC/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopedirectory+

**Comment by SourMesen** [comment]
I have a feeling the black screen on Mesen-S is most likely the same bug as this: https://github.com/SourMesen/Mesen-S/issues/103
So hopefully it should already be fixed.
If you still have issues with the latest builds, feel free to open up an issue on the Mesen-S repository.

**Comment by Cibomatto2002** [comment]
When Lakka comes out with a new nightly I will try it again.
