### ISSUE TITLE
Nuts & Milk (Japan) Bug Maybe

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#774]
I'm not sure if this is a bug or not in Mesen it may be something Retroarch is doing.

![Capture](https://user-images.githubusercontent.com/21169038/74762883-57a66d80-5244-11ea-9615-147f61f85218.jpg)

**Comment by SourMesen** [comment]
You have different overscan settings in both.  The standalone is cutting off the top & bottom 8 pixels, which hides that part of the game. The glitch itself is normal, as far as I know.
