### ISSUE TITLE
Bug: Mesen is inconsistent with the way it handles key assignments for an alternate keyboard layout

### ISSUE THREAD

**Issue by Bohman-Timothy** [SourMesen/Mesen#775]
I recently installed an alternate keyboard layout that I use sometimes: the [Colemak keyboard layout](https://colemak.com/). The layout itself works fine, and so does switching between the Colemak layout and the default English US keyboard layout by using the shortcut provided by Windows (Windows key + Space bar). There is a minor problem in Mesen, though, concerning the shortcuts that are displayed in the File and Game menus. Each shortcut key on the keyboard remains the same when I switch between the two layouts, but the letter displayed for the shortcut in the File menu or Game menu is the letter that the *inactive* keyboard layout has assigned to the specific key on the keyboard, e.g. Ctrl + O is shown for Open when the Colemak layout is active and Ctrl + Y is shown for Open when the default English US layout is active. See screenshots below.

Mesen file menu shortcuts swapped - default US keyboard layout
![Mesen_file_shortcuts_swapped_default_US_keyboard_layout](https://user-images.githubusercontent.com/32476451/74888312-a2f77380-534b-11ea-81e0-16ae7c2c029e.png)

Mesen file menu shortcuts swapped - Colemak keyboard layout
![Mesen_file_shortcuts_swapped_Colemak_keyboard_layout](https://user-images.githubusercontent.com/32476451/74888315-a2f77380-534b-11ea-8f5f-52c669120aae.png)

Mesen game menu shortcuts swapped - default US keyboard layout
![Mesen_game_shortcuts_swapped_default_US_keyboard_layout](https://user-images.githubusercontent.com/32476451/74888314-a2f77380-534b-11ea-8c58-56cada8cd578.png)

Mesen game menu shortcuts swapped - Colemak keyboard layout
![Mesen_game_shortcuts_swapped_Colemak_keyboard_layout](https://user-images.githubusercontent.com/32476451/74888313-a2f77380-534b-11ea-9283-76fc10a167f2.png)

I haven't seen this problem in any other program on my computer, emulator or otherwise (though, admittedly, I haven't tested every emulator I have just for this issue). The other two NES emulators I use, FCEUX and VirtuaNES, simply don't update the shortcut displayed in menus when I switch between keyboard layouts. Like Mesen, though, the physical key on the keyboard assigned to each shortcut remains unchanged.

The shortcut letters in the Debug menu do not change when I switch between layouts; they just show the same letters all the time, but the physical keystroke changes according to the change in keyboard layout (e.g. Ctrl + D for the Debugger). I haven't tested every shortcut in the Debug menu, but I suspect they all also update the physical keystroke with the change in keyboard layout. I think this is the preferred behavior for shortcuts when switching between keyboard layouts.

The physical keys assigned for controller input remain the same when switching between keyboard layouts. I prefer this for controller input specifically, because I can play a game without worrying about switching to the "right" keyboard layout for proper finger placement on the keyboard. The letters shown in the controller input screen do not update when the keyboard layout is changed, nor do they show the active keyboard layout's letter for a key when you assign a new one, so this behavior could be changed to show the active keyboard layout's letter for the assigned keys. However, it may be simpler/easier to have the key placement on the keyboard update with an alternate layout's change in letter placement to be consistent with shortcut keys, if shortcut key behavior is consistently made to do this.

Also, when viewing and assigning shortcut keys in the Preferences dialog, only the default English US keyboard layout's letter assignments are shown, and the physical keys assigned for these shortcuts do not update when the keyboard layout is changed.

I know these are relatively minor issues, but I wanted to share my findings and my opinions on them because Mesen is inconsistent with itself when an alternate keyboard layout is involved.

**Comment by Bohman-Timothy** [comment]
When the Colemak layout is active, there are two shortcut conflicts between the File and Game menus, and the Debug menu.

**Ctrl + O (Open)** - Uses the same physical key on the keyboard despite the change in layout.
**Ctrl + Y (Performance Profiler)** - Uses the Y key in its new position in the alternate layout.
The Colemak keyboard layout moves the Y key to where the O key is on the QWERTY layout, so Y and O overlap for the two shortcuts stated above.

**Ctrl + R (Reset)** - Uses the same physical key on the keyboard despite the change in layout.
**Ctrl + P (PPU Viewer)** - Uses the P key in its new position in the alternate layout.
The Colemak keyboard layout moves the P key to where the R key is on the QWERTY layout, so P and R overlap for the two shortcuts stated above.

**Comment by SourMesen** [comment]
Thanks for the report!

This is actually something I had been aware of for a while, but never got around to fixing it (you are only the 2nd person to report this.)

It should be fixed as of the latest commit (and latest appveyor build), but running that build will reset all of your non-debugger shortcuts to their default values (because I had to change the way the keys were saved in the configuration file)

Let me know if you still have issues with this.

(Also, Mesen-S has the same bug - will fix that in a bit, too)

**Comment by Bohman-Timothy** [comment]
I've tried the dev build, and the issues appear to be resolved. Thank you!

**Comment by SourMesen** [comment]
Great - thanks for the confirmation!
