### ISSUE TITLE
[Feature request] Better Linux support

### ISSUE THREAD

**Issue by jhlkek** [SourMesen/Mesen#780]
Standalone Mesen looks and acts really different from most other Linux applications because it uses mono to support Linux instead of having its own GTK/Qt frontend like bsnes.

**Comment by SourMesen** [comment]
Unfortunately, this will not happen. Rewriting Mesen's entire UI and its debugger tools in either GTK or Qt would take several months of my time, and would reduce the speed at which I can develop the UI in the future.  

While I agree it doesn't look quite right on Linux, it works, which is good enough. If you do not like Mesen's current UI, I can only recommend to use another emulator on Linux (e.g puNES, Nestopia UE or FCEUX)
