### ISSUE TITLE
AccessViolationException when taking a screenshot

### ISSUE THREAD

**Issue by huhu9001** [SourMesen/Mesen#781]
I am using Mesen 0.9.9. I can not take any screenshots from any game.
![d1](https://user-images.githubusercontent.com/14960102/75225483-a4aab680-57e5-11ea-80c2-b86aebf1186d.jpg)

**Comment by SourMesen** [comment]
Thanks for the report!
This only happens when a video filter is turned on, and is fixed by cfc5bf6976f62ebd42ea30d5a803c138fc357509.
