### ISSUE TITLE
[Future Request] Please move the "Tools" from "Debug" to the same line

### ISSUE THREAD

**Issue by ReverseDmitry** [SourMesen/Mesen#785]
It is very annoying to always go to debug just to open "Tools" tab. It has many useful features I would love to get easy access at any time. I had hard time to find it the first time, so I just assumed this emulator does not have it. Please move the "Tools" to the main bar. 
![Tools](https://user-images.githubusercontent.com/58607111/76116741-9a659500-5ffb-11ea-9a59-c7cd885f2281.png)

**Comment by SourMesen** [comment]
I'm not sure I understand?  The contents of the "Tools" menu in the debugger are essentially identical to the "Debug" menu in the main window (which is visible on your screenshot)

**Comment by raousoft** [comment]
For me I memorized almost every keyboard shortcut, I rarely open that menu. But I agree, adding them to the tools menu as a sub-menu would make it easy for new users to get used to it till they memorize the keyboard shortcuts (or unless they don't use keyboards somehow :3 ).

**Comment by SourMesen** [comment]
Like I said, the contents of the "tools" menu in the debugger window are *already* available in the "Debug" menu on the main window. This has been possible for years by enabling "developer mode" in 0.9.8 and before, and is the new default in 0.9.9 (the "developer mode" option no longer exists.)

I don't think there's anything that needs to be done/changed here.
