### ISSUE TITLE
Next generation NTSC-filter algorhytm (integer-only math) by Bisqwit

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#79]
Hi, Sour 
I have an interesting request.
Since mesen is most advanced and feature-full NES emulator, can you add support of
new NTSC-Filter algorithm?

http://forums.nesdev.com/viewtopic.php?p=172329#p172329

Blargg's NTSC filter is good, but bisqwit's filter have some advantages over it, including:
- moire is more accurate
- notch is more accurate
- integer math gives good speed
- PAL-Filter can be easily done over this algorithm by slightly modifing it.

I'll write more info soon.

**Comment by SourMesen** [comment]
I just added this in 641192236eaf152840edc6ca28732e8c365f39cf
It's relatively slow, so the filter uses 2 threads to process the picture (this allows my old i5 to run it at 60fps at 8x resolution, which is the "native" resolution for the ntsc code)
There might be some bugs left, though.  Let me know what you think!

**Comment by eugene-s-nesdev** [comment]
New filter is amazing, thank you very much! 
It looks very close to NTSC Famicom AV.
Color-generation accurate too.

**Comment by SourMesen** [comment]
Thanks - I'll close this for now, let me know if you find any issues.
