### ISSUE TITLE
Debugger: Can't figure out how to turn off "label" display

### ISSUE THREAD

**Issue by binarycow** [SourMesen/Mesen#792]
Hello,

Somehow I inadvertently actived some form of "label" display in the debugger.  In the below screenshot, on line C5FD, the disassembly is `JSR F072D = $EA`.  This used to display as `JSR $872D = $EA`.

I remember toggling an option, and decided I did not like the changed behavior, and turned it off.  After restarting either the debugger, or Mesen as a whole, the label display is shown, and I can't find the option to turn it off.  (I swear, I poked around the debugger - nothing I changed seemed to take effect!)

![image](https://user-images.githubusercontent.com/37249876/77544988-268f0d80-6e80-11ea-9d1a-95f6b3df76e0.png)

**Comment by SourMesen** [comment]
That looks like the "Create automatic jump label" option?  Once they are created, they are real labels.  You'll need to delete them, either by resetting the workspace's labels (there's an option for this under "File"), or manually selecting and deleting them from the label list (you might need to right-click on the label list and enable the option to show the automatic labels before you can do this)

Hope that helps,
