### ISSUE TITLE
Lua script gets deleted / overwritten by Built-in Script example

### ISSUE THREAD

**Issue by NESblast** [SourMesen/Mesen#798]
I found a fairly nasty little bug in the Lua Script Editor. It is reproducible as follows:

- Open Script Window
- Create a new script (myLuaScript.lua)
- Save it (myLuaScript.lua)
- Select Built-in Scripts
- Select any Built-in Script
- Make any change to Built-in Script
- If [X] Auto-Save before running is checked, just hit Run
- Otherwise Hit Save

Congratulations! Your (myLuaScript.lua) script has now been overwritten by the Built-In example Script! Bye bye work!

Anyway i am enjoying Mesen and LUA scripting alot (when they don't get overwritten) so i just want to end on a positive thank you! Keep up the good work!

**Comment by SourMesen** [comment]
Thanks for the report - sorry if you lost some work due to this!
This should be fixed as of the latest commit (you can grab the next appveyor build linked in the readme for the fix.)

Also fixed the same issue in Mesen-S

**Comment by NESblast** [comment]
Thanks for fixing this! No worries!

I didn't lose too much due to having some source control =)
