### ISSUE TITLE
Upgrade to blargg's blip buffer 0.4.1?

### ISSUE THREAD

**Issue by trioan** [SourMesen/Mesen#799]
http://blargg.parodius.com/libs/Game_Music_Emu-0.5.2.zip

This has the latest 0.4.1 library version; Mesen uses 1.1.0.

**Comment by SourMesen** [comment]
The link you gave uses blip_buffer, Mesen uses blip_buf - these are different libraries.
As far as I know, Mesen uses the latest version of blip_buf (and a new release hasn't been done in several years)
