### ISSUE TITLE
master volume sliders corresponding

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#80]
When you move slider 1 -> slider 2 change own value according to slider 1
But when you move slider 2 -> slider 1 won't change value until you touch it.

![sliders](https://cloud.githubusercontent.com/assets/13199529/21213596/b609a008-c2a6-11e6-85dd-3adbbecc31e5.png)

**Comment by SourMesen** [comment]
Thanks for the report!
After pressing "OK" on the audio options dialog, the NSF player's slider will now update its position (63e8fbb839171016651561321568d35832f0396c)
