### ISSUE TITLE
For Multi-byte labels distinguish first byte

### ISSUE THREAD

**Issue by mraiford** [SourMesen/Mesen#804]
When you have several multi-byte labels adjacent to one another, it can be difficult to tell when one label ends and another begins. 

I would be helpful to have the first byte of a multi-byte label made distinct from the rest of the bytes. (Either user selectable color or darkening or lightening either the first byte or additional bytes.)

This would also help slightly with an issue with editing labels where if you choose a byte different to the first byte and edit the label, it updates the label's address to the clicked address, rather than the original address the label was assigned to

**Comment by SourMesen** [comment]
Thanks for the report/request!
The "edit label" function on multi-byte labels should no longer change the address - that was a bug.
Labelled bytes except the first byte of the label will now be shown with a lighter color (calculated from the labelled byte color)
