### ISSUE TITLE
I need this for MacOS. Are there any plans?

### ISSUE THREAD

**Issue by bsudhir6** [SourMesen/Mesen#806]
Hi I desperately need this emulator Mac OS. I am not able find a suitable and perfect emulator like mesen. Please let me know if there is a plan to release for Mac OS.

Thanks,
Sudhir.

**Comment by SourMesen** [comment]
Unfortunately, no.  Due to issues/lack of support in Mono, a MacOS version isn't possible at the moment.

See:
https://github.com/SourMesen/Mesen/issues/396
https://github.com/SourMesen/Mesen/issues/638
etc.
