### ISSUE TITLE
Can't set inputs for my generic USB NES controller

### ISSUE THREAD

**Issue by Birizinho** [SourMesen/Mesen#81]
Every time I set any input on the controller menu, it appears a pop-up that quickly closes itself, and the input "Joy 2 DPad Up" is shown on the respective rectangle. However, the input has no connection with any of the inputs of my controller (It doesn't even perform the "Up" command on my controller's D-Pad) and all of the pre-existent inputs (Keyboard, Xbox, PS4, SNES30) doesn't match the inputs of my controller.

This issue only happens on Mesen since I tried to input my controller on Nestopia (both the standalone emulator and the libretro core), FCEUX, puNES and none of them reported any issues or input lag from the controller's end.

**Comment by SourMesen** [comment]
Thanks for the bug report!
I've made a few tweaks/fixes to the DirectInput code (8132c5cb253a6d0af194707cc4e4ca370a68ef8f) - and I'm hoping this will fix your problem.
If you still have the same problem in the next version of Mesen, please reopen this bug and let me know.
