### ISSUE TITLE
Problems with "Edit Cheat" function

### ISSUE THREAD

**Issue by Evan-Nirkuta** [SourMesen/Mesen#814]
Excuse me, sorry to bother.
Thanks a lot for all your hard work on Mesen !
I have some problems with the "Edit Cheat" function:

![Edit Cheat problems](https://user-images.githubusercontent.com/64546300/80620340-3f10bb80-8a1c-11ea-9538-69dd2279e1a4.jpg)

The "OK" button is not working at all, even if I change from "Game Genie" to "Pro Action Rocky" or "Custom"... :(
Am I doing something wrong ?
Best regards,
Evan.

**Comment by SourMesen** [comment]
I'm not sure what type of code that's supposed to be, but that's not supported by Mesen.
You'll want game genie codes (6 or 8 letters, no signs or numbers, e.g: "ZASZYTPA"), or pro action rocky codes.

The OK button will become enabled when you enter a valid/supported code.

**Comment by raousoft** [comment]
@SourMesen 

That's basically an inline cheat code for FCEUX
the middle part is RAM and 01 means cheat enabled
Nothing important for sure , just wanted to share :3

As for @Evan-Nirkuta , you can pass the RAM 00A0 (or just A0) to the Custom field (with Memory enabled) and 01 for the value and hit OK :)
