### ISSUE TITLE
mesen crashes when manually disconnecting from netplay

### ISSUE THREAD

**Issue by properchopsticks** [SourMesen/Mesen#817]
hi,

i noticed that whenever you're connected to netplay, if you disconnect by going to options > netplay > disconnect it crashes the application. i'm not sure if it's working as intended but i thought i should post a ticket. it also happens if you start a server and then stop it. it's worth mentioning it only happens if no game is loaded. if a game is loaded none of the crashes happen, neither on client nor on host.

i'm using the dev build 0.9.9.31 that fixed the frame loss issue on netplay. i'm also using windows 10 and i tried the bug over hamachi both with a friend and with a virtual machine and it has the same effect.

**Comment by SourMesen** [comment]
Thanks for the report!
This should be fixed as of the latest commit.
