### ISSUE TITLE
Glitches on Fighting Hero 3

### ISSUE THREAD

**Issue by litaniast** [SourMesen/Mesen#819]
I ran Fighting Hero 3(Unlicensed fighting game for NES by NTDEC) on Libretro Mesen core.
After I select a character, the game glitches like that.

![Fighting Hero 3-200504-065131](https://user-images.githubusercontent.com/4857928/80926708-dc307300-8dd3-11ea-8d49-328ca469ca9b.png)

**Comment by SourMesen** [comment]
Thanks for the report!
This should be fixed now.
