### ISSUE TITLE
Full screen is small without a filter on.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#82]
Sorry I do not know how to reopen my old bug with this problem.

The bug is still in 0.6.1. If you set the video size to 1 with a filter off you will get a small picture setting it to  2 makes it bigger setting it to 3 will fill the screen. Maybe this will help i'm using a Element ELEFW328 32" 720p 60Hz Class LED HDTV.

![1](https://cloud.githubusercontent.com/assets/21169038/21470070/133d29f4-ca3e-11e6-85e6-73e703f121e7.jpg)

![2](https://cloud.githubusercontent.com/assets/21169038/21470072/183e6da0-ca3e-11e6-89c6-7366782c6679.jpg)

![3](https://cloud.githubusercontent.com/assets/21169038/21470073/1c94190e-ca3e-11e6-908b-71c4e37edf63.jpg)

**Comment by SourMesen** [comment]
Could you attach your settings.xml file please? There might be something in there that is causing this to be different on your end.
You can find it the Documents\Mesen folder.

**Comment by Cibomatto2002** [comment]
[settings.zip](https://github.com/SourMesen/Mesen/files/672282/settings.zip)

**Comment by Cibomatto2002** [comment]
I made a video on how to fix it you need to make the window screen the same size as the full screen for it to work right.

https://www.youtube.com/watch?v=-cM1UPzHBu4&feature=youtu.be

**Comment by Cibomatto2002** [comment]
If you select None as a filter the screen is small.

![capture12-25-2016-4 30 54 pm](https://cloud.githubusercontent.com/assets/21169038/21473104/de36538e-cabf-11e6-8b71-d400c50b5fd7.jpg)

**Comment by SourMesen** [comment]
I still can't reproduce this on my end, but I made a few other tweaks in 0.7.0.
Let me know if you still get this problem in 0.7.0

**Comment by Cibomatto2002** [comment]
It's ok now.
