### ISSUE TITLE
Graphics issues with Mario 7-in-1

### ISSUE THREAD

**Issue by anonymous7002** [SourMesen/Mesen#823]
There is an unlicensed game called "Mario 7-in-1", which uses Mapper 52.
There are graphics issues in most of those games when played on Mesen.
The bug is at least in Mesen 0.9.8, 0.9.9 and Dev versions.
The same bug is in FCEUX. FCEU 0.98 works fine.

What it should be:
![hqdefault](https://user-images.githubusercontent.com/57062013/81278622-9c30f080-905e-11ea-8995-7cc99ee7f23f.jpg)

What it is in Mesen and FCEUX:
![Mario 7-in-1 (Mapper 52)  p1 ! _000](https://user-images.githubusercontent.com/57062013/81279097-532d6c00-905f-11ea-98dd-f131e1051ec3.png)

**Comment by anonymous7002** [comment]
Sorry for the different sizes of images, forgot to resize.

**Comment by SourMesen** [comment]
As far as I can tell, some versions of that ROM have the data in the wrong order, which causes this glitch.  Older emulators probably emulate the mapper incorrectly, which lets them display the graphics properly.

(I did fix another bug I found with mapper 52 while testing this, though)
