### ISSUE TITLE
Game "Gaiapolis" (part of the screen flashing)

### ISSUE THREAD

**Issue by AlanRibas** [SourMesen/Mesen#825]
I was playing a game called Gaiapolis.
I realized that under the screen. Just above the hourglass, there are a few pixels flashing. Maybe a bug?
This part of the game is already right after starting the game.
I made a video showing.

https://www.youtube.com/watch?v=bTZAQ04NeJw

**Comment by heckez-sys** [comment]
@AlanRibas i think its acting like smb3(pixels flash when music is playing

**Comment by AlanRibas** [comment]
> i think its acting like smb3(pixels flash when music is playing)

I don't understand what you said. So is this a normal thing? Do you see this in the original game?

**Comment by SourMesen** [comment]
Flickering like this is very common on the NES, tons of games do this.
I haven't been able to find any footage that really looks like it was taken on hardware, but based on what the game is doing at that point in the picture, it's unavoidable that some flickering would be present there.  (Any video that doesn't have that flickering was most likely recorded with a low accuracy emulator)

**Comment by AlanRibas** [comment]
I understood.

So there's nothing to do right ...

**Comment by SourMesen** [comment]
No problem!
