### ISSUE TITLE
Garbage on the right side of the screen 

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#83]
There is garbage on the right side of the screen the left side is OK. it's like it's trying to load part of the left side on the right.

![capture12-25-2016-1 45 19 am](https://cloud.githubusercontent.com/assets/21169038/21470217/458cfc62-ca44-11e6-9f99-70dbbd43f22e.jpg)

**Comment by SourMesen** [comment]
This might be related to the crashes you are getting - I'm not getting this on my end though.
Can you see that bar with any video filter/scale?

**Comment by Cibomatto2002** [comment]
If I turn off the video filter it's fine. Any filter I use will do the garbage on the screen.

**Comment by SourMesen** [comment]
Are you sure? On my end it's only 2xSai, Super2xSai and SuperEagle that are causing this issue.
It looks like the original code for these filters is incorrect and can attempt to read invalid memory (and cause the display glitch you noticed) - so it is possible that these are causing crashes if you are using them.

**Comment by Cibomatto2002** [comment]
You are correct the filters you named are the only ones that are causing the issue. Sorry about telling you it was all of them I tried a few filters and they was doing it so I was thinking they all did it.

**Comment by SourMesen** [comment]
Thanks for the report!
This is fixed by 06031da2d4515d0bdc90bdc4e60d52d53e110cd9
