### ISSUE TITLE
Broken on Contra (Japan)

### ISSUE THREAD

**Issue by litaniast** [SourMesen/Mesen#832]
![Contra-200517-215943](https://user-images.githubusercontent.com/4857928/82147310-d33aa980-9889-11ea-98b3-987612b2b62e.png)

I used libretro to run Mesen. I ran the Japanese version of Contra, it stuck on green screen and escalating sound.

**Comment by SourMesen** [comment]
Thanks for the report - looks like this was broken recently by some other changes that uncovered an emulation bug.

This is fixed in the latest commit.

**Comment by NiBBa256** [comment]
I am experiencing the same bug in Sonic 3D Blast 6
