### ISSUE TITLE
Can't access screenshots taken on a dev version

### ISSUE THREAD

**Issue by anonymous7002** [SourMesen/Mesen#835]
When you take a screenshot on a dev version, you can't access it. There is no screenshot folder.

**Comment by SourMesen** [comment]
This seems to work fine for me - deleting the screenshot folder and taking a screenshot recreates the folder.

Do you have characters that aren't typical in the path to your screenshot folder?  Did you override the screenshot folder in your settings?  Does Mesen have the rights to create/write to that folder?

**Comment by heckez-sys** [comment]
Ꭓbox

**Comment by SourMesen** [comment]
I can't help without any additional information.  If someone else has the same issue, please let me know.
