### ISSUE TITLE
can you please add support for MacOS X plz?

### ISSUE THREAD

**Issue by juney2008** [SourMesen/Mesen#841]
i really love this emulator and i really want to play it on my mac computer. can you please make a MacOS X port of this emulator for me? i will appreciate it if you do!

**Comment by SourMesen** [comment]
Thanks for the request. Unfortunately, there is no way to support MacOS at this time without rewriting the entire UI (which would take months) or improving support for WinForms on MacOS in Mono (which I am not able to do myself).

Also see these issues for more information: #806, #638, #521, #367, #123

**Comment by litaniast** [comment]
You can use Mesen as libretro core.

**Comment by NiBBa256** [comment]
You can use Retroarch on Mac.
