### ISSUE TITLE
I can't play an English patched of DBZ Kyoushu Saiyajin

### ISSUE THREAD

**Issue by Leonheart0819** [SourMesen/Mesen#846]
Salutations. I'm loving your emulator but I can't play the game I mentioned in the title with your emulator for some reason. I'm wondering what can I do to alleviate this issue? Thanks in advance.

**Comment by raousoft** [comment]
I tested it , works perfectly.
![image](https://user-images.githubusercontent.com/37517008/83953652-d6e2a000-a839-11ea-8b9e-916b0ece66d1.png)
..
https://drive.google.com/file/d/11sZHfDRxqQRTXMM6R33Likvxl3q3jEUm/view

I think you did not patch the ROM very well , corrupt patch or the ROM ?

I used This Patch:
https://www.romhacking.net/hacks/4342/

With No-Intro rom of course:
`Database match: Dragon Ball Z - Kyoushuu! Saiya Jin (Japan)`
`Database: No-Intro: Nintendo Entertainment System (v. 20180803-121122)`
`File SHA-1: FCA563B8E4DE797A448085839DC7F5F7484ADA91`
`File CRC32: D78484B7`
`ROM SHA-1: 4037DB53D45DB20E3A131D722DCD317ADC966DEB`
`ROM CRC32: 183859D2`

Mesen's Build:`(DevWin-0.9.9.56)`

**Comment by Leonheart0819** [comment]
Wait, what rom do I patch that on to?

**Comment by Leonheart0819** [comment]
I have the No-Intro NES and I can't get it to work. I patched other roms and they work on your emulator. I don't know what's going on here.

**Comment by Leonheart0819** [comment]
It only plays when I don't have the rom patched in Mesen. Which I don't understand? It also doesn't play in Nestopia either. Maybe you are right about that. Can you show me how you patched it?

**Comment by raousoft** [comment]
@Leonheart0819 

Yeah sure, I used LunarIps
https://fusoya.eludevisibility.org/lips/

Run it , click on Apply patch , select the patch file first
then select the ROM and that's it

**Comment by Leonheart0819** [comment]
That's exactly what I did.

**Comment by raousoft** [comment]
and you used the same patch I used ?

**Comment by Leonheart0819** [comment]
Yea, I did. You know what's funny? I tried on my laptop and it works but not on my desktop. I tried to delete everything and do it on my desktop and it still doesn't work.

**Comment by raousoft** [comment]
Try to download another build of Mesen (Try latest dev build)
https://ci.appveyor.com/project/Sour/mesen/build/artifacts

Copy it to an empty folder to anyplace you like (for example desktop)
and run it and choose : Store the data in the same folder as the application

and give it a try

**Comment by Leonheart0819** [comment]
I will give it a try.

**Comment by Leonheart0819** [comment]
Yea, it's not working and also it stopped working on my laptop as well. For me only the raw version of the Rom works but every other English patch works. IDK what to do.

**Comment by raousoft** [comment]
How did it stop working on your Laptop , I mean like.. what exactly happened the game closes as (Unofficial OP code ?) or it runs but glitchy ?
Try this :
Load the original ROM (Unpatched)
then drag and drop the patch file into Mesen , It will ask you to patch and reset the game click OK
it will soft patch the ROM.

**Comment by Leonheart0819** [comment]
Yea, none of my roms matched the hashes you put. Is there any site that has that?

**Comment by raousoft** [comment]
Aha, so the problem it's in the ROM.
Since sharing ROMs online is illegal , you gotta find out how to get it.

The hashes I provided is for the original ROM, a clean dump of the original cartridge and headered.
Just google : Nes No-Intro Set archive
and you can find a lot there!

**Comment by Leonheart0819** [comment]
Man, thanks. It's crazy since like damn near 20 years ago I've been playing on a bad rom lol.

**Comment by Leonheart0819** [comment]
IT WORKS!!!!!! THANK YOU, MAN.

**Comment by SourMesen** [comment]
@raousoft  Thanks for taking the time to help figure this out!

**Comment by mark21gt** [comment]
Could you please test this game (and the translation patch) again? It seems that it doesn't work anymore, it just shows a green screen:

![image](https://user-images.githubusercontent.com/69425805/89734354-fbbde400-da31-11ea-9c3a-70a6517041b6.png)

**It does work on Mednafen** though  (I personally don't use this emulator for NES games though, I'm saying and showing this just to confirm that the ROM should be working):

![image](https://user-images.githubusercontent.com/69425805/89734369-20b25700-da32-11ea-9fa4-4818f14c2765.png)

About the emulator and ROMs I'm using:

**Mesen version:**
Both the current stable release and current unstable build from GitHub.
**CRC32 of the unpatched ROM (from No-Intro):** - It works in Mesen without the patch.
62fa9f0a
**CRC32 of the patched ROM** (with https://www.romhacking.net/translations/647/ - _without the BP hack!_) - It doesn't work in Mesen now, but it does work on Mednafen.
84aeceb7

**The patch you guys were talking about before (with the BP hack included) also won't work** on Mesen but it will also work on Mednafen (again, I'm just saying this to confirm that the ROM itself should be working).
