### ISSUE TITLE
SONY CXA2025AS palette

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#86]
Hi, Sour. Can you add SONY CXA2025AS decoder palette to mesen package?
It comes with puNES / BizHawk / FCEUX packages:
https://sourceforge.net/projects/fceultra/files/Binaries/2.2.3/fceux-2.2.3-win32.zip/download

Thank you.

**Comment by SourMesen** [comment]
Thanks for the suggestion.
Added this in 1c5a44c20e9bdb22e521ad4f1acef4ec29ee9ea4
