### ISSUE TITLE
Key shortcut to exit emulation (enhancement)

### ISSUE THREAD

**Issue by florere** [SourMesen/Mesen#90]
Hello,

It would be very nice to add a "quit" key shortcut so you can exit emulator with a gamepad key combination (usefull for when using a frontend to launch the emulator for example).

Btw thank you for making this great emulator, it's the best nes emulator i ever tried :)

**Comment by SourMesen** [comment]
Thanks for the suggestion, and sorry for the slow response!
I added a configurable shortcut key to exit Mesen (7e35d5b99e5431c52cc492a624163a1a1fcc400b), you should be able to exit Mesen using your gamepad with this.
