### ISSUE TITLE
Integer Scale Not available

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#91]
Could it be added?

**Comment by SourMesen** [comment]
I'm not sure what you mean - are you talking about scaling the image?
You can already scale it using integer values

**Comment by PinkLouie** [comment]
Scale only by whole values, 2x, 3x, 4x, eetc. Lock this. You will get black borders. This is good for precision, especially when you use scanlines and certains shaders.

**Comment by SourMesen** [comment]
You can already do this - just press Alt-1 to Alt-6 to set it to 1x to 6x.
If you are not in a maximized window, the window will resize to fit.  Otherwise you will get black borders around the image.

**Comment by PinkLouie** [comment]
Having an option to set and lock integer scale graphically would be better. And alt+1 in fullscreen do not works correctly. It conflits with the composite ntsc filter I use. +1 looks +2.
![2017-01-07 3](https://cloud.githubusercontent.com/assets/24971871/21742802/c90512b0-d4d4-11e6-83de-88c1f63eb84b.png)
![2017-01-07 4](https://cloud.githubusercontent.com/assets/24971871/21742803/c90c73de-d4d4-11e6-936b-b7a5d27131a2.png)

**Comment by SourMesen** [comment]
This is because filters change the "base" resolution for the emulation, this is also by design.
NTSC roughly doubles the resolution, so 1x becomes ~540x240.
If you used xBRZ x4, then the "1x" scale would be 1024x960 because of the filter.

Basically, "1x" scale always displays exactly the output of the filter without alteration - its actual resolution varies.

**Comment by PinkLouie** [comment]
I understand now, but in windowed mode, windows size could be an indepent configuration. Easily the game screen gets biggets than the monitor itself. It is bad if you want a small windowed mode, and a  full screen with shader to alternate, without changing anything.

**Comment by SourMesen** [comment]
Closing this - see #104 for some changes I made in regards to scaling.
Keeping two different configurations (scale, filter, etc.) for fullscreen vs windowed mode would result in a confusing UI - so I'd rather not implement that.
