### ISSUE TITLE
N163 expansion bug

### ISSUE THREAD

**Issue by ajp9** [SourMesen/Mesen#92]
The implemented Namco 163 board for NSF playback renders sound at the wrong rates (lower octave).

**Comment by SourMesen** [comment]
Is your "Region" setting set to the correct region for the NSF you're playing? You might be playing it in PAL region while it's an NTSC song, for example.

Are you saying the wrong rate is used only in NSF files?  I just compared the same track in Megami Tensei 2 (in both the game and the NSF) in Mesen, Nestopia and FCEUX, and it sounds the same to my ears for all 6 of them.

Did you try the same NSF file in other emulators? Which NSF file is it?

**Comment by ajp9** [comment]
I've tested many files from the 2A03_v3_0.zip archive, and the results just aren't right, compared to other emulators. Changing the region doesn't help.

However, I see that you're right about Megami Tensei 2 - it works, listening to several tracks. Maybe this is an issue with third party rips?

Here's a small NSF from the 2A03_v3_0 archive, and results from Mesen and an FCEUX relative that handles it better.
[Soldier_Blade-NSF-sample.zip](https://github.com/SourMesen/Mesen/files/691996/Soldier_Blade-NSF-sample.zip)

**Comment by SourMesen** [comment]
Thanks for looking into this!
It looks like both Nestopia UE & Nintendulator sound pretty much like Mesen, while FCEUX is the only one that sounds different.  FCEUX is not very accurate when it comes to a lot of details, so in this case, I would assume the correct behavior to be the one heard in Nestopia & Nintendulator.
