### ISSUE TITLE
Wrong Aspect Ratio

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#93]
Aspect Ratio in games is wrong, even if "auto" is chosen. It gets right if you choose a NTSC shader (composite for example) Otherwise, for example, 4:3 looks wider than it is sometimes, or simply wrong. See the difference in the printscreens.

![2017-01-07 2](https://cloud.githubusercontent.com/assets/24971871/21742593/d7103820-d4d0-11e6-8987-d919cd6dafe6.png)
![2017-01-07 1](https://cloud.githubusercontent.com/assets/24971871/21742594/d72949fa-d4d0-11e6-809f-c0aa6b40dba9.png)

**Comment by SourMesen** [comment]
This is by design - "Auto" means "use the native resolution for that filter, with no stretching".
The NES outputs a 256x240 picture, so that is the aspect ratio you get with "Auto".  The NTSC filter automatically stretches the picture to ~550x240 due to the way it works, so that's why you get a different aspect ratio with it.

**Comment by PinkLouie** [comment]
"auto" should means "4:3" because the games were design to be displayed anyway. Just see the better circles look in 4:3. If i set 4:3 with ntsc the game gets wider than 4:3. 
![2017-01-07 6](https://cloud.githubusercontent.com/assets/24971871/21742851/acdea762-d4d5-11e6-8747-cc9a94fd61b5.png)

**Comment by SourMesen** [comment]
In my opinion, the default should be pixel-perfect rendering with no stretching (since stretching can introduce blurring or artifacts).  I could rename the option from "Auto" to "Default" or something similar, I suppose.

**Comment by PinkLouie** [comment]
So, it seems impossible to use ntsc shader and mantain 8:7 aspect ratio.

**Comment by SourMesen** [comment]
I'm not sure what you mean?  If I select the NTSC filter & select the "NTSC (8:7)" aspect ratio, the picture measures roughly 12.8cm by 11.2cm on my screen, which is exactly a 8:7 ratio?

**Comment by PinkLouie** [comment]
I just get confused by all of these. Sorry. I think it can be closed, if it is not a bug or anything to be changed :X

**Comment by PinkLouie** [comment]
I mean, "auto", will Always be changed by ntsc shader, it is not possible to mantain "auto" AR, with ntsc shader on.

**Comment by PinkLouie** [comment]
What about if "auto" chooses the aspect ratio based in the  rom region? Actually it Works different then "NTSC (8:7)" in a NTSC rom.  Seems weird.
![Uploading 2017-01-15 (1).png…]()
![2017-01-15 2](https://cloud.githubusercontent.com/assets/24971871/21965768/a06e0b52-db4d-11e6-8c64-9ae323b63d43.png)

**Comment by PinkLouie** [comment]
In Auto mode, a square have different weight and width. The ideal for a square, is a perfect square. See the blue square above. Circle is also perfect. Then you try to add a ntsc shader, and it is streched. It seems confusing for a lot of users.

**Comment by PinkLouie** [comment]
Acording to [http://andrew.hedges.name/experiments/aspect_ratio/](url) 224px x 256px is 7:8, so 7:8 should be "pixel perfect", right? But it is not, it is more narrow then that, it is 224:240. Maybe "auto" have a wrong configuration? Maybe it is not detecting the game resolution correctly?

**Comment by PinkLouie** [comment]
It seems also, nes game resolution can change from game to game, 224:256, 240:256, 224:240, etc.

**Comment by SourMesen** [comment]
NES resolution is always 256x240, for all games, and all regions (NTSC, PAL)
The different "resolutions" are only caused by the old CRT TVs hiding portions of the screen.
"Auto" will always display a 256x240 picture, but you can hide portions of it (like a CRT does) using the overscan settings.  This does not change the aspect ratio, however.

**Comment by PinkLouie** [comment]
So, sorry for all the confusion.

**Comment by PinkLouie** [comment]
Read this if you have time: https://forums.nesdev.com/viewtopic.php?f=2&t=8063&sid=47f5f03261ac5bd557e5efccc97165d4&start=15

**Comment by PinkLouie** [comment]
Maybe pixel aspect ratio info next to aspect ratio info, (4:3 - 1.25 for example) would be nice. Another suggestion is to add customizable pixel aspect ratio, would by amazing.

**Comment by PinkLouie** [comment]
I Think I discovered the best (or almost best) configuration to play nes games in Mesen, after a lot of read. Crop 8px down, up, and right, and 9 left. The result is a game (native 256x240), cropped to 239x224, then stretched to 8:7. The result is a game measuring 256:224 (same resolution of perfect pixel with just 8px cropped up and 8px down), It do not affect the resolution of screenshots taken with messen which a based early. This configuration should be an"optimized" profile, ou default, or something else maybe. It is the coolest nes emulator.
![image](https://cloud.githubusercontent.com/assets/24971871/21971212/a84f0d7e-db95-11e6-8891-fb9dcd8b0d7b.png)

**Comment by PinkLouie** [comment]
Hi. Today I noticed the horizontal scroll in tremulous when I use other aspect ratio then "auto", 8:7 for example, and bilinear filtering is disabled. Duck tales gets temulous and glitching when scroll.

**Comment by SourMesen** [comment]
I've added an option to set a custom aspect ratio (can be anything from 0.1 to 5.0), this should take care of any aspect ratio related problems. (d6db1d50c5166a92e90d5d49c74036e3f7c9ff01)
As for the issues when the aspect ratio is not auto, this is basically what I was saying at the beginning.  The "auto" option is the pixel-perfect ratio.  Anything else needs to resize the screen, which means some pixels will be bigger than others, which can cause "glitches" when the screen moves.
