### ISSUE TITLE
Video output

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#94]
We have monochrome, composite, s-video, and rgb video output shaders, right? But initially, NES do not used any of these, it come with RF cable which is, from the point of view, worst. Can you please, add RF output please? It is already available in retroarch, and would be a great adition to mesen. https://github.com/libretro/RetroArch/tree/master/gfx/video_filters

**Comment by SourMesen** [comment]
According to RetroArch's code, RF and Composite are the same.  The only difference is the "Merge Fields" option.  RF has "merge fields" disabled, Composite has "merge fields" enabled. 

https://github.com/libretro/RetroArch/blob/f855e80933d235c4cc34c617ddb7dd0ccf8f939d/gfx/video_filters/blargg_ntsc_snes.c#L83

So the "Composite" option in Mesen is equivalent to "RF" in RetroArch by default.  If you check "Merge Fields", you get the same as the "Composite" option from RetroArch
