### ISSUE TITLE
Final Fantasy 3 (CHS)(waixing) crash

### ISSUE THREAD

**Issue by ckmop** [SourMesen/Mesen#95]
ROM：http://pan.baidu.com/s/1kVJjy9h
![ff3chs](https://cloud.githubusercontent.com/assets/4145768/21797582/d5113d18-d74a-11e6-8e3a-016a158f7a3e.JPG)
The rom is said to be an unencrypted rom
Thx

**Comment by SourMesen** [comment]
Thanks for the bug report!
It looks like this game is listed as a MMC3 game, but isn't actually 100% compatible with a real MMC3.
It's an easy fix, though.

**Comment by ckmop** [comment]
Thx, looking forward...

**Comment by SourMesen** [comment]
This is fixed by d96854144486058e059dc2e1c8e50cb761cf8df6

**Comment by ckmop** [comment]
Thx, Great Work!

**Comment by ckmop** [comment]
Well... it seems to be broken in 0.8.1 again...

**Comment by SourMesen** [comment]
I just tested 0.7.1, 0.8.0 and 0.8.1 - they all seem to be working fine.
Is it the exact same issue as before? A green screen + CPU crash?

**Comment by ckmop** [comment]
Sorry...I dont know what happened yesterday, maybe it was an occasional case, it stuck at a grey screen, but today I test it again, and it runs just fine.
