### ISSUE TITLE
Random rom

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#98]
Sugestion: add option for open a random rom from rom directory. It's useful when you do not know what to play.

**Comment by SourMesen** [comment]
Thanks for the suggestion.
This is already available, though!
It's under the "Tools" menu, "Load Random Game"

**Comment by PinkLouie** [comment]
All my roms are in a folder called "Emulation", but a changed this folder's name to "emulação". Load Random Game gives me an error, even if a rename the folder back to "emulation".
![2017-01-13](https://cloud.githubusercontent.com/assets/24971871/21936036/e3f3c816-d996-11e6-8b92-f4f99d7b060c.png)

**Comment by SourMesen** [comment]
Thanks for the bug report, I'll take a look at this soon.

**Comment by SourMesen** [comment]
This is fixed by 535a2e45f0a910ba11a2a8b0cb122afed1c78032
