### ISSUE TITLE
Add website/download link to main Github page

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#99]
Add a http://www.mesen.ca/index.php URL to https://github.com/SourMesen/Mesen project description

**Comment by SourMesen** [comment]
There is already a link to the website - at the very top of the page, in the repository's description:
"Mesen is a cross-platform (Windows & Linux) NES/Famicom emulator built in C++ and C# http://www.mesen.ca"

Downloads are available from that link & the "Releases" tab (https://github.com/SourMesen/Mesen/releases) on GitHub, I think that should be good enough?

**Comment by Nicholas-Steel** [comment]
True, I didn't notice that at all obviously. I was paying attention to the readme.md section which completely excludes mention of where to download pre-compiled builds.

**Comment by SourMesen** [comment]
I've added links to the website & releases in the readme

**Comment by Nicholas-Steel** [comment]
Awesome stuff.
